### ISSUE TITLE
Prevent payment cancellation when payment in batch

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1004]
In GitLab by @JobDoesburg on Feb 12, 2020, 20:41

### One-sentence description

Prevent payment cancellation / changes when payment in batch

### Why?

When a payment is added to a payment batch (#932), it must stay in there and may not be changed or deleted anymore.

### Current implementation

This might be possible

### Suggested implementation

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Feb 12, 2020, 21:05

According to !1415 this shouldn't be possible, but we should definitely write tests for this

**Comment by JobDoesburg** [comment]
Solved in #1044
