### ISSUE TITLE
Event looks like registered for though on waiting list

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1007]
In GitLab by @JobDoesburg on Feb 17, 2020, 15:49

### One-sentence description

When on the waiting list for an event, it still looks like you are registered for that event.

### Current behaviour / Reproducing the bug

- In the calendar stream, the event does appear in your calendar
- Cancelling your registration does show the warning that you have to pay a fine, if after the unregistration deadline
- In the event overview calendar, the dot in front of the event is colored as if you are registered.

### Expected behaviour

- Do not appear in the calendar stream
- Do not show a message that you cannot unregister without having to pay a fine, but something different more fit to the situation
- In the event overview, show some other, pending-ish, colored dot.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 17, 2020, 21:31

The thing is that you are registered for an event when you're on the waiting list. That's how we see it from a implementation point of view and that is how it is shown to the user as well.

I do not necessarily think all of these things classify as a ~bug. Only that you get a warning about a fine is a bug in my eyes. The rest would be ~feature improvements since the functionality currently really is to show events you are registered for, which includes the events with a queue. That you want to improve the visibility for events where you're on the waiting list by changing the colour is not something I would consider to be a bug.

Apart from what could already be discussion with many opinions I would like to add one small possible point to the mix: none of these things are related in the sense of 'code'. Just in the sense that they're related to user experience of the waiting lists for events. I would thus say they are separate issues. If only we had epics..

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Feb 17, 2020, 21:55

Maybe it is a bug because it is unexpected behavior from the user point-of-view. 

And sorry for not making the issues, I was being lazy :smiling_imp:

**Comment by se-bastiaan** [comment]
I have split up this issue in the above three tasks.
