### ISSUE TITLE
Replace Docker image used by Renovate

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1010]
In GitLab by @joren485 on Feb 28, 2020, 12:09

### One-sentence description
Replace Docker image used by Renovate.

### Why?
Apparently Renovate still uses [`thalia/python-thalia`](https://hub.docker.com/r/thalia/python-thalia). `thalia/python-thalia` is outdated and not automatically updated.

### Suggested implementation
Either [`renovate/python`](https://hub.docker.com/r/renovate/python) or [`thalia/concrexit-dependencies`](https://hub.docker.com/r/thalia/concrexit-dependencies).

**Comment by se-bastiaan** [comment]
this is no longer required since we use the github app now
