### ISSUE TITLE
Topic should be visible in https://thalia.nu/user/finance/payments/

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1020]
In GitLab by @JobDoesburg on Mar 11, 2020, 21:05

### One-sentence description

Topic should be visible in https://thalia.nu/user/finance/payments/

### Current behaviour / Reproducing the bug

The topic field is not visible 

### Expected behaviour

Be visible

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 11, 2020, 23:51

I thought the topic was only for batches? Why would we also show it if there is already the note.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Mar 11, 2020, 23:52

It was mainly 'invented' for batches, but we now move information like the event for which was paid from the notes to the topic, so we can / must still show it to users

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 11, 2020, 23:54

Did we move that? I did not know we did that. You're just assuming that. 
https://gitlab.science.ru.nl/thalia/concrexit/-/blob/master/website/events/models.py#L651

I'm pretty sure we discussed this and the conclusion was that we need topic for the batches but that notes are human readable for the users.

**Comment by se-bastiaan** [comment]
I'm closing this since (as far as I know) we are keeping the notes as well and thus showing the topic to users is not really necessary.

I'd be happy to discuss this if someone thinks it would be better to only include the topic of something like that.
