### ISSUE TITLE
Think of a way to improve partner logo's in dark mode

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1021]
In GitLab by @JobDoesburg on Mar 11, 2020, 21:18

### One-sentence description

Think of a way to improve partner logo's in dark mode

### Motivation

With current dark mode, some partner logo's look a bit weird

### Desired functionality

They should look good both in dark mode and light mode.
**Both in the banner, and in the vacancy pages**

### Suggested implementation

It is hard to do this correctly for all logo's. One way is to add a css filter in dark mode that makes the logo's more white. Another way could be to just support a dark mode and light mode logo.

**Comment by se-bastiaan** [comment]
I believe an easy solution would be to remove the constrast of the logos by using `contrast(0)`
![Screenshot 2020-03-29 at 13 33 53](https://user-images.githubusercontent.com/1799914/77848045-1352a980-71c2-11ea-8b81-439501dd7bf3.png)

Or make them black by using `brightness(0)`
![Screenshot 2020-03-29 at 13 34 21](https://user-images.githubusercontent.com/1799914/77848046-1483d680-71c2-11ea-9185-56408230752b.png)

Or white using `grayscale(1) brightness(100)`
![Screenshot 2020-03-29 at 13 36 33](https://user-images.githubusercontent.com/1799914/77848069-5745ae80-71c2-11ea-8a9a-aff98c4142dc.png)

**Comment by se-bastiaan** [comment]
Ah but that does not work for the logos of Quintor and CCV

![Screenshot 2020-03-29 at 13 38 23](https://user-images.githubusercontent.com/1799914/77848102-9a078680-71c2-11ea-95cd-ac84259a9da9.png)

**Comment by se-bastiaan** [comment]
![Screenshot 2020-03-29 at 13 58 18](https://user-images.githubusercontent.com/1799914/77848488-65e19500-71c5-11ea-8ff9-01930f159fc8.png)
If we fix the logos it would work fine

**Comment by se-bastiaan** [comment]
What do you think @JobDoesburg

**Comment by JobDoesburg** [comment]
I like what you did @se-bastiaan (that last one)
