### ISSUE TITLE
Missing translations in information check email

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1028]
In GitLab by @pingiun on Dec 4, 2019, 19:22

### One-sentence description
Information check email has some missing translations

### Current behaviour / Reproducing the bug
Send an information check email, notice some weird text missing.

### Expected behaviour
Information check mail contains correct translations

**Comment by thaliawww-service** [comment]
In GitLab by @pingiun on Dec 4, 2019, 19:28

![image](https://gitlab.science.ru.nl//thalia/concrexit/uploads/31ae1a8576e389b525e82e6703be5ae9/image.png)

There is also a spelling mistake: "changige". This email should be in Dutch but there is no translation

**Comment by thaliawww-service** [comment]
In GitLab by @marthijnvdn on Jan 29, 2020, 21:03

When I use ./manage.py sendinformationcheck, both languages appear to be correct.

**Comment by thaliawww-service** [comment]
In GitLab by @marthijnvdn on Feb 19, 2020, 21:13

assigned to @marthijnvdn

**Comment by se-bastiaan** [comment]
I believe this has been fixed in another PR
