### ISSUE TITLE
Paper thabloid opt-out in user profile

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1072]
### Is your feature request related to a problem? Please describe.
Paper thabloid opt-out in user profile

### Describe the solution you'd like
A checkbox or something (default is True) that allows people to state they don't want to receive the thabloid on paper. 

A filter for this checkbox must be added to the user admin as well.

### Motivation
There are quite some people who send mails that they don't want to get paper thabloids because they read them online and think it is a waste of paper. We currently have no good way of administering this.

### Describe alternatives you've considered
Yes, we could make a spreadsheet, but that means we will need to filter out all these addresses after we downloaded them, and it means we have to do it all manually. A checkbox on the user profile is so much easier.

### Additional context
Before people start the discussion, this is actually discussed by the board. I'm just writing the issue because I know GitHub (and I'm chair of the thabloidcie)

**Comment by se-bastiaan** [comment]
_is_ discussed or _was_ discussed? was there anything _decided_?

anyways, this is a feature that should be part of the member administration since that is where it belongs. and the core task of the website is to do the member administration. So if this is something we are going to support there is no discussion indeed :p

**Comment by se-bastiaan** [comment]
@JobDoesburg

**Comment by JobDoesburg** [comment]
> _is_ discussed or _was_ discussed? was there anything _decided_?
> 
> anyways, this is a feature that should be part of the member administration since that is where it belongs. And the core task of the website is to do the member administration. So if this is something we are going to support there is no discussion indeed 🙃

I won't talk for the board but some people thought 'hey we might want an opt-out'. Then the thabloidcie said 'that's a thing the board should decide' and then Tim said 'yeah we want this'.
