### ISSUE TITLE
Clarifying text on summary reward

### ISSUE THREAD

**Issue by gitLabor8** [svthalia/concrexit#1096]
Hi! I know you're less productive due to Corona, but on behalf of the educacie and with approval of the board I have this two-sided feature request. Thanks in advance!

### Is your feature request related to a problem? Please describe.
1) There is a rule in place that let's us reward the industrious students that write summaries and show them to others via [the Course Overview](https://thalia.nu/education/courses/). However, barely anyone knows this.

2) The feedback system for this rule, as people now just randomly get money on their bankaccounts. This might be confusing.

### Describe the solution you'd like
1) I want to show a little text to everyone visiting the course overview page.

2) Adding a field in the summary upload form in which the uploader can give his phone number. (maybe just a consent button and then take the phone number of the profile) This way we can contact them about it! 🌈 

### Motivation
It will encourage people to send in summaries and clear up the obscureness of this rule.

### Describe alternatives you've considered
Not do 2) or give people the option to type their own phone number instead of taking it from their account.

### Additional context

The little text mentioned before:

> You can submit your own summary! Better even, you might even get a monetary reward if your summary is:
> 
>  - In the current language of the course
>  - Adds significant information that was not already present in the summary overview
>  - Corresponds to the current course
>  - Is positively peer-reviewed by people appointed by the educacie
> 
> Don’t forget to authorise us to use your phone number, so we can inform you about your possible reward.

> 
> Je kan je eigen samenvatting inleveren! Beter zelfs, je kan zelfs een kleine geldelijke vergoeding krijgen als je samenvatting aan het volgende voldoet:
> 
>  - Hij is in de taal van de cursus
>  - Hij voegt significante informatie toe die niet in eerdere samenvattingen aanwezig was
>  - Hij moet overeenkomen met de inhoud van het vak
>  - Hij moet positief gepeer-reviewed worden door mensen die aangewezen zijn door de educacie
> 
> Vergeet ons niet toestemming te geven tot je telefoonnummer, dan kunnen we je op de hoogte houden van je mogelijke beloning.

**Comment by se-bastiaan** [comment]
The phone numbers in the user accounts are taken based on consent. Given that they're optional. So if people have entered a phone number we are allowed to just give you the phone number in the admin.

The privacy policy states:
> Thalia uses the phone number of members, benefactors and honorary members to communicate with members about activities of Thalia. Think about calling a participant who is too late for an activity or communicating a last-minute change.The processing of phone numbers by Thalia is optional. Processing of these data happens based on consent, which is given implicitly when the phone number is entered during registration or on the user profile on the website. 

Since giving people money for summaries is an activity of Thalia this can be seen as valid use of the information. And thus we can show profile information of the Thalia user in the summary admin for you to use without any extra consent.

**Comment by 9Y0** [comment]
Reopened since the `ul` shouldn't look like this ![](https://i.gyazo.com/b57bcc08d8b898c8b0e9107c5bd757fe.png)

**Comment by se-bastiaan** [comment]
@gitLabor8 This has been released
