### ISSUE TITLE
Use a different colour for waiting list events

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1116]
### Is your feature request related to a problem? Please describe.
In the event overview calendar, the dot in front of the event is colored as if you are registered. And this is confusing.

### Describe the solution you'd like
Use a different colour for events you're on the waiting list for.

### Motivation
Better user experience.

### Describe alternatives you've considered
There is not really any alternative

### Additional context
Created based on #1007

**Comment by pingiun** [comment]
This can probably be found in https://github.com/svthalia/concrexit/tree/master/website/events/templates/events

**Comment by se-bastiaan** [comment]
No, the colour is retrieved from the API.

**Comment by ColonelPhantom** [comment]
I'm wondering about what would be a proper design for this. What color would be nice in this case? And do we maybe want a coloured dot for events someone is registered for as well?

Also, from what I can find, the colors are added using CSS classes, which are in turn received from the API.
