### ISSUE TITLE
Personal iCal feeds show events that you are on the waiting list for

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1117]
### Describe the bug
In the calendar stream, the event does appear in your calendar even if you're only on the waiting list

### How to reproduce
Steps to reproduce the behaviour:
1. Make sure you are on the waiting list for an event
2. Check that it appears in the ical feed

### Expected behaviour
Not showing the event in the ical feed if you're on the waiting list.

### Additional context
Created based on #1007

**Comment by pingiun** [comment]
Turns out it's pretty hard to select these events in a query. I tried to do it in sql first, and came up with this query:
```sql
SELECT
	events_event.*
FROM (
	SELECT
		*,
		ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY events_registration.date) AS c_id
	FROM
		events_registration
	WHERE
		events_registration.date_cancelled IS NULL) AS valid_reg
	RIGHT JOIN events_event ON valid_reg.event_id = events_event.id
WHERE
	c_id <= (
		SELECT
			max_participants
		FROM
			events_event
		WHERE
			events_event.id = event_id)
		AND member_id = %user_id;
```

**Comment by se-bastiaan** [comment]
I personally think that being on the waiting list should actually show in your personal calendar, at least I prefer it that way since I'm still hoping to be at the event. If it is not in my calendar I will easily forget it.

**Comment by pingiun** [comment]
That's fine with me too, I think we can close this then
