### ISSUE TITLE
Membership page shows 'you are a benefactor' if user does not have any memberships

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1142]
### Describe the bug
Membership page shows 'you are a benefactor' if user does not have any memberships and language is Dutch

### How to reproduce
Steps to reproduce the behaviour:
1. Be a user without memberships
2. Set your language to Dutch
2. Visit `/user/membership/`
3. It says "You are a benefactor, contact the board (...)" (in Dutch)

### Expected behaviour
It should say something like "you don't have any memberships in your history", possibly with some button to start a registration.

### Screenshots
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/7915741/83964058-7a6b9900-a8aa-11ea-8e67-0ca69ea60d8a.png">

**Comment by JobDoesburg** [comment]
I wouldn't say this is very important since this scenario doesn't apply that often in practice, yet it is still a bug

**Comment by se-bastiaan** [comment]
![Screenshot 2020-06-07 at 11 02 29](https://user-images.githubusercontent.com/1799914/83964598-69248b80-a8ae-11ea-95cf-ccb452c841fe.png)

**Comment by se-bastiaan** [comment]
This is a wrong translation.
