### ISSUE TITLE
Can't add bank account without active membership

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1143]
### Describe the bug
Users without memberships cannot add a bank account to their account because they don't have the permissions.

### How to reproduce
Steps to reproduce the behaviour:
1. Be a user without an active memberships
2. Try to add a bank account via `/user/finance/accounts/add/`
3. Permission denied

### Expected behaviour
This should still be possible, since the fact that someone can authorize Thalia is not directly related to the fact that they are not a member right now. Even, when we would start using Thalia Pay for membership renewals, it is required that users that don't have an active membership can add their bank account.

**Comment by se-bastiaan** [comment]
This only needs removal of the decorator

**Comment by se-bastiaan** [comment]
I am pretty sure this was solved, since I did exactly this yesterday in my demo.

**Comment by JobDoesburg** [comment]
Correct, I fixed it in the TPay for renewals issue :)
