### ISSUE TITLE
Fix link to Gitlab in footer

### ISSUE THREAD

**Issue by thomwiggers** [svthalia/concrexit#1149]
### Describe the bug
Thalia's stuff is no longer on Gitlab.

### How to reproduce

![image](https://user-images.githubusercontent.com/974662/84596766-e5dfd880-ae5f-11ea-9bcc-1d1795e36af3.png)

**Comment by se-bastiaan** [comment]
Was changed in #1041, we just have not released since the March.

**Comment by thomwiggers** [comment]
The last time we had such a long release lapse we replaced the website :joy:
