### ISSUE TITLE
Display honorary membership start date

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1155]
### Is your feature request related to a problem? Please describe.
I am interested in when people became honorary member, but you can't find it on the website. However for admins, this data is visible

### Describe the solution you'd like
On the profile page of honorary members, display the date they became honorary member

### Motivation
The members administration has this information

### Describe alternatives you've considered
Asking the board to log in to the admin and show the profile...

### Additional context
Neuh

**Comment by JobDoesburg** [comment]
Note that it is subtly different from the cohort of the honorary member!

**Comment by se-bastiaan** [comment]
Like this for example :)

![Screenshot 2020-08-11 at 14 15 27](https://user-images.githubusercontent.com/1799914/89896080-213b2100-dbdd-11ea-988d-4fbef2aa1159.png)

**Comment by JobDoesburg** [comment]
Exactly! (but with a $d-$m-$Y date…)
