### ISSUE TITLE
The webpage of newsletter 264 says "CafÃ© Van Ouds" instead of "Café van Ouds"

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#1176]
### Describe the bug
The webpage of newsletter 264 says "CafÃ© Van Ouds" instead of "Café van Ouds"

### How to reproduce
1. Go to [the webpage of newsletter 264](https://thalia.nu/newsletters/264/).
2. Scroll down to the craft beer borrel.

### Expected behaviour
"Café van Ouds"

### Screenshots
![2020_08_03_12_30_33](https://user-images.githubusercontent.com/7031489/89173843-2668f200-d585-11ea-813b-3ddd1d47edbb.png)

### Additional context
I tried to quickly reproduce this, but I was not able to.

**Comment by pingiun** [comment]
This might be dependent on email clients. This looks like the email client defaulting to ISO/IEC 8859-1:1998, when the email was sent with UTF-8 encoding. Maybe a header can be set to inform the email client of the UTF-8 encoding

**Comment by joren485** [comment]
This does not seem to occur in the email clients I tried, but on [the web version of the newsletter](https://thalia.nu/newsletters/264/).

**Comment by pingiun** [comment]
Ah then this should be a super easy fix. A meta tag should be added to the created web page:

```html
<meta charset="utf-8">
```
