### ISSUE TITLE
Member statistics is missing data

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1179]
### Describe the bug
Member statistics is missing data

### How to reproduce
Steps to reproduce the behaviour:
1. Go to https://thalia.nu/members/statistics/
2. Check the 'total number of (honorary) members and benefactors per cohort)
3. Where is all the data?

### Expected behaviour
Nice data graph including data of normal members.

### Screenshots
![Screenshot 2020-08-11 at 14 09 27](https://user-images.githubusercontent.com/1799914/89895848-c1dd1100-dbdc-11ea-8245-f8806d7d05f6.png)

**Comment by joren485** [comment]
As I said in the duplicate #1180:

>The statistics page has a graph showing the amount of benefactors and honorary members per cohort. However, the graph shows members that are currently a benefactor or a honorary member that had a membership (of any type) in a certain cohort. 
>
>For example, currently the graph tells us there are two benefactors and zero honorary members in the year 2017 (which I assume is academic 2017-2018). A lot more benefactors signed up that year and there was one (or two, depending on how you count) honorary member that year.

**Comment by se-bastiaan** [comment]
If you mean Mats by the honorary member then he is categorised under 'Older' because he is cohort (started his studies in) 2011. Any benefactors from 2017 may also have other cohorts because they started studying in earlier years. Or if they're missing here: they are no longer a benefactor.

**Comment by joren485** [comment]
Mats wasn't a honorary member in 2011, so he should not be counted as a honorary member for "Older", but as one for 2017. In my understanding, the graph should show benefactors and honorary member memberships that started in the specific cohorst.

**Comment by se-bastiaan** [comment]
The cohort you see here is the value that is in the admin 'Starting year' and the confusion is exactly why the field was changed from 'cohort' to 'starting year'. The term cohort as used by the university is the year you started in. Even though I my membership status will change from member to benefactor at some point my cohort will always stay 2014.

**Comment by joren485** [comment]
The graph shows exactly that. For example, there are 2 people from cohort 2017 that are currently benefactors.

What would you like to see changed?

**Comment by se-bastiaan** [comment]
The graph is missing every single non-honorary member.

**Comment by joren485** [comment]
No it is not, the graph shows the current benefactors that had some type of membership for each cohort year on the graph ([for example 2017 has 2 benefactors](https://thalia.nu/admin/auth/user/?membership=benefactor&profile__starting_year=2017)).

**Comment by se-bastiaan** [comment]
Benefactor != non-honorary member

We have three types here:
- Benefactor
- Member
- Honorary member

Every user with the membership of type Member is missing.

**Comment by joren485** [comment]
Alright, I think we are talking about two different issues here. I will reopen my issue.
