### ISSUE TITLE
Benefactors/honorary member statistics show wrong on statistics page

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#1180]
### Describe the bug
The statistics page has a graph showing the amount of benefactors and honorary members per cohort. However, the graph shows members that are currently a benefactor or a honorary member that had a membership (of any type) in a certain cohort.

For example, currently the graph tells us there are two benefactors and zero honorary members in the year 2017 (which I assume is academic 2017-2018). A lot more benefactors signed up that year and there was one (or two, depending on how you count) honorary member that year. 

### How to reproduce
Steps to reproduce the behaviour:
1. Go to the [statistics page](https://thalia.nu/members/statistics/)
2. Look at the graph called "Total number of (honary) members and benefactors per cohort" (sic).

### Expected behaviour
The graph should show how many memberships of a specific type (either benefactors or honorary memberships) started in each year.

**Comment by joren485** [comment]
Duplicate of #1179

**Comment by joren485** [comment]
After some discussion, it turns out that this issue is not a duplicate.

- #1179 is about adding member data to the "Total number of (honary) members and benefactors per cohort" graph.
- This issue is about the wrong (or at least confusing) statistic that the "Total number of (honary) members and benefactors per cohort" graph is tracking.

**Comment by se-bastiaan** [comment]
The cohort you see here is the value that is in the admin 'Starting year' and the confusion is exactly why the field was changed from 'cohort' to 'starting year' in that admin. The term cohort here is the one used by the university as the year you started in. Even though my membership status will change from member to benefactor at some point my cohort will always stay 2014.

Doesn't mean we can clarify the title by changing it from 'cohort' to 'starting year' or something along those lines.

**Comment by joren485** [comment]
I prefer changing the statistic it is tracking, because I don't think the statistic it is tracking now is that interesting.

I find "How many benefactors did we have in year x" more interesting than "How many current benefactors did have some type of membership in year x". I also find the first statistic less confusing.

**Comment by se-bastiaan** [comment]
That is also fine, but in that case it would be a feature request and not a bug report :p

**Comment by joren485** [comment]
Well I do think it is a bug, because it does not show the statistic that it is intended to show. But I guess it depends on what it is intended to show.
