### ISSUE TITLE
Events presence registration in app creates payment

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1198]
### Describe the bug

Events presence registration in app creates payment

### How to reproduce
Steps to reproduce the behaviour:
1. Create an event with registrations
2. Register
3. Mark the registration as present _in the app_
You can simulate this by going to the registration using the API on `/v1/api/registrations/` and patching the body:
```
{
    "payment": "no_payment",
    "present": true
}
```
4. Note that a payment with the status 'no payment' is created for this registration

### Expected behaviour

No payment should be created

**Comment by 9Y0** [comment]
Looks like it is an issue [here](https://github.com/svthalia/concrexit/commit/732015365471404dbceb20d2bcf8995e55dc6016#diff-fea01ddf09080902cc7967c2de85b792R295-R299) introduced by #1173 

Can't test it since I couldn't get the app running

**Comment by se-bastiaan** [comment]
Mmm it is not really possible for #1173 since it never been released on production.
