### ISSUE TITLE
Change registration contribution from FloatField to DecimalField

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1229]
### Describe the change
We currently user FloatFields for contribution amounts. We should use DecimalField's.

### Motivation
Events also use DecimalFields for the price of an event. Also, consider [https://docs.python.org/3/library/decimal.html#module-decimal](https://docs.python.org/3/library/decimal.html#module-decimal)

### Current implementation
FloatFields

### Suggested implementation
Just change it

**Comment by se-bastiaan** [comment]
This is also a good read: https://stackoverflow.com/questions/2569015/django-floatfield-or-decimalfield-for-currency

**Comment by se-bastiaan** [comment]
This is also a good read: https://stackoverflow.com/questions/2569015/django-floatfield-or-decimalfield-for-currency
