### ISSUE TITLE
Translation missing on Vacancies pages

### ISSUE THREAD

**Issue by mark-boute** [svthalia/concrexit#1232]
In the filter tab of the [Vacancies](https://thalia.nu/career/vacancies#) page there are two missing translations for 'bijbaan' and 'stage'

![image](https://user-images.githubusercontent.com/33718602/93689590-5c7c1a00-fad0-11ea-8b51-b13875e8f900.png)

**Comment by se-bastiaan** [comment]
This is not a bug, it is non-translated dynamic content. Notifying the board to correct the issue would have been the correct solution.
