### ISSUE TITLE
Registrations with ß fail to generate the username

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1238]
### Describe the bug

Registrations with ß fail to generate the username

### How to reproduce
Steps to reproduce the behaviour:
1. Create a new registration
2. Enter a lastname with the ß
3. Approve
4. See that the username field is still empty

### Expected behaviour

It should generate a username replacing the `ß` with `ss`

### Additional context

https://en.wikipedia.org/wiki/ß

**Comment by PeaceDucko** [comment]
Seems to be solved.

1. Create user with last name containing ß
2. Created test even
3. Added user to event both manually and using the admin panel
4. Username on public page shows ß, when hovering over it shows 'ss'
