### ISSUE TITLE
Move photos to S3 (fullres)

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1245]
### Is your feature request related to a problem? Please describe.
Currently there are 2 places where we store photos: the Paparazcie photo archive on a shared G Suite drive, and the low res photos on concrexit. This is inconvenient, as we want to keep those 2 in sync but that needs to be done manually, and because people need to ask the Paparazcie for fullres files.

### Describe the solution you'd like
As we are on AWS now, we could decide to move our photos to S3.

### Motivation
- One single place and interface for Thalia's photos
- Everyone can easily access fullres photos
- Less server crashes whenever anyone tries to download an album

### Describe alternatives you've considered
What we have now.

**Comment by joren485** [comment]
The one thing that is missing for me in this proposal is what happens to the Paparazcie photo archive if this change is implemented. Are you proposing that the Technicie will manage the fullres archive (through S3) and the Paparazcie does not have the fullres archive anymore?

**Comment by JobDoesburg** [comment]
> The one thing that is missing for me in this proposal is what happens to the Paparazcie photo archive if this change is implemented. Are you proposing that the Technicie will manage the fullres archive (through S3) and the Paparazcie does not have the fullres archive anymore?

Yes. Paparazcie doesn’t need the archive either. Whenever we want a fullres photo we can just download it from the website in fullres

**Comment by JobDoesburg** [comment]
Also relevant for a possible #203

**Comment by JobDoesburg** [comment]
https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

**Comment by JobDoesburg** [comment]
We're on S3 now! So now we could decide to not compress high res photos anymore and don't have the google drive folders anymore. Let's discuss this with paparazcie and board too

**Comment by JobDoesburg** [comment]
@DeD1rk

**Comment by DeD1rk** [comment]
I sent an email to paparazcie

**Comment by DeD1rk** [comment]
Paparazcie is fine with simply dropping fullres versions of existing photos. We can just start storing fullres of new photos starting ASAP. Then, we'll send out an email announcing the deprecation of the archive, and after that at some point the archive can simply be deleted.

**Comment by JobDoesburg** [comment]
> Paparazcie is fine with simply dropping fullres versions of existing photos. We can just start storing fullres of new photos starting ASAP. Then, we'll send out an email announcing the deprecation of the archive, and after that at some point the archive can simply be deleted.

I think dropping the current archive is a bad idea, because it might always come in handy at some point. Doesn't mean we should script something to put back the original versions for all existing albums, but let's not delete the originals. They can remain on the google drive for a while
