### ISSUE TITLE
create fixtures crashes on "django.db.utils.IntegrityError: UNIQUE constraint failed: activemembers_membergroup.name"

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1252]
### Describe the bug
When running `./manage.py createfixtures`, it crashes on the following error: `django.db.utils.IntegrityError: UNIQUE constraint failed: activemembers_membergroup.name`

### How to reproduce
Run `./manage.py createfixtures`

### Expected behaviour
Not crash

### Additional context
The reason this bug occurs, seems to be that after removing localization, we are using `member_group.name` instead of `name_en` in the database. However, this is not fixed in the `createfixtures` code.

**Comment by se-bastiaan** [comment]
This should be a result of https://github.com/svthalia/concrexit/pull/1216
