### ISSUE TITLE
Add a per user 'is allowed to use Thalia Pay' property

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1257]
### Is your feature request related to a problem? Please describe.
We decided we want to roll out Thalia Pay as a closed beta. Also, we want to blacklist people from using Thalia Pay, for example if they have too large debts or for any other reason. 

### Describe the solution you'd like
Every user gets a boolean property 'is allowed to use Thalia Pay'. Only if that is set to True, **and** he/she has a valid bank account, the `tpay_enabled` property (that exists already) will be True too. 

### Motivation
- This way we can roll out Thalia Pay as a closed beta first
- It is a easy kill switch for the board

### Additional context
In my opinion we should **also** keep the global Thalia Pay setting as an easy global kill switch

**Comment by se-bastiaan** [comment]
Maybe it would be good to negate the value? Otherwise you have to set the boolean to true for every single user.

Not that it is hard, but as blacklist it would make more sense I think

**Comment by JobDoesburg** [comment]
> Maybe it would be good to negate the value? Otherwise you have to set the boolean to true for every single user.
> 
> Not that it is hard, but as blacklist it would make more sense I think

Agreed
