### ISSUE TITLE
Add a simple incrementing reference number to Payment Batches

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1262]
### Is your feature request related to a problem? Please describe.
For bookkeeping purposes, it would be nice if payment Batches would have a simple incrementing reference number. That way, we can easily search for a batch and easily verify whether all batches are in the bookkeeping and vice versa. Currently, batches only display a non-unique description (which should stay!) and a unique but unpredictable UUID.  

### Describe the solution you'd like
Either:
- Don't use a UUID but just a regular auto-incremented PK
- Add a secondary auto-incremented unique reference number. Perhaps in the format of "TPAY-BATCH-20/21-001" or something like that.

### Motivation
It makes bookkeeping easy. 

### Describe alternatives you've considered
Registering this manually on paper

**Comment by se-bastiaan** [comment]
I don't think a batch necessarily needs a UUID as pk, so removing the custom field and altering the schema to use a regular AutoField has my preference.
