### ISSUE TITLE
Use pydocstyle to check documentation

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#1294]
### Describe the change
Add [`pydocstyle`](https://github.com/PyCQA/pydocstyle/) as a linter.

### Motivation
`pydocstyle` is a linter that checks the documentation of code according to [PEP 257](https://www.python.org/dev/peps/pep-0257/). This will improve the overall documentation, because developers are forced to write basic documentation (a tedious, but important part of development).

### Suggested implementation
Add `pydocstyle --match-dir='(?!migrations).*' website` to the linting GitHub Actions workflow.

### Additional context
We need two changes for this to happen.
First all of the existing code needs to be documented using PEP 257:
- [ ] activemembers
- [ ] announcements
- [ ] documents
- [ ] education
- [ ] events
- [ ] mailinglists
- [ ] members
- [ ] merchandise
- [ ] newsletters
- [ ] partners
- [ ] payments
- [ ] photos
- [ ] pizzas
- [ ] pushnotifications
- [ ] registrations
- [ ] singlepages
- [ ] thabloid
- [ ] thaliawebsite
- [ ] utils

And secondly, we need to add it to our CI.
- [ ] Add `pydocstyle` to GitHub Actions workflow

**Comment by se-bastiaan** [comment]
How does this match the docstring checking of pylint? (#1292)

**Comment by joren485** [comment]
`pylint` has a few checks on documentation (3 as far as I can tell, `missing-module-docstring`, `missing-class-docstring`, `missing-function-docstring`). `pydocstyle` has many more and does not only check for the existence of docstrings, but also whether their contents match with PEP 257.
