### ISSUE TITLE
More convenient way of selecting Album cover photo

### ISSUE THREAD

**Issue by mariesophiesimon** [svthalia/concrexit#1297]
### Is your feature request related to a problem? Please describe.
Right now it is only possible to select an album cover photo after uploading the whole album and then going back to select the file name, that should be the cover.

### Describe the solution you'd like
It would be nicer if it would be possible to choose the album cover already in the first step, so while uploading the photos.

### Motivation
Uploading albums nicer and quicker

### Describe alternatives you've considered
Not really any

### Additional context
None

**Comment by se-bastiaan** [comment]
I don't think this is possible, you don't have the files yet so you cannot choose a file.

**Comment by Tedddoo** [comment]
Is it maybe possible to add the album cover photo first (which automatically selects it) and then add all of the other photos? @se-bastiaan

**Comment by se-bastiaan** [comment]
You could technically do that. But that is really shitty when you just want to upload a ZIP and be done with it.

**Comment by Tedddoo** [comment]
What will we do with this issue then?
