### ISSUE TITLE
Use cached dependencies on GitHub actions

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1304]
### Describe the change
Use cached dependencies on GitHub actions

### Motivation
Decrease CI time

### Current implementation
We don't properly cache

### Suggested implementation
Properly cache

### Additional context
You could look at [https://github.com/GipHouse/Website/blob/master/.github/workflows/ci.yaml](https://github.com/GipHouse/Website/blob/master/.github/workflows/ci.yaml)

**Comment by se-bastiaan** [comment]
This will not really decrease the CI time, since our dependencies are contained inside the Docker image already.

**Comment by se-bastiaan** [comment]
Closing this since we do not need the caching due to our dependency docker image
