### ISSUE TITLE
Event information is not automatically filled in in newsletter

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/concrexit#1315]
### Describe the bug
When making the newsletter and selecting the events to show it doesn't automatically fill in all the information about an event when you select one.

### How to reproduce
Steps to reproduce the behaviour:
1. Make a new newsletter
2. Click on 'Add another newsletter event'
3. Select an event in the dropdown menu
4. See that it doesn't fill everything in automatically

### Expected behaviour
It fills in the information about the event automatically

### Screenshots
![image](https://user-images.githubusercontent.com/45050184/95777010-aa4a0380-0cc5-11eb-87a9-b7e2d388d79e.png)

**Comment by se-bastiaan** [comment]
The javascript that controls this form autofill can be found here: https://github.com/svthalia/concrexit/blob/master/website/newsletters/static/admin/newsletters/js/forms.js
