### ISSUE TITLE
API endpoints for slide models

### ISSUE THREAD

**Issue by KiOui** [svthalia/concrexit#1318]
### Is your feature request related to a problem? Please describe.
We want to build the website sliders in the app. For that we need to be able to get the website sliders from the API.

### Describe the solution you'd like
There should be an API feature such that the app is able to get the current website sliders.

**Comment by se-bastiaan** [comment]
Not necessarily really _easy_ but it should be doable looking at how it is done in other apps. For example the partner api, that one is also quite basic.
