### ISSUE TITLE
Cannot add Partner postal code of another country

### ISSUE THREAD

**Issue by megamichiel** [svthalia/concrexit#1348]
### Describe the bug
I felt like this was in between a feature request and bug, but decided to make it a bug report since this bugs me.
When adding/editing a Partner in the site administration, the company address only accepts valid postal codes from the Netherlands (1234AB). We have a new partner ([https://thalia.nu/career/partners/exellys/](https://thalia.nu/career/partners/exellys/)) that only has offices in Belgium and has a postal code of 2800, and the form rejects this, so I had to settle with 2800ME instead (it's in Mechelen). It would be nice if the postal code was less strict, which shouldn't cause too many issues, since the little Google Maps location already looks fine if I use the incorrect 2800ME but add the correct country to the city.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'Partners' in Site administration, and add/edit a partner.
2. Fill in required information, and set postal code to 2800 (or sth else). In this example, I set "City" to "Mechelen, Belgium".
3. Click any save button.
4. Input is rejected.

### Expected behaviour
I would hope for it to not reject the postal code.

### Screenshots
![image](https://user-images.githubusercontent.com/6312298/96731400-836f8980-13b7-11eb-9c7a-a20100e0b034.png)

**Comment by se-bastiaan** [comment]
Nice, I think we should just change the way these addresses are entered and mimick the way we do this for members since those fields support addresses all over Europe. Some corners were cut here (and we have not had foreign sponsors apparently)
