### ISSUE TITLE
Newsletter is not responsive

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#135]
In GitLab by lennartjansen on Feb 27, 2016, 21:36

### One-sentence description
When opening the Thalia newsletter via email on a narrow screen, the email clips at the right side. 

### Current behaviour
See capture below. While a scrollbar is being displayed at the bottom of the mail, you can't expect readers to scroll down and up again to read both parts of each sentence. 

![Capture](https://gitlab.science.ru.nl//thalia/concrexit/uploads/055b923e42161c0ee7846d9cd080e3b6/Capture.PNG)

### Expected behaviour
The width of the email scales with the width of the container in a responsive way. 

### Steps to reproduce

1. Open the Thalia newsletter in a mail client, or open the online version in a browser. 
2. Narrow the screen down. The scrollbar should appear at 744 pixels. Readability issues start at ~720 pixels.

---

Als je de view breder maakt, blijft de container mooi gecentreerd, maar als je view wat kleiner is, moet je horizontaal scrollen, wat flink irritant is.
De 'most-outer' container past zich wel aan, maar deze blijkt geen effect te hebben op de content-container.

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Feb 28, 2016, 01:53

Gaat dit over de nieuwsbrief? Die ziet er namelijk prima uit bij mij.. Misschien mailclient-specifiek?

**Comment by thaliawww-service** [comment]
In GitLab by mstiphout on Apr 7, 2016, 19:46

Idem, de mails werken prima op Gmail (Android) voor mij.

**Comment by thaliawww-service** [comment]
In GitLab by lennartjansen on Apr 7, 2016, 20:19

In de standaard mail-app op iOS krijg je gwn desktopformaat, en kun je dus inzoomen, zonder dat de verhoudingen veranderen (dus in principe als een statische afbeelding). Dit zou al sws mooier kunnen.
In Thunderbird (Ubuntu) is hetgeen in de issuebeschrijving staat aan de hand.

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Apr 8, 2016, 09:16

Hoe had je 't dan graag gewild? <s>Op het eerste gezicht kan ik geen mailtjes vinden die zich wel anders gedragen in Thunderbird. Als je een voorbeeld hebt is het wellicht nuttig om die door te sturen / screenshots te maken / die op de een of andere manier te delen.</s>

EDIT: Nevermind, ik geloof dat ik je verkeerd begreep. Inderdaad kunnen we gebruik maken van de dingen die bootstrap ons biedt om te zorgen dat 't in een leesbaar lettertype onder elkaar weergegeven wordt op een kleiner scherm.

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Oct 30, 2016, 17:10

Moved from thalia/website#418

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 25, 2017, 16:50

De vraag 'Gaat dit over de nieuwsbrief?' is niet beantwoord volgens mij. (at)lennartjansen?

Responsive e-mails zijn moeilijk. Het wordt nooit perfect. Gmail ondersteunt bijvoorbeeld geen media queries.

https://www.campaignmonitor.com/dev-resources/guides/mobile/

**Comment by thaliawww-service** [comment]
In GitLab by lennartjansen on Feb 25, 2017, 16:52

Ja, het betreft de nieuwsbrief. Dit had ik idd duidelijker moeten aangeven.

Media queries zijn wel een punt idd.

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Sep 11, 2019, 20:07

assigned to @pingiun

**Comment by pingiun** [comment]
We don't want to mess with css that has to work in all mail clients, because this is a notoriously hard problem. In other words #wontfix
