### ISSUE TITLE
Event descriptions can be very long in newsletter

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1354]
### Is your feature request related to a problem? Please describe.
Some events have a very long event description text. When those are added to a newsletter, it becomes a hell to read

### Describe the solution you'd like
Some ideas:

- automatically trim the event descriptions to the first _x_ words for the news letter and add a 'read more' button
- refactor events to have a 'event description' and an optional 'description excerpt'

It is not only a real problem for newsletters but also perhaps for the event page itself, because it can be quite messy. For example showing a 'read more' button or a dropdown with a bigger description would make things better organized.

### Motivation
Make sure the newsletter is better readable

**Comment by se-bastiaan** [comment]
So you want to fix the laziness of the secretary? The secretary is the one responsible for the newsletters, not us. Even though I do agree that some events have really long descriptions this should not be something _we_ need to fix.

**Comment by mark-boute** [comment]
I get that "voorkomen is beter dan genezen", but I also think that us fixing the issue would be better than ignoring the issue.

**Comment by JobDoesburg** [comment]
Closed by #2067
