### ISSUE TITLE
Add an optional from albums ForeignKey to events

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1363]
### Is your feature request related to a problem? Please describe.
Not really. But conceptually, it feels weird that our photo albums (which are almost always photos of an event) are not connected to those events. For me it feels like in some way it should be possible to have that connection.

### Describe the solution you'd like
Just an optional Foreign Key for Album to Event (I thought about a one to one field even I think that wouldn't work in some cases maybe)

### Motivation
Maybe in the future (our 7th lustrum maybe) someone would like to write a tool that does something fancy with photos taken at events. Or to send attendees a notification if photos are updated.

And it is really easy to add.

### Additional context
To populate our historical albums, we probably would want to write some script that matches events and albums semi-automated based on the date of both and possibly the name (it is no problem if this does require a little bit of guidance by the user for some cases, or if it is not perfect in all cases)

**Comment by se-bastiaan** [comment]
I like this idea
