### ISSUE TITLE
Event status messages per event

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1381]
### Describe the change
Events can show quite some status messages about being able or not being able to cancel, about fines, about possible 'other' ways of registering, etc. This has become quite messy in our codebase and still it does not always work ideally. I propose to move these fields to the event model and only provide some default texts that can be changed per event. We can then also add the event status message to the API and immediately have fixed it for the app as well

### Motivation
Some problems:

- we almost always forget that when we fix something about an event status message (about the fines or so), that we need to do the same update in the app
- for certain events, the standard status messages are a bit misleading because they just work differently, which results in additional text in the event description
- sometimes things just require a change, for example during this coronavirus times it turned out that a change to the default texts is desirable

### Current implementation
A lot of hardcoded messages

### Suggested implementation
Model fields for all the states an event registration can be in.

- unregistered & registration not open: "You cannot register yet"
- unregistered & registration possible: "Register now"
- unregistered & waiting list: "Put on waiting list"
- registered & before cancellation deadline & re-registration possible: "Cancel registration"
- registered & before cancellation deadline & re-registration not possible: "Cancel registration. Note that you cannot re-register afterwards anymore"
- registered & after cancellation deadline & re-registration possible: "You cannot cancel your registration without having to pay a fine of some amount."
- registered & after cancellation deadline & re-registration not possible: "You cannot cancel your registration without having to pay a fine of some amount. Note that you cannot re-register afterwards anymore."

etc. etc. etc. 

It does add a lot more information to our database, but I do think that in the end it is a nicer way of implementing these fields as the behavior of the system is more transparant and flexible. We move a lot of logic out of the views and into the model, which is something I like.

**Comment by se-bastiaan** [comment]
Please don't forget to add the correct label according to the issue template.

Moreover, this issue contains two proposals. Could you split them please?

**Comment by JobDoesburg** [comment]
> Please don't forget to add the correct label according to the issue template.
> 
> Moreover, this issue contains two proposals. Could you split them please?

I think they are very related so at least for now I think it is nice to keep them in one. Except if everyone agrees with my idea, then it becomes 2 issues indeed

**Comment by se-bastiaan** [comment]
Well I do agree that the message should be in the API, I think that one is fairly easy.

To be able to find the right solution for easily changing the messages I think that creating settings would be a better fit.
But that is a discussion that does not affect my opinion about the API.

**Comment by Tedddoo** [comment]
Is this still needed (since the other part of this issue is solved already), and it seems easy and fun enough for me. Is this correct? @se-bastiaan (I will just mention you since you nolife this github)

**Comment by se-bastiaan** [comment]
This is something that can definitely still be done.

**Comment by ColonelPhantom** [comment]
Should these be implemented as either services or the model returning a string?

I would also think that we could use a sum type/enum/class to represent this. I'm mostly thinking about how we can share the code between the description and CalendarJS.

**Comment by JobDoesburg** [comment]
I think I would do it at the model level: so create db fields for messages for all these cases, with default values that can be overwritten
