### ISSUE TITLE
Allow .svg files for slides

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1385]
### Is your feature request related to a problem? Please describe.
In high resolutions, banners don't always look nice, although I often create them as vector graphics so this shouldn't be a problem

### Describe the solution you'd like
Allow .svg files for the slides

### Motivation
Lower file size, better quality

### Describe alternatives you've considered
Use high resolution .png's (`@4x`) but that increase file size quite a bit and is not optimal

### Additional context
The Django image field does not allow .svg, maybe we can make a Django file field with a validator on image or .svg?

**Comment by se-bastiaan** [comment]
This would require validation of the SVG file, otherwise it could be a source of an XSS vulnerability I believe

**Comment by JobDoesburg** [comment]
> This would require validation of the SVG file, otherwise it could be a source of an XSS vulnerability I believe

I researched this for a bit, but if we put it in image tags it is not vulnerable according to [this blog post](https://digi.ninja/blog/svg_xss.php)
