### ISSUE TITLE
Thalia Pay at borrels

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1386]
With Thalia Pay being almost released, the next thing would be to also use it for buying beers and such at borrels.

### Possible solutions
I think the best way to do this is with some form of QR code. Members should scan the QR code with their favorite QR-scanner app and this will forward them to a site where they need to confirm (after logging in) their payment. A little brainstorm:

- Dynamic QR codes: every transaction requires a new QR code. This would result in a system where borrelcie members need to generate the QR code on their own device (not necessarily from concrexit, btw!), which will display the QR code on their screen and a member will then scan that code. The borrelcie member will see a confirmation on their own device after the payment has been accepted by the member. Possibly, we can also implement the 18+ check here!
    - pro: secure, nice to model
    - con: requires a device for borrelcie members, might be a bit of work in practice

- Static QR codes: every event / kind of payment will get a single QR code that users scan and confirm. The member then shows the payment-confirmation on their own device to the borrelcie.
    - pro: easy and simple
    - con: ugly, a little less secure (we could get payments of people not buying anything, which is not really bad but still)

There are different choices to make about for example, when to set the amount of beers someone orders. 

### What's next?
I think it would be nice to have a meeting with the borrelcie so they can think about their own preferred workflow, so we can consider that in further decisions. 

I could think of us building a separate system like borrel.thalia.nu that only functions as a borrel console, which uses concrexit for payments, but might be a bit overkill though as well.

**Comment by se-bastiaan** [comment]
Step one should be finding out if this is something that the Borrelcie and the board would want.

**Comment by JobDoesburg** [comment]
I have sent an email to CAD to ask them about their thoughts on this

**Comment by mark-boute** [comment]
We could also make the payer generate a dynamic QR which is then scanned as a payment, where the payer would select what they are paying for and the receiver confirms the selection.

As in:

1. Payer goes to a payment-page on the app/website

2. Payer selects what they are going to pay for

3. A QR code is generated on selection confirmation

4. Receiver scans QR

5. Receiver checks selection and confirms payment

-. Possibly change list and let payer confirm payment instead.

6. Payment is concluded, both devices get a confirmation

Pros:
- Both users have control of the payment and what needs to be paid
- We'd still know for which event the payment was made

Cons:
- Requires many steps
- Payer needs to go to a payment page

**Comment by Luca-Castelnuovo** [comment]
If the user has payed and is 18+ (if required) maybe show a green full screen, with a big date and a live time. Showing the bartender that the person has payed and is 18+.

**Comment by JobDoesburg** [comment]
Spoke with CAD. Conclusion:

- CAD is going to have some kind of borrel-console / ATM system (like izettle) where they select things people are going to order
- This will create a payment-url
- The member will scan a QR code of this payment-url and accept the payment
- Checkbox at the ATM

Extra thoughts
- Possibly we could also use push notifications instead of QR codes.
- Some checks should be performed by the server if a user wants to accept the payment (18+ check, is allowed to attend borrels)
- Probably we should also have the possibility to still have the cash / card payment where we just do not store the member that is buying anything.
- We should have a product list of things that can be ordered (think about craft beer borrels)
- This system does not need to be borrel-specific, could also be used at other events, or even for merchandise sales.

**Comment by JobDoesburg** [comment]
So basically we're going to have shifts/sessions. Those can be added to `events` but might also exist independently. Then we're going to have `orders` that contain a number of `products`, which are derived from a product list. The `orders` are `Payables`. We will need an extra `accept_payment` flow on top of `process_payment` (which is already used by Thalia Pay) that will not require a `payer` upfront, but will set it to anyone who accepts the payment.

**Comment by JobDoesburg** [comment]
Discussed with @lukovdm and we came to the conclusion that it is waaaay better to keep this in concrexit as a new app. Building a separate system for this would be yet another system to maintain. Also, using another system would require us to create some sort of anonymous payments in concrexit (and an API endpoint for it) because the current implementation requires a concrexit Payable. And we have problems with permission management etc. 

So a new app it is 🥳
