### ISSUE TITLE
Speed up the PaymentUserAdmin

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1397]
### Is your feature request related to a problem? Please describe.
The PaymentUserAdmin currently does a query for each and every user whether they are allowed to use Thalia Pay and calculate their Tpay balance. This is very very very slow.

### Describe the solution you'd like
We should improve the queries in some way that it is faster. It can all be done by the database so it must be possible. The problem is now that we do the same query many times for each user separately, while we should be able to somehow do this query immediately at once.

**Comment by JobDoesburg** [comment]
We could change the Thalia Pay balance to a read-only field and add a signal that does the recalculation when a payment is saved

**Comment by JobDoesburg** [comment]
Newest idea: write some `RawSQL` and use `django-queryable-properties` for it. I also did it in the `sales` app and although `RawSQL` should be avoided, it is feasible and probably better code than writing a full migration that defines a complete database view.

**Comment by JobDoesburg** [comment]
What was the whole reason we're using `PaymentUser`s over regular Members again, actually?

**Comment by se-bastiaan** [comment]
> 
> 
> What was the whole reason we're using `PaymentUser`s over regular Members again, actually?

I think it was to be able to show an overview with the current balances.
