### ISSUE TITLE
Setting payment to 'none' in events admin does not work

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1406]
### Describe the bug
Setting payment to 'none' in events admin does not work

### How to reproduce
Steps to reproduce the behaviour:
0. Make sure your user is superuser
1. Create an event with registrations
2. Register a payment for an event registration
3. Try to remove the payment again
4. You are not authorized!

### Expected behaviour
It should show an more informative error message

**Comment by JobDoesburg** [comment]
Cannot reproduce this specific error. It is true that you cannot remove payments when the `PAYMENT_CHANGE_WINDOW` has passed but that is intended behavior right?

**Comment by se-bastiaan** [comment]
Aaah I forgot we introduced that. But then we should clarify that in the error. I was so confused why the payment could not be changed anymore even though the event has not even been yet.
