### ISSUE TITLE
Creating a user does not work

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1408]
### Describe the bug
Creating a user does not work
### How to reproduce
Steps to reproduce the behaviour:
1. Go to the user admin
2. Click on 'Add user'

### Expected behaviour
I should be able to create a user

**Comment by 9Y0** [comment]
Duplicate of #1242, this is actually the third issue for this bug (#1329) 

I tried fixing it but I wasn't able to fix this one.

**Comment by se-bastiaan** [comment]
ah thanks I could find an issue
