### ISSUE TITLE
Add description to management commands

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#1414]
### Describe the change
Currently it can be unclear what some management commands do.

### Motivation
It would be nice if we could add these descriptions so it is more clear what our commands actually do.

### Suggested implementation

Add documentation and `--help` documentation

**Comment by se-bastiaan** [comment]
You're creating an issue about code that is not in master yet? Should this not be a comment on the NixOS PR?

**Comment by Legosteen11** [comment]
I originally thought it would be nice to add descriptions to the commands in manage.py so they could then also be added to the Nix config, but then I decided why not just add them to the Nix config directly. 

I'll change it back to "pls add this to manage.py".

**Comment by se-bastiaan** [comment]
So the answer to my questions is 'yes'?

**Comment by Legosteen11** [comment]
Update: the answer is no

**Comment by pingiun** [comment]
The thing about these descriptions in the PR was that the management commands do not contain descriptions or help texts themselves. It was my suggestion to create an issue as it was not really a problem in the PR, but in the management commands
