### ISSUE TITLE
Introduce API v2

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1428]
### Is your feature request related to a problem? Please describe.
Our current API code is hard to understand and maintain. 

1. We use Django Rest Framework for our API and every implementation we have uses [viewsets](https://www.django-rest-framework.org/api-guide/viewsets/). This is a way to tightly couple the different views and can work wonderful for the [easy cases](https://github.com/svthalia/concrexit/blob/master/website/activemembers/api/viewsets.py). But [in](https://github.com/svthalia/concrexit/blob/master/website/pizzas/api/viewsets.py#L51) [most](https://github.com/svthalia/concrexit/blob/master/website/members/api/viewsets.py#L41) [situations](https://github.com/svthalia/concrexit/blob/master/website/events/api/viewsets/events.py#L49) it only brings extra checks in our code to accommodate different situations. Especially in cases where there are permissions involved.
2. We used [Django token authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) but have now also authentication using OAuth 2. This last implementation should be a first-class citizen in our API but most of the APIs do not have scoping available. Moreover, they are not readable because the API code _expects_ a user.

### Describe the solution you'd like
To be able to solve this I'd like to introduce the Concrexit API v2. This PR is here for comments, what you think about this and maybe to make some design choices.

Thus:
1. The implementation of the API views should happen using [class-based views](https://www.django-rest-framework.org/tutorial/3-class-based-views/), just like most views in the (newer) apps. This is much more similar to the normal views and is thus easier to grasp if you have to write a view for both users (HTML) and applications (API). No more trying to understand viewsets to try to get them to do what you want. This PR contains an example of such APIs
2. Implement scopes and Django permissions for all views. No longer allow TokenAuthentication for the API. This is going to require a custom implementation that checks both the user permissions and the client scopes. A client logging in with client_credentials will get access as read-only anonymous.
3. Throttle requests based on the amount made per day because the API is basically public due to the awesome Swagger documentation (this also applies to API v1)
4. Pagination should always be enabled by default because some views are really slow now (i.e. https://thalia.nu/api/v1/photos/albums/)
5. It is probably smart to split the regular user APIs from the admin APIs. So for organisers that are changing the payments for events or pizzas for example, this will increase duplicated code but reduce API view and serializer complexity. The same endpoints are currently used for both normal users and for admin changes.

### Motivation
Easy and fun.

### Describe alternatives you've considered
Keep what we have.

### Additional context
I introduced this idea initially in #1403 so that I could show some example code.

**Comment by se-bastiaan** [comment]
How I am going to tackle this:

 - [ ] Move the current API packages to a new subpackage for `v1`
 - [ ] Move the calendarjs endpoints to their own subpackages and endpoints. These should not be part of the API.
 - [ ] Create a v2 endpoints for each package that currently has an API, possibly in two steps when admin APIs are required
 - [ ] Expose endpoints for things that have potential to be used via an API

**Comment by JobDoesburg** [comment]
- [ ] payments endpoint

We must think about the preferred way of letting admins create non-thalia-pay-payments via the API (like cash payments for event registrations). This could either be a functionality of the payments API (which would require extending payables with a permission check like `can_create_payment_for_payable(member)` that each payable must implement), or we could implement the functionality in each app's API separately (like v1 does). I have no real preference, both cases have their benefits

**Comment by se-bastiaan** [comment]
I am already implementing this with a permission check in #1673

**Comment by JobDoesburg** [comment]
> I am already implementing this with a permission check in #1673

yep I saw that

**Comment by JobDoesburg** [comment]
Increasing this priority as quite some things are blocked on this right now

**Comment by se-bastiaan** [comment]
HEEEY. I am doing 1 full API per week now hmm

**Comment by DeD1rk** [comment]
Reopening since the pizza admin has not been made.

**Comment by se-bastiaan** [comment]
Oh I thought I had done that already, whoops. Pretty sure I have a branch somewhere, just need to find where
