### ISSUE TITLE
Board member can't add event registrations

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/concrexit#1438]
### Describe the bug
I can't add or edit registrations for an event that I'm not organizing even though I should be able to as I have board permissions. It gives me 403 permission denied. 
I am able to change events themselves, I tried to edit a description and that worked.

### How to reproduce
Steps to reproduce the behaviour:
1. Give yourself the 'access event as if organizing' and make sure you are not superuser
2. Try to add registrations for an event that is not organized by you

### Expected behaviour
A board member should have 'access event as if organizing'.

**Comment by pingiun** [comment]
I think permissions of event editing and event registrations are seperated deliberately. I don't think this is a code issue, instead the board should just request permissions to edit event registrations

**Comment by Jorritboer** [comment]
How do we request that permission?

**Comment by pingiun** [comment]
Just write an email to www@
