### ISSUE TITLE
Allow benefactors to display study programme and cohort

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1447]
### Is your feature request related to a problem? Please describe.
Benefactors don't get to supply their study programma and starting year right now.

### Describe the solution you'd like
Allow them to.

### Motivation
This would make their profile pages more complete and pretty.

**Comment by se-bastiaan** [comment]
Adding the study programme would require values for every single study that we know. So we could add all beta associations and an 'other' value.

**Comment by pingiun** [comment]
Feature creep
