### ISSUE TITLE
Add link to WhatsApp promo group in member registration confirmation

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1470]
### Is your feature request related to a problem? Please describe.
Need a new way for promo

### Describe the solution you'd like
Add link to WhatsApp promo group in member registration confirmation

### Motivation
Reach new people this way easily.

**Comment by se-bastiaan** [comment]
We still need the group before this can be done.

**Comment by pingiun** [comment]
Did the board request this from you privately?

**Comment by se-bastiaan** [comment]
We discussed this idea during the CCM yesterday and thought it would be good that we would already have an issue for it.

**Comment by se-bastiaan** [comment]
@Tedddoo Maybe this one is nice to do next? You have some experience with tests now so this should be a breeze for you!
