### ISSUE TITLE
Check for breaking migrations

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#1473]
Add a check to the CI if breaking migrations have been pushed to a new branch. This would be useful to know for now, but is especially important if we want to add green/blue deployments.

Breaking migrations include:
- deletion
- adding a column with no default/nullable value to an existing table
- renaming a column
- more I haven't thought of

**Comment by Legosteen11** [comment]
[These are all the operations possible](https://docs.djangoproject.com/en/3.1/ref/migration-operations/) in Django migrations, of these the following seem breaking for sure:
- `DeleteModel()`
- `RenameModel()`
- `AlterModelTable()`
- `RemoveField()`
- `AlterField()`
- `RenameField()`

These may be breaking:
- `AddField()`
- `AddConstraint()`
- `AlterUniqueTogether()`
- `RunSQL()`
- `RunPython()`

**Comment by pingiun** [comment]
We can do downtime deployments and those are much easier for us, so we are not going to implement this
