### ISSUE TITLE
Automatically fill in event title and date after selecting event for a photo album

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/concrexit#1488]
### Is your feature request related to a problem? Please describe.
While solving #1363 I thought it'd be nice if the album's title and date were automatically filled in after selecting the event the albums are for. Just like adding an event to a newsletter.

### Describe the solution you'd like
When you select the event the photos are for it automatically fills in the fields title and date.

### Motivation
Saves 5 seconds to look up what the event was called exactly again and what date it was

**Comment by se-bastiaan** [comment]
You could change the album admin form:
- Make the name and date field conditionally required (aka optional when an event is selected)
- Auto fill the fields in the form when available

**Comment by Tedddoo** [comment]
Is there another example where, by selecting something, information is already filled in?

**Comment by se-bastiaan** [comment]
@Tedddoo The only example we have are the newsletters who have their own autofill admin.
