### ISSUE TITLE
Change mandate no. increment to guarantee uniqueness

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1508]
Consider https://github.com/svthalia/concrexit/blob/56ef628318d5bc4c4bbdc28a6eeac2d6c73cc218/website/payments/views.py#L44

In case an admin might manually remove a mandate (rather than invalidate it), manually change a user's mandate id, the newly generated mandate id might not always be unique. For example, if a user has mandate no. 1234-1 and 1234-3, the next number that will be generated is 1234-3 as well (because we take the `count() + 1`).

Solution: take the max mandate no. if it is of the form `<id>-<i>`, the new mandate no. will be `<id>-<i+1>`, else use the fallback we have already implemented. 

Other solution: do an additional check that the newly generated reference number is in fact really unique.

**Comment by JobDoesburg** [comment]
This issue occurred while discussing some problem with the bank with @ki-mberley

(Accidentally, the first batch was submitted at the bank as 'one time debits' while the mandate was actually a recurring debit. This cause some banks to disallow future debits with the same mandate reference, because they did not know that the actual mandate is a recurring mandate and thus consider the provided mandate no. as one-time and final. The quick solution was to let Kimberley increment the mandate no. for the affected users so the bank would consider them as 'new' again)

**Comment by se-bastiaan** [comment]
Nice catch, good that we did not open it up for everyone. That would have been such a mess.
