### ISSUE TITLE
Staging photos and media do not work

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1522]
### Describe the bug
Staging photos and media do not work

### How to reproduce
Steps to reproduce the behaviour:
1. Go to photos on the staging site.
2. I don't see any images loading on the page.
3. Please fix

### Expected behaviour
I see photos loading.

### Additional context
The images are saved, Wouter checked this.

**Comment by wdoeland** [comment]
It seems the SENDFILE_ROOT environment variable that is required in settings.py (https://github.com/svthalia/concrexit/blob/2faf3c15731850aecf31d8f3d6732a6967da73a4/website/thaliawebsite/settings.py#L209) is not set in the environment variables in configuration.nix
