### ISSUE TITLE
Dynamic link to promotion whatsapp group

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/concrexit#1528]
### Is your feature request related to a problem? Please describe.
The board is moving the whatsapp promotion to one group. Whatsapp groups have a maximum of 256 members so there should be multiple groups.

### Describe the solution you'd like
To avoid having to send new links when the old group is full we would like something like whatsapp.thalia.nu or thalia.nu/whatsapp that always links to the newest group. 

### Describe alternatives you've considered
The alternative is to deal with multiple links, ugh.

**Comment by pingiun** [comment]
A static link has been created at https://thalia.nu/whatsapp

Dynamic link functionality will be added later
