### ISSUE TITLE
Thalia Pay: Allow API access to Thalia Pay status of members

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1530]
### Is your feature request related to a problem? Please describe.
It is currently not possible to find out if a user is allowed to use Thalia Pay.

### Describe the solution you'd like
There needs to be a field in the payable object. So events and pizzas for example.

### Motivation
To be able to implement Thalia Pay in the app we really need this.

**Comment by JobDoesburg** [comment]
This is blocked by #1397 I think

**Comment by se-bastiaan** [comment]
Why exactly? It is just the tpay allowed value that is currently used to determine if you can actually use it in the website as well.

**Comment by JobDoesburg** [comment]
> Why exactly? It is just the tpay allowed value that is currently used to determine if you can actually use it in the website as well.

Hmm yeah okay you're right. I meant to say that with #1397 we are going to refactor the `PaymentUser` model once again from a proxy model to a real model. So that will change some things for the implementation

**Comment by JobDoesburg** [comment]
I think we should rebrand this issue `Payments in API v2`

**Comment by se-bastiaan** [comment]
That is part of #1403
