### ISSUE TITLE
Rename "pizza" to "is_pizza_event" in /events/ api

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1555]
In api/v1/events/ (idk about v2) there is a field named "pizza" that is called "is_pizza_event" in api/v1/events/{pk}/. The latter name is more clear, and it would be nice if the same field gets the same name across the requests that return them.

**Comment by se-bastiaan** [comment]
We cannot change this field in production since the previous app is still using it. Or, we can but it is not really proper to do so.

The value has already been named is_pizza_event on v2. Which you can see on https://staging.thalia.nu/api/docs.

So in my opinion this issue is already done
