### ISSUE TITLE
Add API v2 filters

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1598]
API v2 is missing some filters:

- [ ] `/api/v2/events/` should get optional '?start=<iso-date>` and `?end=<iso-date>` filters.
- [ ] `/api/v2/members/` might get filters on membership type and starting year.
- [ ] `/api/v2/events/:pk/registrations/` should get a filter on being registered.

I might add more to the list later on.

**Comment by se-bastiaan** [comment]
What do you mean exactly with filters on being registered for the event registrations? That API view only includes the registrations that are non-cancelled and non-pending, like the website also does. The length of the queue and the number of cancellations should not be exposed to all members imo.

**Comment by DeD1rk** [comment]
Ah that's perfect, in v1 the queue and cancelled registrations were included by default, but this is better

**Comment by se-bastiaan** [comment]
I'm merged this issue into #1428 btw. Think it is good to collect everything we need there.
