### ISSUE TITLE
Make Payable a protocol

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#1599]
### Describe the change
We might want to adopt the [mypy way of describing python protocols](https://mypy.readthedocs.io/en/stable/protocols.html). Right now we have something that looks like an [abstract base class for Payable](https://github.com/svthalia/concrexit/blob/5d47bff98b1fc5b1bf4ac080b084415b5dcc89f9/website/payments/models.py#L401), but isn't really.

### Motivation
Cleaner code

### Current implementation
Almost an abstract base class (ABC)

### Suggested implementation
https://mypy.readthedocs.io/en/stable/protocols.html

**Comment by se-bastiaan** [comment]
It is not an ABC because you cannot mix those with Django models. We found that out the hard way when we started implementing this.

The protocols seem to be quite similar to what we have already, if it is only for typing I am not sure it will improve anything.

**Comment by pingiun** [comment]
This doesn't seem needed
