### ISSUE TITLE
Newsletter CSS broken

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1624]
### Describe the bug
CSS vertical overflow in newsletter

### How to reproduce
Checkout the newsletter of 19 April in iPhone mail.app (1792 x 828 px)

### Expected behaviour
No overflow 

### Screenshots
![image](https://user-images.githubusercontent.com/7915741/115158947-0b95c980-a091-11eb-908e-07c78d82c2f8.png)

**Comment by se-bastiaan** [comment]
Welcome to HTML emails. Please add more information, we really need this to not break the email in other clients.

As you can see it works perfectly fine in the Gmail client, even though that is one of the easy ones. 
![Screenshot_20210419-101417.jpg](https://user-images.githubusercontent.com/1799914/115203976-4a129f00-a0f8-11eb-89c8-ab44da4d8114.jpg)

**Comment by JobDoesburg** [comment]
> As you can see it works perfectly fine in the Gmail client, even though that is one of the easy ones.

Well I wouldn't say 'perfect' (the blocks are overflowing at the right, but that's a different problem)

**Comment by JobDoesburg** [comment]
Nvm, I just reloaded the email and it works fine right now. Shitty email rendering as always

**Comment by se-bastiaan** [comment]
> > As you can see it works perfectly fine in the Gmail client, even though that is one of the easy ones.
> 
> Well I wouldn't say 'perfect' (the blocks are overflowing at the right, but that's a different problem) 

As perfect as it gets on mobile :p
