### ISSUE TITLE
Expose photo album slug in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1626]
### Motivation
Currently the only way to get an album from the api is using its `pk`. It would be nice 
if the new app can accept the `members/photos/:slug/` links as deep links, and share
the album using a link that both the website and app can open.

### Describe the solution you'd like
I think the best solution would be to either replace `api/v2/photos/albums/:pk/` with `api/v2/photos/albums/:slug/`,
or add it with a different path or prefix before the slug.

**Comment by se-bastiaan** [comment]
Hint: https://www.django-rest-framework.org/api-guide/generic-views/#attributes
