### ISSUE TITLE
Apple Tester account is visible on the members page

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#1637]
### Describe the bug
There is a member called "Apple Tester".

### How to reproduce
Steps to reproduce the behaviour:
1. The [members list](https://thalia.nu/members/directory/)
2. You will see the Apple Tester account on the first page on the 6th row in the 1st column.

You can also go to the the [Apple Tester member page](https://thalia.nu/members/profile/1622).

### Expected behaviour
Every visible member on the website is a human. No tests accounts on the production website.

**Comment by JobDoesburg** [comment]
Yeah I really hate this. @KiOui why do we exactly have that Apple Tester account, does Apple actually use it to test our app? Can't we have Apple use our staging environment? How does the app review process work exactly?

**Comment by JobDoesburg** [comment]
Otherwise I would suggest to not give the apple tester account a membership. We can then still keep the account, but it will not be shown as a member. And we should change the app so user that are no member can still log in

**Comment by se-bastiaan** [comment]
We have to have the account for apple to be able to approve the app when we release it.
And no, they cannot use the staging environment since we have to give them the actual release.

Technically you do not need a membership to be signed in to the app, but Apple needs to be able to properly review the app. Otherwise they will simply not approve it.

**Comment by JobDoesburg** [comment]
> Technically you do not need a membership to be signed in to the app, but Apple needs to be able to properly review the app. Otherwise they will simply not approve it.

I believe you, but I can hardly imagine that there is no alternative. This problem is so common with all kinds of apps for all kinds of organizations. It's also just a privacy violation. Do you guys think sending an email to Apple about this would work?

If there's really no alternative, I would propose to make some kind of 'functional account' for this purpose, so that still the account doesn't need a membership but can still be used.

**Comment by JobDoesburg** [comment]
I just googled around for a bit and found this: https://developer.apple.com/forums/thread/118914

> > I need to provide a test account to Apple
> Perhaps not. An alternative is to create a demo video, placed on the 'net where review can access - share the link w/review via that app's meta data notes.
> If app review needs more info, I'd expect them to make that request.
> A demo video has the added benefit where it can be repurposed as a Preview in the store.

Maybe it's worth to check this out

**Comment by pingiun** [comment]
I think the best idea is to have the apple tester account be on the staging site. This does require a modification to the app to make it so the staging site can be selected at the login screen.

**Comment by se-bastiaan** [comment]
I don't think they will just accept an option to change the server to staging. Would probably easier to hardcode a specific username to always set the server to staging.

Anyways, the initial idea was to just disable this account for when it was not needed. Still an easy option too.

**Comment by JobDoesburg** [comment]
> Would probably easier to hardcode a specific username to always set the server to staging.

I like this.

> Anyways, the initial idea was to just disable this account for when it was not needed. Still an easy option too.

Also fine by me

**Comment by pingiun** [comment]
> Anyways, the initial idea was to just disable this account for when it was not needed. Still an easy option too.

I just removed the Apple Tester membership and deactivated the account. When we release new versions of the app we will now need to remember to reactivate the account.

I think this solution is fine, so I will close this issue

**Comment by DeD1rk** [comment]
Google Play has started requiring that the have access to a review account at all times, so not just when we submit a new release for review. So I think we'll have to implement some alternative. I guess modifying the app to have a way to switch to staging would be most elegant, so I guess it should be an issue on Reaxit instead, but maybe an alternative here is also an option.

**Comment by DeD1rk** [comment]
I've implemented signing in to staging from the app, and created a review user there. I'll remove the production review user once the app has successfully passed review with that.
