### ISSUE TITLE
Search and filters for groups in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1640]
### Describe the solution you'd like
Search and filtering options for `api/v2/activemembers/groups/`.
I suggest a search parameter for `name`, and filter on `type` and perhaps `since` and `until` as is done for events, or at least some way to only get currently existing results.

### Motivation
This way users will be able to search for a group in the app, and for example show only the ones that currently exist, i.e. those that they might be able to join.

### Describe alternatives you've considered
Not doing it, but that would limit functionality of the app.

**Comment by se-bastiaan** [comment]
Can you please use the issue template?
