### ISSUE TITLE
Thabloid endpoint in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1641]
### Describe the solution you'd like
An API v2 endpoint for thabloids, possibly with some filters and ordering options.

### Motivation
I think it would be great if we can open the thabloids from the app. We'd need an endpoint for a list of thabloids.

### Describe alternatives you've considered
Not doing it. If we don't want it in the app, we don't need it in the api.

**Comment by se-bastiaan** [comment]
Can you please use the issue template?
