### ISSUE TITLE
Groups miss description in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1644]
### Describe the bug
The `description` field is missing in the `activemembers/groups` serializers. 

### How to reproduce
Look at swagger.

### Expected behaviour
An extra field for the description, at least in the detail endpoints.

### Additional context
Also something to double-check: groups have a field `display_members`. This is not included in the serializers, so are the members not shown if that field is true?

**Comment by se-bastiaan** [comment]
display_members should not be a problem since the API is not for public usage.
