### ISSUE TITLE
Merchandise in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1645]
### Describe the solution you'd like
`api/v2/merchandise/` giving a list of merch items. (The complete models, so a detailed version is not needed.)

### Motivation
This way we can show the merchandise in the app some day!

### Describe alternatives you've considered
Not doing it.

**Comment by JobDoesburg** [comment]
I think we shouldn't want to make the app an expensive and harder-to-maintain mobile website. In my opinion, the app should only offer functionalities that we can't build on the web (such as push notifications) or real core features that users use a lot (events & event registrations, pizzas, photos) and that we can build in a more user friendly way in the app then on the web. The latter of which I already doubt about a bit...

And apart from the app, I don't see any other application for merchandise to be in the API (it's read-only for everyone)
