### ISSUE TITLE
Minimise sales order data

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1653]
### Is your feature request related to a problem? Please describe.
The new `sales` app stores quite some member credentials that we don't need to keep for a long time

### Describe the solution you'd like
Anonymise the orders (setting the Member field to NULL) after a while (30 days? 1 year? directly when a shift closes)

Note that this also needs an update in the privacy statement!

### Motivation
Data minimization 

### Describe alternatives you've considered
Right now this will happen when a member object is deleted, but that takes too long in my opinion. There's no need to keep an order history in my opinion.

### Additional context
- We shouldn't delete the orders themselves, we want to keep them for multiple reasons
- This is no true data minimization, as orders will have payments, and those payments still have a user connected, but that's another issue.

**Comment by JobDoesburg** [comment]
Also see #880

**Comment by pingiun** [comment]
#1919
