### ISSUE TITLE
Copy product information to payable instead of using a foreign key

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1655]
### Is your feature request related to a problem? Please describe.
Right now, it is possible to change the description of an order even after it has been paid, by just changing the product. Only the price is stored separately and cannot be cascade-changed

### Describe the solution you'd like
When a `Product` is used in an order that is paid, the product should be immutable

### Motivation
Consistency of data

### Describe alternatives you've considered
Copying fields, that just creates more database columns that we don't really need

### Additional context
It should be fine to delete products (and then, the product can just be SET NULL)

**Comment by pingiun** [comment]
Copying the product information is better so that existing product information can still be renamed
