### ISSUE TITLE
Sales order payments are not always saved

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1675]
### Describe the bug
When paying for a Thalia pay order (via the sales payment view, so the QR code flow), the payment is not always stored back to the order. The payment is created properly, but after payment, the foreign key to the payment in the order is not saved. 

### How to reproduce
I am not sure exactly when this happens, at least it happens for the current shift 2 on the current staging environment. It might be because the shift has already been ended.

### Expected behaviour
Store the payment properly

### Additional context
Might be related to https://github.com/svthalia/concrexit/blob/6d0866022afb7fdf3edab34709d4d99e28039d59/website/sales/models/order.py#L123

**Comment by se-bastiaan** [comment]
Maybe you could add an example?

**Comment by JobDoesburg** [comment]
> Maybe you could add an example? I don't really understand why the ended shift would influence something in the payments app.

No the problem is not the payments app. The payment itself is created just fine. Only the order is saved to store the ForeignKey to the payment.

**Comment by se-bastiaan** [comment]
Well it uses the PaymentProcessView from the payments app right? And that is exactly the place where save is called on the payable object. https://github.com/svthalia/concrexit/blob/master/website/payments/views.py#L252

**Comment by JobDoesburg** [comment]
Yep, so I think something in the order is preventing the save. For example https://github.com/svthalia/concrexit/blob/6d0866022afb7fdf3edab34709d4d99e28039d59/website/sales/models/order.py#L123

**Comment by JobDoesburg** [comment]
Found the problem. Weird that we didn't have tests for this though...

@se-bastiaan do you think it would be a good thing to add a check for this in the payments app after saving the payable:

```python
        payable.refresh_from_db()
        if payable.payment is None:
            raise PaymentError("Something prevented this payment from being saved")
```

**Comment by se-bastiaan** [comment]
Wouldn't it be better to throw an error in the place that caused it from not being saved?
