### ISSUE TITLE
Sales API gives 400 when order items is null

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1692]
### Describe the bug
When sending `order_items: null` as to the sales API, this results in a 400

### How to reproduce
1. POST/PUT/PATCH an order with `order_items: null`. 
2. Profit

### Expected behaviour
Not crash and treat `null` as `[]`

**Comment by se-bastiaan** [comment]
I don't really believe this is a bug, this is proper typing. The API expects an array thus an array you should send.
