### ISSUE TITLE
Magenta text on light grey background in partner event

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1722]
### Describe the bug
There's ugly magenta text on light grey background in dark mode on partner events:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/41264528/121078217-f27be000-c7d8-11eb-84c1-ab70e1616a6e.png">

### How to reproduce
Look in the calendar at a partner event in dark mode.

### Expected behaviour
The text should probably be black, or the background really white or black.

**Comment by JobDoesburg** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-contrast()

**Comment by pingiun** [comment]
@DeD1rk is this still an issue?

**Comment by DeD1rk** [comment]
> @DeD1rk is this still an issue?

Yes
