### ISSUE TITLE
Send an email to the Educacie when there is a new document to approve

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#1725]
### Is your feature request related to a problem? Please describe.
Currently, the Educacie has to manually check if there are any documents (i.e. exams and summaries) to approve.  

### Describe the solution you'd like
Send the Educacie an email when there is a new document to approve.

### Motivation
As the committee needs to manually check, this only happens a few times a year. If a summary is submitted a few days before an exam and the committee checks after the exam week, students will not be able to access the summary in time.

### Describe alternatives you've considered
My first idea was to publish the files automatically and remove bad documents when they are checked. However, Isolde told me that a significant portion of the files is not approved, which means that this solution would result in a lot of poor quality/joke documents on the site.

### Additional context
I discussed this with Isolde and this is the solution that the Educacie prefers.

**Comment by se-bastiaan** [comment]
I like this idea, saw a few weeks ago that the documents were not checked for at least a year.
