### ISSUE TITLE
Cannot renew membership as benefactor, expects length field

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1740]
### Describe the bug
Right now, when trying to renew a membership as benefactor from http://localhost:8000/user/membership/ I can't send the form. I get a javascript error: `An invalid form control with name='length' is not focusable.` 
So the problem is that the length field is expected to have a value while this isn't the case for benefactors.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to http://localhost:8000/user/membership/
2. Add a benefactor membership renewal 
3. The form will not respond when trying to send
4. You will get a javascript error, indicating that the form can't focus on the length field (as it is hidden for benefactors), 

### Expected behaviour
It should ignore the length field for benefactorship renewals, as for benefactors it is always 1 year

**Comment by JobDoesburg** [comment]
I found the problem. website/registrations/views.py:241 hides the `year` choice in certain cases. The reason is that throughout the year, people can only upgrade their membership to a study membership.

However, the `year` choice needs to remain to allow people to renew their membership for benefactorship.  

I think it is best to just remove that filtering altogether. What do you think, @se-bastiaan

**Comment by se-bastiaan** [comment]
I am not sure there is another place where the 1-year renewal is checked. So adding it that functionality may result in unexpected results.

In any case, the benefactor option should also not be shown as long as you cannot renew for 1 year, since benefactor memberships can only be 1 year.
