### ISSUE TITLE
Script the release plan

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#1770]
### Describe the change
Make a script or an information file that states how a release should be done.

### Motivation
We forget that just undrafting the release on GitHub does not push the tag, and thus the GitHub action to make the release Docker doesn't run. Also the version number in `pyproject.toml` isn't changed. We could do all of these things automatically in a script, we could even undraft the release using the `gh` command line tool.

### Current implementation
We forget things

### Suggested implementation
All the information is available to the #concrexit owner to properly make a release.

### Additional context
This document or script could also include things like "tell the board that we just released"

**Comment by pingiun** [comment]
The part about using the github command line tool to undraft the draft release is not possible yet: https://github.com/cli/cli/issues/1997

**Comment by se-bastiaan** [comment]
We already have on here: https://github.com/svthalia/concrexit/wiki/release-procedure

But it has never been updated after we moved to GitHub.

**Comment by pingiun** [comment]
Yea the release process has changed a lot, and having it be more automated would be nice

**Comment by JobDoesburg** [comment]
Should also include

- Sending an email to the board
- Sending an email to committee chairs if the changes are of large influence to them
- Checking for new permissions that need to be granted to board or committees

**Comment by ColonelPhantom** [comment]
The releases are much simpler now, but there's still some outdated docs here and there, for example on the wiki: https://github.com/svthalia/concrexit/wiki/release-procedure

It'd be nice to have some clear and proper documentation or do-nothing-script about what needs to be done for a release (and what is done automatically).

**Comment by DeD1rk** [comment]
Closed in 83ccb9c
