### ISSUE TITLE
Don't send album notification if event is updated

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#1773]
### Describe the bug
After the `link_album_events_read` management command was executed, all of the album notifications were sent again.

### How to reproduce
Steps to reproduce the behaviour:
1. Have an album with unlinked event
2. Run `link_album_events_write` and `link_album_events_read` management commands
3. Album notifications are scheduled

### Expected behaviour
Album notifications aren't scheduled because the albums aren't new

### Screenshots
![image](https://user-images.githubusercontent.com/1576660/122955610-8a083380-d380-11eb-9940-14170a8e7956.png)

## Additional context
This seemed to have caused a couple of people to have uninstalled the app

**Comment by se-bastiaan** [comment]
This only happened unfortunately because the albums were so old that they never had a notification to begin with. So it is an unfortunate side effect, but since all new albums have a notification this will not happen anymore.
