### ISSUE TITLE
Food order can be changed after paying

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1783]
### Describe the bug
If you order a pizza and pay it, you can still change the product. If you change the product through the api, the payment is not removed.

### How to reproduce
Steps to reproduce the behaviour:
1. Order a pizza
2. Pay with Thalia Pay
3. Change the order through the api
4. Get an expensive pizza for little money

### Expected behaviour
Either changing the order after paying is impossible, or it removes the payment. I think removing the payment (as the website currently seems to do) would be strange, and for event registration we've decided not to enable this.

### Screenshots
<img width="569" alt="image" src="https://user-images.githubusercontent.com/41264528/123456318-01d59880-d5e3-11eb-86c8-9217e4720988.png">

There are probably no food events any time soon, so a hotfix may not be needed, though it might be good to double-check that similar stuff is not possible with registrations.

**Comment by JobDoesburg** [comment]
Did you try this on master? Because exactly this bug was fixed this tuesday when releasing

**Comment by JobDoesburg** [comment]
Nvm, I think it was only fixed in the web view not in the api

**Comment by DeD1rk** [comment]
>Did you try this on master? Because exactly this bug was fixed this tuesday when releasing

On staging, so that should be master
