### ISSUE TITLE
Add sales order API

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1785]
### Describe the solution you'd like
- An api endpoint `api/v2/sales/order/<uuid>/` that returns the order information that is shown on the website when you pay for the url from a qr code.
- It should be possible to pay the order through `api/v2/payments/sales/order/<uuid>`. This might already be possible, I haven't checked.

### Motivation
This way people will be able to pay from the app, instead of through the website where they may even need to log in. I think this is an obvious case where the ease of use of an app is very welcome.

**Comment by JobDoesburg** [comment]
> An api endpoint api/v2/sales/order/<uuid>/ that returns the order information that is shown on the website when you pay for the url from a qr code.

I don't think this needs to exist. The payable will contain a description of the order and thus contains all information a user needs

> It should be possible to pay the order through api/v2/payments/sales/order/<uuid>. This might already be possible, I haven't checked.

This already exists, it's the whole idea behind payments

> This way people will be able to pay from the app, instead of through the website where they may even need to log in.

They should still scan the QR code to identify themselves _at the counter_. The QR code will simply redirect them to the website. It is fine by me if they are redirected to the app to process the payment, but I don't want to introduce a flow of paying for orders

**Comment by DeD1rk** [comment]
> The payable will contain a description of the order and thus contains all information a user needs. (...) This already exists

If thats the case then indeed no new endpoint is needed. The code of the payment page suggested that paying for sales is more intricate than for other payables, but if it just works through the payments api that's fine.

> They should still scan the QR code to identify themselves at the counter. The QR code will simply redirect them to the website. It is fine by me if they are redirected to the app to process the payment

That is exactly the idea.

**Comment by JobDoesburg** [comment]
Well there is one extra thing, namely that the payer is also set after scanning the QR. This is not yet possible via the api.

**Comment by DeD1rk** [comment]
I guess this is possible now after #1787? I'll take a look if I can figure it out :)

**Comment by JobDoesburg** [comment]
I don't think it is possible yet actually. #1787 only gives access to order that are already yours, but _claiming_ an order that doesn't have a payer is not yet possible

**Comment by DeD1rk** [comment]
That seems right. Right now, `v2/sales/order/<uuid>` raises 403 for paid orders and when user orders are not allowed, and 404 if the user is not the payer. That makes sense for user orders, but doesn't let you claim orders. I'm not sure what would be the best way to make claiming possible:

- Allow (empty) PATCH on unclaimed `v2/sales/order/<uuid>` to set the payer. This adds some logic that's unrelated to user orders in the UserOrderSerializer, which sucks.
- Add a separate endpoint only for claiming (and viewing the order content) such as `v2/sales/order/<uuid>/pay`, analogous to the normal url with the same purpose. This adds an endpoint that is very similar to what exists, which sucks, but at least the endpoint is really simple and won't conflict with user order logic.

I think I'll try making a PR for the second option.

Besides, in OrderPaymentView: 
```python
if order.payer is not None and order.payer != request.member:
    messages.warning(request, _("This order is not yours."))
```
It does not check `created_by`, whereas the user order api allows both `payer` and `created_by` users to access, and sets both `payer` and `created_by` on creation. Then it's possible to later set `payer` to null (or any other user) through the user order API, after which someone else can pay for it. In general I think there are some limitations missing on what a user can change about user orders, and I'm not sure what the purpose is of having separate `created_by` and `payer`.

**Comment by JobDoesburg** [comment]
> I'm not sure what would be the best way to make claiming possible

I'm in favor of the first approach, as it is the most RESTful thing to do and leaves actual paying of the payable to the payments app and payments API. 



> I'm not sure what the purpose is of having separate created_by and payer

In the future, pizza orders will also go via this system. In that such cases, orders that are placed by the person itself have payer == created_by. Updating a payer field should only be possible if you are a shift manager.



> I think this line should be gone

No. If you remove the line, everyone trying to pay will only get the 'you successfully identified' message and be redirected to the index page, and they won't go to the page where they actually perform the payment.
