### ISSUE TITLE
Cannot cancel paid food order in API

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1806]
### Describe the bug
It is not possible to cancel a foodOrder paid with Thalia Pay with a DELETE request in API v2, but it is possible to first change it to a different product, which deletes the payment, and then cancel it when it is not paid.

### How to reproduce
Steps to reproduce the behaviour:
1. Order a pizza
2. Pay with TPay
3. Try to cancel through api v2
4. You can't
5. Change the order
6. Cancel the changed order
7. You can

### Expected behaviour
Cancelling a paid order should work the same as changing one.

**Comment by se-bastiaan** [comment]
I have tried this, but I cannot reproduce this behaviour. I can both cancel and edit my order.
Did you already add the payment to a batch or something like that?

**Comment by se-bastiaan** [comment]
Okay, adding it to a batch and processing that making deleting a 500 and disallows changing the order correctly. So I don't exactly know what you tried that gave this behaviour.

**Comment by se-bastiaan** [comment]
@DeD1rk

**Comment by DeD1rk** [comment]
Hmm yes it seems to work now, perhaps there was something to do with the payments caching
