### ISSUE TITLE
Charset content-type parameter in API responses

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1808]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when the API doesn't specify the charset it uses.

### Describe the solution you'd like
All API responses including their charset: `content-type: application/json; charset=utf-8`.

### Motivation
That way we don't have to hardcode the charset in applications that use the API.

**Comment by se-bastiaan** [comment]
Apparently, the charset is not set on purpose: https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py#L68. So I am not sure what to do here. The API is completely following specifications.

Maybe it is possible to solve this in the app by using some middleware?

**Comment by se-bastiaan** [comment]
More context: https://github.com/dart-lang/http/issues/175

**Comment by DeD1rk** [comment]
I see, interesting. I don't think there is any disadvantage in adding the charset anyway (since it is common practice), but I guess it would be quite a tough change. In the app I can simply decode everything before doing the json parsing, that is somewhat ugly and inefficient but not problematic.

**Comment by se-bastiaan** [comment]
It doesn't really look like common practice, more like something people really can't seem to agree on. Imo the dart HTTP client should decode this as utf-8.

The cleanest solution is probably writing from wrapper around the existing HTTP code and transform the json correctly.

**Comment by DeD1rk** [comment]
Agreed, I'll handle it in the app, and hope they find a real solution in dart/http sometime.
