### ISSUE TITLE
DeviceListView permission not checked

### ISSUE THREAD

**Issue by KiOui** [svthalia/concrexit#1809]
### Describe the bug
The `DeviceListView` of `api/v2` has a `IsAuthenticatedOwnerOrReadOnly` permission which is never checked as `get_object` is not used in the view.

### How to reproduce
Steps to reproduce the behaviour:
1. Set a breakpoint in the `IsAuthenticatedOwnerOrReadOnly` class
2. Enable the debugger
3. See that the `has_object_permission` method is not called on a request to the corresponding endpoint

**Comment by se-bastiaan** [comment]
Not really a problem, we simply don't need it :p
