### ISSUE TITLE
Add payment_type or full payment to event admin API

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1817]
### Motivation
`api/v2/admin/events/<eventPk>/registrations/` currently only gives the uuid of a payment, so to display in the admin screen how it was paid, the payment must be requested separately. Doing this for all of the registrations would be very inefficient (like 40 extra requests to load the event admin). If we simply add the payment_type or replace the payment uuid with a payment serializer, it will be much simpler.

**Comment by se-bastiaan** [comment]
Where are all the other sections from the template?
