### ISSUE TITLE
Use correct exceptions in sales API so JSON is returned instead of HTML on error

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1831]
### Describe the bug
When doing an API request that returns in a HTTP error (like 500), the API returns our default HTML error page.

### How to reproduce
1. Do a request that results in a 404, 403 or 500
2. You see HTML being returned

### Expected behaviour
I would expect to get a simple JSON response or empty body back

**Comment by DeD1rk** [comment]
Iirc this is only the case when you do the request from a browser. Still, it would make sense to see the same json response that you would get on a simple http client in the Django rest framework html wrapper that currently shows regular json results to browsers.

**Comment by JobDoesburg** [comment]
> Iirc this is only the case when you do the request from a browser

nope, this happens as well when doing the request with axios

<img width="780" alt="image" src="https://user-images.githubusercontent.com/7915741/126866752-11c32532-152b-46d5-91f0-85b1187ebc6f.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/7915741/126866755-bc1ed8c5-2673-4022-9a43-2745d6d0581d.png">

**Comment by se-bastiaan** [comment]
Do we raise this error ourselves? Maybe that it uses the wrong exception. There is a special one for the rest framework

**Comment by se-bastiaan** [comment]
A 500 error will always give an HTML response, we cannot handle it any other way. That response is the last resort.
For a 404 and 403 we should be able to return JSON, example is: https://staging.thalia.nu/api/v2/members/2000/

This issue really needs to be more specific, therefore I am taking the liberty to close it. If it gets updated with better examples where this goes wrong we can fix those situations.

**Comment by JobDoesburg** [comment]
Then

**Comment by se-bastiaan** [comment]
As far as I can see we are not raising any wrong exceptions. Th example you gave is a 500 and will always return HTML, don't really think we need a better response for that since it fails hard in any case.

**Comment by se-bastiaan** [comment]
Yes we could. But as I said: I don't think we need a better response for that situation. A 500 does not have more information even if you return JSON instead of HTML. It will stay 'server error' without more information.

**Comment by JobDoesburg** [comment]
Sure
