### ISSUE TITLE
Investigate why Thadmin creates such a high server load

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1847]
### Describe the bug
Investigate why Thalia Pay creates such a high server load

### How to reproduce
Today, 30-07-2021, was the first time Thadmin was actually used in practice at a borrel. This resulted in a extremely high server load, and we are not really sure why. 

### Expected behaviour
No high server load

### Screenshots
![image](https://user-images.githubusercontent.com/7915741/127578062-efde15c6-eb7b-4eba-a93a-5e2b98aa6559.png)

### Additional context
@svthalia/server has nginx logs

**Comment by se-bastiaan** [comment]
Maybe we can use https://artillery.io/ to test the performance?

**Comment by pingiun** [comment]
We have investigated this and have found the following:

8:53 PM Job Doesburg 
als een 404 ontvangen wordt door thadmin, reset thadmin
8:56 PM
thadmin interface product buttons worden niet gedisabled als een payer toegevoegd is
8:57 PM
het verwijderen van producten / orders kan resulteren in de situatie dat een order op de server niet bestaat met in thadmin wel (de catch 404's fixt dit)
(edited)
8:58 PM
Dirk Doesburg:flutter: 
change debouncing is per product: als je (snel) zowel bier als wijn toevoegt, wordt er eerst een request gestuurd met de aangepaste hoeveelheid bier, en  snel daarna met wijn. Vervolgens komt de response met bier aan, en reset de wijn teller totdat de wijn response aankomt
8:59 PM
Job Doesburg 
de automatische refresh van een order, en de push van een update lijken tegelijkertijd plaats te kunnen vinden
