### ISSUE TITLE
API filters for sales shifts

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1852]
### Is your feature request related to a problem? Please describe.
Thadmin should be able to query shifts in multiple ways. We should have filters for this

### Describe the solution you'd like
API filters

**Comment by JobDoesburg** [comment]
https://github.com/svthalia/thadmin/issues/78 Is also relevant

**Comment by se-bastiaan** [comment]
It would be nice to know what filters exactly, because I have no clue what filters we'd need

**Comment by JobDoesburg** [comment]
Sorry should have elaborated on this:

- filter on whether a shift is locked or not
- filter on whether a shift is active or not
- filter on start/end of a shift
