### ISSUE TITLE
Resolve some Django-doctor warnings

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1856]
### Describe the change
See attachment: Django-doctor has found quite some issues with our codebase. For #1855, we should either resolve those issues or ignore them explicitly

### Additional context
[django_doctor-concrexit.txt](https://github.com/svthalia/concrexit/files/6923881/django_doctor-concrexit.txt)

**Comment by pingiun** [comment]
This issue is redundant with #1855
