### ISSUE TITLE
Optional profile picture field during registration

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1857]
### Is your feature request related to a problem? Please describe.
Only few people actually have a profile picture on the website. It's nice to see faces of people to recognize them

### Describe the solution you'd like
Give people the opportunity to upload a photo during registration

### Motivation
This will likely result in more faces on the website

### Describe alternatives you've considered
Don't do this during registration, but rather redirect people on first login to the 'change profile' page and change the email text to explicitly ask them to upload a photo. 

### Additional context
If I remember correctly, @se-bastiaan came up with this idea

**Comment by se-bastiaan** [comment]
Thanks, forgot to open the issue

**Comment by JobDoesburg** [comment]
@se-bastiaan what do you think about the alternative remark?

**Comment by se-bastiaan** [comment]
> 
> 
> @se-bastiaan what do you think about the alternative remark?

sounds like something that people will ignore :p
