### ISSUE TITLE
Disabling optional registrations does not work

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1861]
### Describe the bug
I tried to disable optional registrations for an event, but somehow it didn’t work out

### How to reproduce
Have an event. 
Do not check ‘optional registrations allowed’
Profit

### Expected behaviour
Speaks for itself

**Comment by se-bastiaan** [comment]
This bug report really needs some more context. What event was it? Were registrations for that event enabled? Were the registrations already open?

I tried to reproduce the steps in this issue using https://staging.thalia.nu/admin/events/event/49/change/ and the only thing I found is that the checkbox was enabled for the event that had registrations enabled.

**Comment by se-bastiaan** [comment]
Have tried this again and really cannot reproduce.

**Comment by JobDoesburg** [comment]
Okay I just found that gmail decided to spam all GitHub notifications so I have some discussions to catch up :)

I experienced this problem with the orientation barbecue event that was cancelled. I was able to reproduce it right now with https://staging.thalia.nu/events/153/ and https://staging.thalia.nu/events/154/. Note that https://staging.thalia.nu/admin/events/event/153/change/ and https://staging.thalia.nu/admin/events/event/154/change/ show that optional registration is **not** enabled though the front end allows registration...

**Comment by JobDoesburg** [comment]
Not sure if relevant, but the `registration_start` `registration_end` `registration_cancel` and `max_participants` fields are all unset

**Comment by 9Y0** [comment]
Looks like we forgot to check if `optional_registrations` is actually enabled

https://github.com/svthalia/concrexit/blob/48933f4517073e126c7e5aa5640e5f132629a899/website/events/models/event.py
