### ISSUE TITLE
Remove automatic membership renewal field

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1883]
### Is your feature request related to a problem? Please describe.
Years ago, when the registrations app didn't exist yet and Thalia Pay really wasn't a thing, we had a checkbox for automatic membership renewal if people signed a mandate to automatically renew membership every year. 

We don't use it anymore. The mandates have all become invalid and with the registrations app and Thalia Pay people can arrange this themselves

https://github.com/svthalia/concrexit/blob/master/website/members/models/profile.py#L233
https://github.com/svthalia/concrexit/blob/master/website/members/templates/members/email/expiration_announcement.txt#L4

### Describe the solution you'd like
Remove the field from the profile, and change the email texts accordingly

### Motivation
Clean up the codebase

**Comment by se-bastiaan** [comment]
I am pretty sure we do not use the value any more, anywhere, at all. 

That was all removed when we introduced the registrations, only the field is left. Unless my search missed something :p

**Comment by JobDoesburg** [comment]
Yeah only the field exists that's all.

Regarding the emails, the membership expiration announcement says "The past year you've been a member or benificiary of Study Association Thalia.
You've not given us permission to prolong it automatically, thus your membership will
end on the 1st of September."

This implies that automatically prolonging is possible

**Comment by se-bastiaan** [comment]
Ah yes, I cannot remember but I think it maybe we planned to add that later. Hmm.

At least, what I know is that we needed to keep the values because seem people still were expecting automatic renewal. Especially teachers.

**Comment by JobDoesburg** [comment]
> At least, what I know is that we needed to keep the values because some people still were expecting automatic renewal. Especially teachers.


I think that with Thalia Pay for renewals this has changed

**Comment by se-bastiaan** [comment]
@Jorritboer
