### ISSUE TITLE
Deleted payment batches results in missing id's

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1884]
### Describe the bug
Payment batches can be deleted as long as they are not processed. However, this can result in missing id's which is very inconvenient.

### How to reproduce
1. Have a batch
2. Create a new batch
3. Delete the first one
4. The id's are not sequential anymore

### Expected behaviour
I think: not allow deleting batches if a batch with a higher ID exists

### Screenshots
![image](https://user-images.githubusercontent.com/7915741/130257380-81d75601-c6ed-40d2-8546-9e2aa41dd4bf.png)

**Comment by se-bastiaan** [comment]
Is this really a problem tho?

**Comment by JobDoesburg** [comment]
It makes it hard to check whether all batches are correctly processed in Thalia's bookkeeping. Normally this could simply be done by counting the "volgnummers"

**Comment by pingiun** [comment]
This does not actually break things
