### ISSUE TITLE
Move external events from partners to event package

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1892]
### Describe the change

This is a proposal to move the partner events from the partners package to the events package and rename them to external events.

### Motivation
1. They are events, and as such may fit better in the events package
2. The current partner events can be attached to partners, but that field is not used. Which makes them nothing more than models that link to external webpages
3. Moving them out of the partners package can allow us to use the functionality for other external events as well: the BBB, SNiC, something organised by Olympus etc.

### Current implementation
There is a PartnerEvent model in the partners package that has an unused foreign key to Partners. The API part is implemented using similar code that we use for the events. And the CalendarJS output uses a shared base serializer that is in the thaliawebsite package so that can properly be shared.

### Suggested implementation
Move the model and API serializers to the events package as `ExternalEvent` with the appropriate URL changes. Remove the foreign key to partners. And include the external events in places like the frontpage.

**Comment by pingiun** [comment]
This will need a migration
