### ISSUE TITLE
Add option to add email and phone number to non-member event registration 

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/concrexit#1898]
### Is your feature request related to a problem? Please describe.
When manually registering someone to an event that isn't a member, e.g. for the almanac event or an alumni event or the 'real life meeting of cohort 2020', it would be nice to be able to add their phone number and email address. Especially email address as often you already have that and this way you can still email all people registered for the event.

### Describe the solution you'd like
When manually registering someone to an event that isn't a member, add the optional fields email address and phone number.

### Motivation
So you can email all registered people to an event even when there are non-member registered. 

### Describe alternatives you've considered
Adding those email addresses manually when emailing.

**Comment by ColonelPhantom** [comment]
Sounds like a good idea; I'll take a look at this sometime soon
