### ISSUE TITLE
Create pizza orders in createfixtures

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#1900]
### Is your feature request related to a problem? Please describe.
Currently, the `createfixtures` command creates pizzas but no pizza orders.

### Describe the solution you'd like
Making `createfixtures` also create pizza orders.

### Motivation
This speeds up testing when developing some part of the website that is related to pizza orders.

**Comment by pingiun** [comment]
We're planning on removing the pizzas app so this will not need to be implemented
