### ISSUE TITLE
Clarify calendar colors

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#1908]
### Describe the bug
It's not always clear what the calendar colors mean for events.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to calendar
2. See half-transparent event
3. Confused about whether it's unpublished/closed for registrations/hidden

### Expected behaviour
Some kind of help text to remind you what the colors mean. Maybe a legend or text on the event block in the calendar.

### Screenshots
Current state (the first two events will open registrations soon):
![image](https://user-images.githubusercontent.com/1576660/132332512-eb98bfad-78d7-4f56-8c6c-0da7073dd4fa.png)

Example fix with text in the calendar block:

![image](https://user-images.githubusercontent.com/1576660/132349861-a2e99c20-a5c9-45f9-96d1-b41e9e60fc15.png)

**Comment by se-bastiaan** [comment]
Oh nice, I like that status text
