### ISSUE TITLE
Inactive partner page is still visible

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#1910]
When a partner is not set to be active, the page can still be loaded, while it should give a 404. See for example: https://thalia.nu/career/partners/exellys/, can be viewed, but it cannot be found on the https://thalia.nu/career/ page.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to specific partner settings and disable "Is active" checkbox
2. Go to partner page: the partner is not visible
3. Go to the specific partner page: the partner is visible

### Expected behaviour
The specific partner page should give a 404.

**Comment by se-bastiaan** [comment]
https://github.com/svthalia/concrexit/blob/master/website/partners/views.py#L26 needs filtering on is_active
