### ISSUE TITLE
Improve vacancy page lay-out

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#1937]
### Is your feature request related to a problem? Please describe.
We need a better lay-out for the vacancies.

### Describe the solution you'd like
I think it would be better if we displayed the vacancies in a simple list of items like this: 
```
[...partner image...] <title> 
<partner name> - <partner location> <optional tags> - <vacancy category>
<summary>
<learn more>
```

So for example:
```
[nedap.png] (junior) software engineer
Nedap - Groenlo - Young Professional
Nedap Light Controls realiseert duurzame verlichtingsoplossingen via zelf ontwikkelde hard- en software. Met ons product Luxon kunnen onze klanten hu…
Learn more


[infocaster.png] junior .NET (C#) ontwikkelaar
InfoCaster - Arnhem - .NET - Young Professional
Geef je carrière als developer een kickstart en werk samen met het .NET-team van Infocaster aan complexe vraagstukken voor klanten. Je realise…
Learn more
```

### Motivation
The vacancies page will be easier to read and more students will use the vacancies.

### Additional context
See #1845

**Comment by se-bastiaan** [comment]
Again: please use the issue template.
