### ISSUE TITLE
Event information does not load automatically when selected during the making of a newsletter

### ISSUE THREAD

**Issue by SnevelRetlaw** [svthalia/concrexit#1946]
### description of the bug
I am in the backend of the site creating a newsletter and I want to add an event to be displayed in full detail like it is on the website. When I select an event from the dropdown menu,  the information and details of the event should automatically load into the right places. But when I select an event now, only the event name wil appear, but not its description, URL, location, time and costs.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'newsletters' in the backend of the website
2. Click 'add newsletter'
3. Scroll down to 'add newsletter events'
4. Click 'add another newsletter event'
5. Select an event from the drop-down menu

### Expected behaviour
When an event is selected from the list of available events, all details, like description and time, of the event should load in automatically.

**Comment by se-bastiaan** [comment]
Adding to this that the agenda on the web version of the newsletter seems to be broken: https://thalia.nu/newsletters/310/
<img width="436" alt="Screenshot 2021-09-25 at 13 43 20" src="https://user-images.githubusercontent.com/1799914/134890875-faacb265-b034-4f44-a478-904f210515b6.png">

**Comment by se-bastiaan** [comment]
Seems that the agenda in the newsletter web version is broken too: https://thalia.nu/newsletters/310/
![Screenshot 2021-09-27 at 12 21 04](https://user-images.githubusercontent.com/1799914/134890980-ab613b35-da5d-47fe-86f9-6593ea8e0d53.png)
