### ISSUE TITLE
Show vacancies more prominently

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#1959]
### Is your feature request related to a problem? Please describe.
The vacancy page is not hard to find, but you do have to look for it. 

### Describe the solution you'd like
It would be nice if the vacancies had a bit more of a prominent place on the site so users don't need to search for it. There are multiple ways to do this, this is what I came up with:

- Show some vacancies at the bottom of the home page, under the upcoming events.
- Move the vacancies link in the navbar out of the career section and onto the main nav bar.

### Motivation
It is important that vacancies are seen by users.

### Describe alternatives you've considered
See #1845 

### Additional context
See #1845

**Comment by se-bastiaan** [comment]
I don't entirely see how this issue is different from #1845. There are still two options. So I would say this issue should become 'Show vacancies on homepage'
