### ISSUE TITLE
Registration message in calendar wrong

### ISSUE THREAD

**Issue by movieminer** [svthalia/concrexit#2008]
### Describe the bug
In the calendar, when you have to register for an event, it says in the block; You can register on .......
However, this seems to be the date of when the event will take place (or the registration deadline, can't tell for sure).
See screenshots for an example.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to the calendar and look for an event with a registration.
2. Look at the message in the calendar view
3. Compare with the registration date in the event itself.

### Expected behaviour
The message in the calendar view matches the date of when the registrations will open.

### Screenshots
![image](https://user-images.githubusercontent.com/12615607/139580635-4f56710d-23ae-4680-a45d-ace2376cfeb7.png)
![image](https://user-images.githubusercontent.com/12615607/139580729-88d92dcd-e60d-4d13-8505-107fc2b69b14.png)

**Comment by se-bastiaan** [comment]
Thanks for the elaborate issue! Looks like it is indeed using the registration deadline in the text.
