### ISSUE TITLE
Add statistics to vacancies

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#2012]
### Is your feature request related to a problem? Please describe.
Partners sometimes ask us for statistics on vacancies and it would be nice to see how many people actually view our vacancies.

### Describe the solution you'd like
It would be nice if we could see how many times the vacancy page is viewed and how many times a vacancy is visited.

### Motivation
It is important to know how often vacancies are viewed so we can see what is relevant for our students and whether we should promote the vacancies more.

### Describe alternatives you've considered
We could also see if there's some service where we can make tracking links.

### Additional context
I don't think we need to add a very big tracking suite to the site. Only some basic statistics are necessary.

**Comment by JobDoesburg** [comment]
The most basic version would be `grep`ing the server logs. My personal opinion is that you should do that first. We do not have so much vacancies (nor user interaction) that building something specifically for this purpose is worth the effort. If you just want to (incidentally) see "how many people are looking at the vacancies" and "do more people look at the vacancies if we put them on the front page" a grep of the nginx logs would suffice.

I think we should only bother about implementing this if this "feature" would really be used on a regular basis. I'm afraid that it will be a gimmick that nobody will look at anymore after your semi-annual report.
