### ISSUE TITLE
Update implementation of cryptography dependency when crates are built

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#2013]
### Describe the change

TODO: change https://github.com/svthalia/concrexit/blob/master/nix/concrexit.nix#L21 when https://github.com/nix-community/poetry2nix/issues/413 is fixed

### Current implementation
@svthalia/server Please elaborate.

### Suggested implementation
@svthalia/server Please elaborate.

### Additional context
When updating cryptography they added rust build requirements and thus our build started failing when we updated to 35.0.0

**Comment by pingiun** [comment]
> @svthalia/server Please elaborate.

I expect this issue to be solved in poetry2nix at some point in the future and at that point we can remove our override
