### ISSUE TITLE
Support for videos in photos package

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#203]
In GitLab by @thomwiggers on Dec 6, 2016, 20:13

### One-sentence description

Support for videos in photos package

### Desired behaviour

We should be able to save and serve videos inside photo albums

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Dec 7, 2016, 01:18

Hmm, er was ooit thalia/website#197

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 20, 2016, 15:24

We have videos from previous years in the Paparazcie archives, we should be able to show these too.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Sep 8, 2018, 16:37

New videos will be more common with the purchase of the new camera in July 2018. Thus I've increased the priority of this issue.

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Oct 23, 2019, 20:38

assigned to @lukovdm

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Oct 23, 2019, 20:38

unassigned @lukovdm

**Comment by pingiun** [comment]
We don't want to do this
