### ISSUE TITLE
Use django admindocs instead of docs.technicie.nl

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2060]
### Describe the change
Django apparently supports admindocs (https://docs.djangoproject.com/en/3.2/ref/contrib/admin/admindocs/), whichs works kinda awesome! I think we can remove all the .rst documentation that is hosted on docs.technicie.nl and include it in the django admindocs 

### Motivation
The .rst documentation is hardly ever updated because people don't like writing docs. By adding the docs to the source code, all documentation is centralized

### Current implementation
We both have pydoc and separate .rst documentation files. 

### Suggested implementation
Move all the documentation in the .rst files to pydoc. Then remove docs.technicie.nl and all related code.

### Additional context
I tried this for https://github.com/KiOui/TOSTI : 
![afbeelding](https://user-images.githubusercontent.com/7915741/145052444-307b8e2c-8a0f-449d-bee6-7e3122cc1d6c.png)
![afbeelding](https://user-images.githubusercontent.com/7915741/145052468-566e872b-d53b-4fd8-8dab-e4af6d88607b.png)
![afbeelding](https://user-images.githubusercontent.com/7915741/145052487-5033dc11-36f1-495c-a41d-a1a2b6c8760d.png)
![afbeelding](https://user-images.githubusercontent.com/7915741/145052503-258d5146-40a6-4e03-82ca-562db29ea6c7.png)

**Comment by se-bastiaan** [comment]
> The .rst documentation is hardly ever updated because people don't like writing docs.

What .rst documentation are you referring to? The files in the docs folder are for sphinx [automodules](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). All the actual documentation is in docstrings already.

**Comment by se-bastiaan** [comment]
Oh now that I think about it, can these docs include other documents as well? Like here: https://thalia-documentation.s3.amazonaws.com/master/registrations.html

**Comment by pingiun** [comment]
We don't want this in the admin site
