### ISSUE TITLE
General meeting documents are not private

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#2084]
### Describe the bug
The documents that were discussed during a general meeting are publicly available. This behaviour is inconsistent, because the minutes, policy documents and annual reports are private and require authentication.

For example, you need to authenticate to download the minutes of the general meeting of 16-06-2021 (document 483). But you do not need to authenticate to download the file "Minutes 16-06-2021" (document 481) that is part of the set of documents that was discussed during the general meeting of 13-10-2021.

### How to reproduce
1. Go to the [documents page](https://thalia.nu/association/documents/).
2. Copy the download link of the minutes of the general meeting of 16-06-2021 (the pink "MINUTES" button) into a private browsing session.
3. Observe that you are redirected to a login page.
4. Copy the download link of the second document that was discussed during the general meeting of 13-10-2021 (called "Minutes 16-06-2021") into a private browsing session.
5. Observe that you download the file.

### Expected behaviour
All documents under the header "annual documents" require authentication.

**Comment by joren485** [comment]
This also means that Google is indexing these documents. For example:

![2021-12-15_21-51-22](https://user-images.githubusercontent.com/7031489/146263192-373041fd-cc8c-4edd-81a0-d99557d4ae02.png)

**Comment by se-bastiaan** [comment]
thanks for opening the issue about this!

**Comment by se-bastiaan** [comment]
![image](https://user-images.githubusercontent.com/1799914/146412953-5598dd9f-867e-4a7b-87a7-4c94793877e2.png)
![image](https://user-images.githubusercontent.com/1799914/146412978-1d1bd6ab-4d97-46a3-9511-0a6a90ac47eb.png)

@SnevelRetlaw You've uploaded documents and not marked them as 'member only'. Can you please fix this?

**Comment by SnevelRetlaw** [comment]
Thanks for notifying me, it should be fixed now. Please let me know if that is not the case.

**Comment by joren485** [comment]
It still seems to be the case for the files of the GM of 22-09-2020. Other than that it seems to be fixed (with a quick sample from some random GMs).

**Comment by SnevelRetlaw** [comment]
Thank you for checking! I changed the files to be member only. I also did not find any other documents with a quick sample from other GMs.

**Comment by joren485** [comment]
Great! I guess this can be closed now?

Two ideas on how to prevent this, that you might want to think about:
1. Make GM files private by default, with the possibility of being made public manually.
2. Make GM files always private. I don't see a situation in which non-members should be able to access GM files via a link.
