### ISSUE TITLE
Date format for events

### ISSUE THREAD

**Issue by mark-boute** [svthalia/concrexit#2087]
### Describe the change
Change the date format for events from { MMM. DD, YYYY, H A } (see additional context)
to { EEE, DD - MMMM - YYYY, HH:MM }.

### Motivation
The current dateformat is following the US style, according to the spelling in the styleguide we use British English (Colour), and we are EU based.
So the date format should also follow the British English date format (a.m./p.m. is mostly used in the US, Australia and Canada), throughout Europe 24-hour notation is used.

### Additional context
Current: ![image](https://user-images.githubusercontent.com/33718602/146271152-5853aac7-cf7f-4458-afcc-3c9315e9bb75.png)

**Comment by DeD1rk** [comment]
Something to keep consider is that the newsletter uses 24-hour notation and 3-character abbreviations:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/41264528/149205190-0c1171a8-f6ee-4ff1-8cad-423ac050e7fc.png">
