### ISSUE TITLE
Payment amount seems to have max value of 99.99

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2091]
### Describe the change
https://github.com/svthalia/concrexit/pull/2086#issuecomment-995261018 suggests that on production database systems, the maximum value for payment amount is 99.99... This is intended to be 9999.99, though... This should be verified and possibly fixed

### Motivation
99.99 is high, but not uncommonly high for payments

### Current implementation
We use DecimalFields with 6 digits and 2 decimals. But apparently that does not work properly?

### Suggested implementation
- Verify existence of the issue
- Perhaps, subclass DecimalField ourselves to some payment amount field, that auto-sets the number of digits and decimals.

**Comment by se-bastiaan** [comment]
@JobDoesburg Bit higher prio for this wouldn't be weird imo.

**Comment by JobDoesburg** [comment]
I just verified the existence of this issue. Not only do payments of above €100 not `clean()`, they result in an internal server error...
