### ISSUE TITLE
Manage thalia.nu in terraform

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#2119]
For the deploy of production we used the existing route53 thalia.nu record. It's better to manage this in terraform as well

**Comment by se-bastiaan** [comment]
Are we sure about doing this? It is possible to use an existing record for it, and not give terraform the permission to edit the DNS zone. Aka if an AWS key used for Terraform leaks we may have a problem.

**Comment by pingiun** [comment]
We already give terraform permission to use the dns zone for staging, or do you want to remove that as well?

**Comment by pingiun** [comment]
I’m not sure about that, I don’t know enough about IAM

**Comment by pingiun** [comment]
Let's close this because it's fine to change the record manually
