### ISSUE TITLE
Upgrade to bootstrap5

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2139]
### Describe the change
[As django-bootstrap4 seems to go unsupported](https://github.com/svthalia/concrexit/pull/2059#issuecomment-1001773582), and bootstrap 5 is more lightweight, we should upgrade to bootstrap 5.

### Motivation
Bootstrap 5 is more lightweight and more than bootstrap 4.

### Current implementation
Bootstrap 4

### Suggested implementation
django-bootstrap5

**Comment by se-bastiaan** [comment]
This looks doable I think https://getbootstrap.com/docs/5.0/migration/

**Comment by JobDoesburg** [comment]
> This looks doable I think https://getbootstrap.com/docs/5.0/migration/

The most nasty thing is that left and right have been replaced for start and end

**Comment by se-bastiaan** [comment]
Lucky for us that we didn't use those that much
https://github.com/svthalia/concrexit/search?l=HTML&q=left
https://github.com/svthalia/concrexit/search?l=HTML&q=right
