### ISSUE TITLE
Add social security page or section to the site

### ISSUE THREAD

**Issue by SnevelRetlaw** [svthalia/concrexit#2143]
### Is your feature request related to a problem? Please describe.

Because of the new Trust Contact Person project, we have to add some kind of social security page or section to our site, which students can easily find. A trust contact person is a computing science student that can help other students in finding the right help for them because that might sometimes be difficult to find or determine. The idea for now is that there are 2 of such Trust Contact Persons that will stay a Trust Contact Person for 2 years. They will not be replaced at the same time, but rather alternating per year, so that every year there is someone who already has experience with this and someone that is new. This means that it has to be changed once every year if everything goes as planned. Besides information about the trust contact person, we also want the other services of the radboud to be there, so students can easily find them.

### Describe the solution you'd like

We suggest to make a separate new page which contains:

- contact information of the Trust Contact Person. Note that every computing science student, not only Thalia members, must be able to contact this Trust Contact Person, because of that we suggest the following structure:
	* for non-members an email-address (and maybe a picture) would suffice
	* for members we can decide to also include mobile numbers if the Trust Contact Person approves
- links and/or contact information to all services the university offers (https://www.ru.nl/currentstudents/during-your-studies/overview-counsellors-advisors/student-support/). It is probably best to add a short description for every service so students have an idea what these persons are for. We can look for example at the sites of Marie-Curie (https://marie-curie.nl/page/show/93), Synergy (https://www.synergy.nu/en/members/mental-health)or Mycelium (https://mycelium.nu/studentbegeleiders/) for inspiration. 

We can add this for example as a drop-down menu at contact, or add a completely new section.

### Motivation
-

### Describe alternatives you've considered
-

### Additional context
-

**Comment by se-bastiaan** [comment]
I feel like you used the issue template but remove the titles?

What is a trust person contact person project tho? Vertrouwenspersoon?

**Comment by JobDoesburg** [comment]
We discussed this with @SnevelRetlaw and decided to make it a static html page (at least for now). We can always make it into a real app with a backend if we want
<img width="560" alt="image" src="https://user-images.githubusercontent.com/7915741/149216829-75501fc2-8b30-4976-8a8a-16c904ea460b.png">

**Comment by JobDoesburg** [comment]
The board will send us the exact details
