### ISSUE TITLE
Automatically add newsletter events for events in the upcoming week

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2162]
### Is your feature request related to a problem? Please describe.
It takes quite a while to manually select all events for next week in the newsletter. This can be automized

### Describe the solution you'd like
Either javascript or an admin action that automatically adds newsletter event objects.

**Comment by se-bastiaan** [comment]
I think that extra context here is: the event items. So the inlines, not the agenda at the top.
