### ISSUE TITLE
Vacancies in the newsletter

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2165]
### Is your feature request related to a problem? Please describe.
Vacancies in the newsletter 

### Describe the solution you'd like
Add a section in the end of the newsletter with some selected vacancies (to be selected by the person drafting the newsletter)

### Motivation
Better promote vacancies

**Comment by pingiun** [comment]
If the extern/secretary want this (do we know this?), they can copy paste the vacancy in a regular newsletter text field
