### ISSUE TITLE
Profile picture url returns 403

### ISSUE THREAD

**Issue by joren485** [svthalia/concrexit#2175]
### Describe the bug
The [url to my profile picture](https://thalia.nu/media/public/avatars/IMG_2702.JPG) returns a 403.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to my [public profile](https://thalia.nu/members/profile/1239).
2. Notice that the image does not load.

### Expected behaviour
Profile pictures are publicly available.

### Additional Context
* I didn't find any other profiles with this problem.
* The [smaller version of the profile picture](https://thalia.nu/media/public/thumbnails/600x600_1/avatars/IMG_2702.JPG) (used in the members list) does not seem to be affected.

**Comment by se-bastiaan** [comment]
Might be possible that our move to NixOS caused this? @svthalia/server

**Comment by pingiun** [comment]
There were some images in `/volume/concrexit_media/data/media/public/avatars/` that weren't world readable, which means nginx couldn't read them. I ran `sudo chmod +r /volume/concrexit_media/data/media/public/avatars/*` to fix this
