### ISSUE TITLE
Visual quirk in the login failure message

### ISSUE THREAD

**Issue by W-M-T** [svthalia/concrexit#2188]
### Describe the bug
When you fail to log in on desktop (or probably any wider screen) the message saying this shows up on the left and the login fields are offset to the right. I would expect the message to appear on top, while the login fields were to stay in the same horizontal position.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to the login page
2. Enter invalid credentials

### Expected behaviour
The login fields do not move to the right. The error message is either shown above the login fields or next to them.

### Screenshots
![Screenshot from 2022-01-27 16-20-21](https://user-images.githubusercontent.com/12382856/151389280-ed564ad7-e792-41a4-98fc-713a14cbce83.png)

### Additional context
Not sure in what other situations these message boxes are used, but it may occur in other places too. Haven't checked.

**Comment by se-bastiaan** [comment]
![Screenshot 2022-01-27 at 17 03 40](https://user-images.githubusercontent.com/1799914/151396537-79bcc117-435f-4b4e-98e8-f808d1e9f03d.png)

This does no longer happen on staging, however there we can see that the close button has a double X and it doesn't work.
