### ISSUE TITLE
Digitpaint vacancy returns a 404

### ISSUE THREAD

**Issue by stefanvi** [svthalia/concrexit#2200]
### Describe the bug
When clicking 'learn more' on the Digitpaint vacancy card the server returns a 404.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'Vacancies'
2. Scroll down to the Digitpaint card
3. Click 'learn more'

### Expected behaviour
Be shown a page with more information about Digitpaint.

### Additional context
Their logo also has some white pixels around the black text that does not work well with a dark background.

**Comment by se-bastiaan** [comment]
The expected behaviour is actually that we scroll down to the bottom of the page to open the vacancy that is located there. Digitpaint has no partner page with information.

**Comment by stefanvi** [comment]
Right, that makes sense.

**Comment by stefanvi** [comment]
Ordina seems to have the same issue and others, like GX software don't go anywhere.

**Comment by ColonelPhantom** [comment]
My findings so far:
- It seems like the partners that give 404's are not active. So should their vacancies not also be inactive?
- Scrolling within the page should happen (like @se-bastiaan mentioned), but that does not seem to happen, although I don't know why.

**Comment by ColonelPhantom** [comment]
Apparently this is a duplicate of #2039 at least for the 404.
