### ISSUE TITLE
Remove padding from event description text (at least on mobile)

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2212]
### Describe the bug
![855635BB-A85A-48BD-BBBB-5063561F7E5E](https://user-images.githubusercontent.com/7915741/153772135-16382ecb-1330-4e86-8a4d-1b1a50fcb8bc.png)

This pretty much says it all

### How to reproduce
Any event page

### Expected behaviour
no padding over the x axis

**Comment by se-bastiaan** [comment]
I noticed this as well last week on desktop. Probably needs a `py` class for the spacing instead of whatever it is now.
