### ISSUE TITLE
Event list loading indicator

### ISSUE THREAD

**Issue by rowan-vr** [svthalia/concrexit#2223]
### Is your feature request related to a problem? Please describe.
The event list page doesn't show a loading icon when loading, instead, it says there are no events which is confusing

### Describe the solution you'd like
Change the blue box that tells us there are no events to a loading indicator when the events are loading
![](https://cdn.discordapp.com/attachments/545558263408885770/943584810138497105/es4dr6ft7gy8huoij.gif)

### Motivation
The current information displayed whilst loading is incorrect and unclear, if you quickly want to look at the page you might think there're no events but they just aren't loaded yet.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by se-bastiaan** [comment]
I am very much confused how to reproduce this. The data always loads instantly for me.

**Comment by ColonelPhantom** [comment]
Yeah, it loads quite quickly on production. Might still be a nice enhancement, but not really needed.

**Comment by JobDoesburg** [comment]
I do experience this. Priority is low but it's also easy to add
