### ISSUE TITLE
Create narrow container page base template

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2227]
### Describe the change
Some pages still mix wide page and narrow page layout:

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/7915741/154339942-790ffcf0-6b92-47c6-ac9b-1c220e02d9fb.png">

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/7915741/154340275-0e13f72c-1ea0-4bb3-970a-20cb0c850f72.png">

This should be fixed, preferably by adding 2 distinct base templates to extend.

### Motivation
Easier templates

### Current implementation
Every template does this same styling over and over again

### Suggested implementation
have 2 base templates to extend

**Comment by se-bastiaan** [comment]
I think it would also help if we implemented the title differently. It is now a border on the h1. Kinda related I guess
