### ISSUE TITLE
Change the size and positions of the tiles on the well-being page

### ISSUE THREAD

**Issue by SnevelRetlaw** [svthalia/concrexit#2258]
### Is your feature request related to a problem? Please describe.
As a result of some discussion, we feel like the univesity service and our trust contact persons are as equally important. This means we want the tiles on the web-page to be on the same level and of the same size

### Describe the solution you'd like
A good solution would for example be to make the page have 2 columns: one for the services from the university and one for our TCPs. Then you can add the text that belongs to the tiles at the top of the column.

### Motivation
This way, both services from TCP and university are as accessible as possible.

### Describe alternatives you've considered
A possibility is to reduce the amounts of tiles of university services. I personally think that a link to the student advisors and STIP are the most important. This way the webpage won't be too assymetrical. I do think it is a good idea to keep the link to the general student well-being page on the bottom of the page.

### Additional context
I currently do not have an example lay-out, sorry!

**Comment by JobDoesburg** [comment]
@SnevelRetlaw could you perhaps make a drawing of the layout you envision? And also think about what this would look like on mobile

**Comment by Pokemaster69** [comment]
I have looked at it, but in my (maybe unpopular) opinion this is not a big problem, however if given a good example of the envisioned layout this can be implemented

**Comment by SnevelRetlaw** [comment]
Sorry for taking so long, but I made a draft of what it should approximately look like. If you have any questions, please let me know.


![Slide1](https://user-images.githubusercontent.com/65032271/170503206-9209ecc5-81f4-4f3e-808e-f12097ee308a.JPG)

**Comment by SnevelRetlaw** [comment]
Then for the mobile site, you can move the trust contact persons below "services from the university", but above "general student support website from the university".

**Comment by NienkeWessel** [comment]
Hey Walter,
Something like this?

![wellbeingpagelargescreen](https://user-images.githubusercontent.com/36206600/200941974-4bbd1982-8b69-4e14-8c19-b79a3d0b28b8.png)
![wellbeingpagesmallscreen](https://user-images.githubusercontent.com/36206600/200941969-8226879f-0cbb-492c-b627-cacc4d20196c.png)

Please let me know if I should move anything around. I have now put the trust contact persons on the right because then they automatically move below the university stuff for smaller screens. If it is really important to have them on the left in larger screens and below on smaller screens I can see if there is an elegant way of doing that, but it is quite a bit more complicated.

**Comment by SnevelRetlaw** [comment]
Nice Nienke, that looks good! You can check if the current board agrees as well, although I think they will.

**Comment by JACY24** [comment]
Looks very nice! Just for layout I think it might be nice to align the pictures of the TCPs and the first to university bodies, but apart from that we as board agree with these changes.

**Comment by NienkeWessel** [comment]
After elaborate discussion, we believe it to be technically infeasible to get the pictures at the same height. This is because the two are in separate columns and it is not easily possible to get content from two different columns at the same height.
