### ISSUE TITLE
Schema.org annotations

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2309]
### Is your feature request related to a problem? Please describe.
schema.org exists and is pretty awesome. It would be nice to implement this on some pages we have, like events, so Google can feature our events as rich search results etc.

### Describe the solution you'd like
Add annotations for https://schema.org/Event

### Motivation
It's nice, modern, state-of-the-art, and we are a study association CS

### Describe alternatives you've considered
Not doing it

**Comment by pingiun** [comment]
This benefits no-one. This is a bad issue and you should feel bad Job
