### ISSUE TITLE
Get confirmation mail when registering for events

### ISSUE THREAD

**Issue by jendusseljee** [svthalia/concrexit#2310]
### Describe the solution you'd like
An option in your profile to get confirmation emails when registering for event, these emails should have the date and such in them so that Google/Apple can recognise them and add them to your calendar automatically.

### Motivation
This way people can easily see and remember the events they have registered for.

**Comment by JobDoesburg** [comment]
I would want this to be done after #971

**Comment by JobDoesburg** [comment]
This should be a setting in a members profile if you want this or not

**Comment by ColonelPhantom** [comment]
I think we also provide a calendar that you can integrate into your own. It could probably use some work though (not sure how it works with optional registrations, for example) but it solves a similar problem.

More options is always better though!
