### ISSUE TITLE
Change the header photos

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2318]
### Is your feature request related to a problem? Please describe.
The header photos are a bit outdated 

### Describe the solution you'd like
Choose some new photos

### Motivation
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/7915741/164710169-e2d4ac27-04f0-48e6-bceb-bc05a1d3c30f.png">
these guys are old
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/7915741/164710211-ad6fa23f-b021-4dab-9f4f-de45b11c56a2.png">
this image is lowres and old

### Describe alternatives you've considered
Not

### Additional context
I have access to the RU Brandportal with nice stock images of the university that we can use

**Comment by se-bastiaan** [comment]
Very much bib

**Comment by JobDoesburg** [comment]
Just sent another email to the paparazcie requesting an update

**Comment by JobDoesburg** [comment]
Sending an email again

**Comment by DeD1rk** [comment]
Any reply yet? Otherwise I'll go pressure them :)

**Comment by JobDoesburg** [comment]
Nope they're ignoring me
