### ISSUE TITLE
Time bases QR code to register presence for events

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2319]
Feature request (I'm making this via the Github app so the template doesn't work) 

Registering presence of people is a time consuming thing, sometimes resulting in long queues. Now thalia pay exists, there is no reason to actually have these queues.

I propose a system with a QR code that people can scan to indicate their presence. The QR code should be time based and contain a secret string, so the organiseer can publish it and there is some level of certainty that people are actually there.

**Comment by DeD1rk** [comment]
Nice idea. So the organizers get a QR code (they show it on their phone at the door I guess? Printing it and hanging it somewhere limits the possibility to make it time-based and makes it trivial to just share a picture of it). 

I think that way this works perfectly for e.g. lunch lectures. But of course there are also events with payments. Perhaps (although this will make it much more complex which isn't really nice) we can combine it with payments. When payment is still required scanning the QR could prompt to pay with thalia pay first, and only after that mark someone as present (perhaps show a large green thing such as with pizzas?). However, that way there are still some difficulties: what if people pay by card or cash (they'd need to pay first?), and what to do when paying is complicated (such as the difficulties with different prices at the boulderen event, so perhaps resolved only after the event). I guess it's fine to just fall back on the existing admin for that, but it makes me doubt whether integrating with payments is desirable. 
It's also an option (I think this is probably best) to just mark people as present, and notify them that they have/haven't paid (again with thalia pay prompt but not required before marking as present). After all being present doesn't really require having paid anyway.
