### ISSUE TITLE
Test makefixtures during PR 

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#2341]
### Describe the change
This is a proposal to somehow run makefixtures during tests in PRs.

### Motivation
The makefixtures command breaks very often.

### Current implementation
We do not test it.

### Suggested implementation
Add it in the github workflow.

### Additional context
Add any other context or screenshots about the change here.

**Comment by DeD1rk** [comment]
It should be possible to just write a normal test that runs createfixtures right? Then there's no need to change anything in the workflows

**Comment by se-bastiaan** [comment]
Ah yes that would work perfectly well too indeed. Probably better even.

**Comment by rowan-vr** [comment]
Will be fixed in #2471
