### ISSUE TITLE
Cannot lock shifts

### ISSUE THREAD

**Issue by nvoers** [svthalia/concrexit#2437]
### Describe the bug
shifts cannot be locked anymore. backend says that there is an error, but there seems not to be a visible error

### How to reproduce
1. go to an unlocked shift
2. check the 'locked' box
3. save the shift
4. get an error that something is wrong, but 'locked' box becomes an icon
5. reload the page
6. shift is still unlocked

### Expected behaviour
shift should properly lock

**Comment by se-bastiaan** [comment]
I cannot reproduce this as superadmin on staging.

**Comment by nvoers** [comment]
Okay reloading doesn't unlock the shift apparently. If you go back and click on the shift again, it should be unlocked again

**Comment by JobDoesburg** [comment]
I actually have been able to reproduce it in a shift with 1 unpaid order
