### ISSUE TITLE
Can edit shifts I'm not manager of

### ISSUE THREAD

**Issue by nvoers** [svthalia/concrexit#2438]
### Describe the bug
It is possible for everyone with the shift permissions to edit every shift.

### How to reproduce
Edit a shift that you are not a manager of.

### Expected behaviour
As with events, it would seem logical to me that you can only edit shifts that you are a manager of. Shifts always have one manager, so this should work.

**Comment by se-bastiaan** [comment]
Hey! Could you maybe elaborate on the situation? What you are describing is exactly how the shifts should work.

Unless someone is a superadmin or has the 'override managers' permission they should only be able to manage the shifts that the are a manager of. And those managers are determined by the member groups they are in.

**Comment by se-bastiaan** [comment]
@JobDoesburg maybe check if committees or people have the override permissions? I cannot see it and have confirmed that the code should work.

**Comment by nvoers** [comment]
For instance I can edit the 'beach party drinks' shift which is only managed by the sjaarscie, while I'm not in the sjaarscie.

**Comment by nvoers** [comment]
Yep all good now
