### ISSUE TITLE
The forget password page is empty.

### ISSUE THREAD

**Issue by tintin10q** [svthalia/concrexit#2449]
### Describe the bug

When you click on the forget password button on the [login page](https://thalia.nu/user/login/) you get to an empty page (https://thalia.nu/user/password_reset/) without any clear way to reset your password. So people can't reset their password. 

### How to reproduce
Steps to reproduce the behaviour:
1. Go to [https://thalia.nu/user/login/](https://thalia.nu/user/login/)
2. Click on 'Forgot Password'
3. Notice the empty page

### Expected behaviour
A page where you can enter your email to reset your password.

### Screenshots

![Log in page](https://user-images.githubusercontent.com/24190849/188420871-f679e64a-858a-4600-8728-2e6ea03e74ab.png)

![Empty page](https://user-images.githubusercontent.com/24190849/188420929-8e3f53ef-e1b5-4889-8422-2edff15bcf51.png)

**Comment by tintin10q** [comment]
I did manage to log in now and the [change password](https://thalia.nu/user/password_change/) page does work.

**Comment by se-bastiaan** [comment]
Thanks, this is quite inconvenient 😅 

The change password page is a custom feature by us while the password reset is a [Django built-in feature](https://docs.djangoproject.com/en/4.1/topics/auth/default/#module-django.contrib.auth.views) so it makes sense that that functionality would work.

It's probably related to #2237
