### ISSUE TITLE
Promotion Request not showing

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2453]
### Describe the bug
The priority requests section in the administration shows 0 requests, while it is known there have been requests made

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'user options'
2. Click on 'administration'
3. Scroll down to 'promotion'
4. Click on 'promotion requests'

### Expected behaviour
The page should show all requests that have been made.

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/12158186/188486344-65345249-fe61-438a-b98f-0c89a6241026.png)

**Comment by DeD1rk** [comment]
@nvoers currently 

```python
class UpcomingRequestManager(models.Manager):
    def get_queryset(self):
        end_date = timezone.localdate()
        start_date = end_date - PROMO_PUBLISH_DATE_TIMEDELTA
        return super().get_queryset().filter(created_at__range=(start_date, end_date))
        
``` 
is the default manager for PromotionRequest, so it's not possible to view any non-upcoming promo request in the admin. Should there just be the default .objects manager with a default ordering for the admin instead?

**Comment by nvoers** [comment]
The code is fine like this imo. But I made promo requests for borrels a month from now which for some reason have disappeared. Cato told me it ended up being something else rather than a mistake in the code

**Comment by DeD1rk** [comment]
Well I don't think it's all intended behaviour. There are filters in the sidebar, even though only a fraction (requests made in the last week) can be seen.

So if you make a request for a borrel in november today, next week it will not be accessible any more, even thouh the publish date is over a month later.
