### ISSUE TITLE
Running tests is very slow due to newsletter migration

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#2462]
### Describe the change
Running tests takes very long due to the migration `newsletters.0015_embed_images_html`. I'm not sure how this migration works and why it is so slow, but we should probably work around the slowness of this in some way, e.g. enabling a developer to re-use the same database when testing.

### Motivation
When debugging some tests, needing to wait multiple minutes to run each test is very demotivating and makes it impossible to iterate quickly to see if my changes are correct.

### Suggested implementation
Either speed up this migration, find a way to 'skip' it, or use enable using a pre-populated database for testing.

**Comment by se-bastiaan** [comment]
Quick fix should be removing any newsletter HTML files from your media folder. It was part of #2290
