### ISSUE TITLE
Vacancy page is broken

### ISSUE THREAD

**Issue by Gulianrdgd** [svthalia/concrexit#2467]
### Describe the bug
The learn more button. If you click on it it sometimes goes to the vacancy and on some other vacancies it does nothing. 

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'https://thalia.nu/career/vacancies#'
2. You can click on learn more

### Expected behaviour
Learn more buttons

### Additional context
I am using firefox and linux, however I verified that also on chromium it didn't work.

**Comment by se-bastiaan** [comment]
> two parts which are broken

aka there are two issues :p

one is already in #2455
