### ISSUE TITLE
Sales shifts admin changelist_view is very very very slow

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2469]
### Describe the bug
Sales shifts admin changelist_view is very very very slow

### How to reproduce
1. Go to https://thalia.nu/admin/sales/shift/
2. It is slow

### Expected behaviour
Don't be so slow

**Comment by DeD1rk** [comment]
Seems like the execution of the queries for number of orders and total revenue is slow, as (in the database) it takes time linear in the total number of orders. 
For me locally, the queries already take >4ms with 120 orders in my db, while on production there are over a thousand so far.

Still that doesn't fully explain the 10+ second loading times though I think.

Although it would be really sad not to have a single source of truth, it may be nice to actually store amounts in the database (make order.subtotal a normal field, and keep it up to date with signals/overriding save()).

**Comment by JobDoesburg** [comment]
Yes...

**Comment by pingiun** [comment]
This was fixed by #2502
