### ISSUE TITLE
Promotion requests get deleted instantly

### ISSUE THREAD

**Issue by nvoers** [svthalia/concrexit#2488]
### Describe the bug
After saving a promotion request, it disappears or it gets deleted instantly. on thalia.nu/admin I can still see the action that I created one. When clicking on the action, I get the error that promotion request [ID] does not exist.

### How to reproduce
1. create and save a promotion request
2. go to thalia.nu/admin
3. click the most recent action
4. get an error

### Expected behaviour
Promotion requests should not be deleted instantly

**Comment by se-bastiaan** [comment]
I don't they are deleted, I think they are not shown due to the object manager. As mentioned in https://github.com/svthalia/concrexit/issues/2453

**Comment by JobDoesburg** [comment]
Pretty sure yeah, #2475 fixes this but hasn't been released yet
