### ISSUE TITLE
Mailing lists don't seem to sync

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2490]
### Describe the bug
Mailing lists don't seem to sync

### How to reproduce
Steps to reproduce the behaviour:
1. Look at the members of footballmembers@thalia.nu in GSuite and compare with concrexit. 
2. People like Jord are not in the mailinglist
3. People like Todd is in there but he left

### Expected behaviour
Be synced

### Additional context
This is the only case I can confirm right now. It could very well be that there are more, which is why I gave it this priority

**Comment by ColonelPhantom** [comment]
This issue was fixed, right? Is this issue still needed?
