### ISSUE TITLE
Time/Date picking window is underneath the description styling 

### ISSUE THREAD

**Issue by Gulianrdgd** [svthalia/concrexit#2491]
### Describe the bug
When adding an event to the site the window, which pops up when you select a date or a time, appears underneath the text styling bar of the description. The z index of the description text styling bar should be lower then that of the time/date selection window.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'thalia.nu/admin'
2. Click on 'events'
3. Click on add event
4. Go to details
5. Go to 'End time'
6. Click on the clock icon
7. See error

### Expected behaviour
 The z index of the description text styling bar should be lower then that of the time/date selection window.

### Screenshots
[screenshot of the problem](https://imgur.com/a/sYT13lL)

**Comment by JobDoesburg** [comment]
![Urbx5bs](https://user-images.githubusercontent.com/7915741/191544381-9708dd55-76ff-494e-9489-fd8563c12f03.png)
