### ISSUE TITLE
New email warning shows up in the wrong place

### ISSUE THREAD

**Issue by stefanvi** [svthalia/concrexit#2494]
### Describe the bug
When a member changes their email address, but they enter their old email address, the warning shows up on the left instead of on top. See screenshot.

### How to reproduce
Steps to reproduce the behaviour:
1. Chang an account's email address
2. Enter the same address as before

### Expected behaviour
It should be above the email box.
![Screenshot_20220921_184655](https://user-images.githubusercontent.com/60365750/191571705-f955bec2-1fb9-475e-8a81-febc0cd9d40c.png)

**Comment by Pokemaster69** [comment]
This issue does not exist (anymore) on the current website or master branch and was probably an old issue from when the branch where this issue exists was created.
