### ISSUE TITLE
Codestyle cleanup

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#2504]
For the sake of maintainability and just the satisfaction of clean code, I would like to clean up some ugly code. For instance, we have code that still uses python 2 style `super(SomeModel, self).__init__`, and loads of messy imports (unused or unorganized).

Let's get rid of that :)

Perhaps it's an idea to enable isort (with custom settings to work nicely with django and black), and maybe look at enabling some more flake8 lints.

Related is also the idea to remove all translation code, but that's controversial...

**Comment by se-bastiaan** [comment]
> Related is also the idea to remove all translation code, but that's controversial...
Not controversial imo, just either remove _everything_ or _nothing_. Not something in-between.

We once had a check (I think in pylint or flake) that blocked having unused imports. Definitely a good idea. 
And we also once had a isort config: https://github.com/svthalia/concrexit/pull/2182

**Comment by se-bastiaan** [comment]
Maybe this is nice:
https://pypi.org/project/pyflakes/
https://github.com/PyCQA/autoflake

It doesn't to style checks like flake8 but can do basic checks.
