### ISSUE TITLE
Upload .svg files as partner logos

### ISSUE THREAD

**Issue by JasmijnB** [svthalia/concrexit#2506]
### Is your feature request related to a problem? Please describe.
A lot of partners have .svg files as their logo, and it is pretty annoying and arbitrary to have to convert these to png and lose quality.

### Describe the solution you'd like
When uploading a partner logo, both when creating a vacancy or a profile page it should be possible to upload .svg extensions and have these show correctly on the site.

### Motivation
Better quality logos on the site and a very happy partnercie and external :)

### Describe alternatives you've considered
I guess you could just not do it

**Comment by DeD1rk** [comment]
I think I'd argue against this. In contrast to the banners, for the small logos there's just not really a visual advantage (you can have high quality png or webp without any filesize problems as the pictures will be small). 
But making them svgs means that we also need to support svgs in emails (do most email clients even support that/is it secure?). And (see also #1701) it probably won't be feasible to display svg partner logos in the app.

So I think a better solution would be for the extern to use a simple cli tool/script to convert to high quality webp images.

**Comment by JobDoesburg** [comment]
Dirk is giving good arguments, but I do also like svg... So maybe do both?

**Comment by DeD1rk** [comment]
Give optional svg as separate field, like we considered but haven't implemented yet for banners? Sounds ideal to me, but it doesn't help do anything for the main motivation point: reducing workload for extern, unless we implement conversion in concrexit, which seemed tough/unreliable(??, then again we could show the conversion for confirmation..)

**Comment by JobDoesburg** [comment]
I wouldn't want to build conversion, just add it as a optional feature. 
Also, not all partners are included in the newsletter so we can work with a `banner_logo` that can be .svg, and `email_logo` that must be .png. 

Note that #1650, which someone started working on last Wednesday is also relevant

**Comment by se-bastiaan** [comment]
It is 100% possible to do implement conversion and I don't think it would be bad if we'd do that. 
Easiest way is to catch the image on save and replace it. Similar to the resizing of the photos that are uploaded. There is a nice library for it: https://cairosvg.org/, although it doesn't do webp.

**Comment by pingiun** [comment]
I suggest you run [`rsvg-convert`](https://manpages.ubuntu.com/manpages/trusty/man1/rsvg-convert.1.html) on the svg files before uploading them.
