### ISSUE TITLE
API v2 Events list is broken on master

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#2512]
### Describe the bug
API v2 eventslist is broken (throws an exception)

### How to reproduce
Go to localhost:8000/api/v2/events for example

### Expected behaviour
Get a list of events in JSON

### Additional context
This seems related to #2461 because not every event is annotated (can be fixed by either adding it elsewhere or by fixing its usage to be optional) and after that also #2459 since it refers to "organiser" still it seems.

**Comment by DeD1rk** [comment]
Just for reference: #2123
