### ISSUE TITLE
Vacancies for partner without partner page don't open

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2515]
### Describe the bug
Vacancies for partner without partner page don't open

### How to reproduce
1. Check out https://thalia.nu/career/vacancies#vacancy-117 or hit the Learn More button for ICT TRAINEE - JAVA DEVELOPER from the Belastingdienst

### Expected behaviour
Do open a details page, maybe in a modal or offcanvas

### Screenshots
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/7915741/192245844-2049ab28-8e8c-4f7f-8cb9-114a42eefe63.png">

### Additional context

**Comment by se-bastiaan** [comment]
https://github.com/svthalia/concrexit/issues/2467 
https://github.com/svthalia/concrexit/issues/2455

This has been fixed already

**Comment by ColonelPhantom** [comment]
It seems that on the vacancy page, still nothing happens, at least for vacancies without an active partner.

**Comment by se-bastiaan** [comment]
You're right, apparently there still is a js error

**Comment by se-bastiaan** [comment]
okay big fun, it was not really js. It was that the vacancies were not rendered at the bottom of the page so you couldnt scroll to them
