### ISSUE TITLE
Update to poetry 1.2.x+

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#2533]
### Describe the change
In Poetry 1.2.0 and later the syntax for dev dependencies has changed. So we should update and migrate the pyproject.toml file.
https://python-poetry.org/blog/announcing-poetry-1.2.0/

### Motivation
We need to keep up! This functionality is now deprecated.

### Current implementation
Poetry lower version?

### Suggested implementation
Just update!

**Comment by pingiun** [comment]
I think some of us are still running older versions of poetry, and the new version still supports the old syntax. It's unfortunate that poetry does not give a timeline of when this will be removed but I think we can just wait a bit more

**Comment by ColonelPhantom** [comment]
Looks like #3209 includes this migration, and so we can close this issue.

**Comment by DeD1rk** [comment]
Oh yes that's true, oops. But yes if people are still on old versions it's really time to upgrade
