### ISSUE TITLE
Help with interacting with the api?

### ISSUE THREAD

**Issue by tintin10q** [svthalia/concrexit#2541]
Hi, 

This is a question for some guidance on how to interact with the Thalia api. I have looked around but there does not seem to be one concrete source of information about this. I have some questions but feel free to tell me more. 

The website seems to use username and password authentication. Is making a POST request to `https://thalia.nu/user/login` with the form data `password` and `username` enough to get a token or session? If yes what scopes does this token have? Do I understand correctly that this token is added to the cookies? When using this mode of authentication do you always have to have the cookie set? In `session_id`? Or is there another way to send the token without it being in a cookie?
I tried to send a request to `/user/login` with form data password and username but the response did not set the `session_id` cookie. What else could be required? Would this only work if I send the post request from code and not from `https://thalia.nu`?

There also seems to be oauth2 implemented! How can I get a `client_id` and `client_secret`? I know how oauth2 works and I think I can figure the rest out if I can get a `client_id` and `client_secret`.

I also found [something in the code](https://thalia-documentation.s3.amazonaws.com/master/_modules/thaliawebsite/api/openapi.html#OAuthAutoSchema) about openAPI. Are there any openAPI documents available and if so where?

**Comment by tintin10q** [comment]
I didn't mean to add the feature label.

**Comment by tintin10q** [comment]
Thanks @DeD1rk that is very helpful. Especially the openAPI docs. Maybe put that link in the readme?

I will send an email for a client id and secret for staging and I guess when I am done making the thing I will ask for a client id and secret for production. How can I get a (normal) user account for the staging?

**Comment by DeD1rk** [comment]
I'll create an account for you

**Comment by tintin10q** [comment]
Thanks, I send an email to [www@thalia.nu](mailto:www@thalia.nu) for the client secret and id. Is this email still in use?
