### ISSUE TITLE
Calendar wrongly shows registered for an event.

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2600]
### Describe the bug
I was registered for an event, and then deregistered, however the calendar still shows "you are registered for this event". This includes the event being magenta. When going to the event page it does not show as registered.

### How to reproduce
Steps to reproduce the behaviour:
1. Register for an event
2. Deregister
3. Go to calendar
4. See magenta event that you are not registered for

### Expected behaviour
The event should not show as registered

### Screenshots
![screenshot-2022-10-16-122038](https://user-images.githubusercontent.com/19241481/196030103-ee429a3d-7488-4381-ac8d-6cf6bce91fba.png)
![screenshot-2022-10-16-122028](https://user-images.githubusercontent.com/19241481/196030106-8b335ffa-29cf-4e95-a574-e49b8ec89224.png)

### Additional context
I am sorry for breaking the 2^6 issues. Clearly the only solution to getting back to such a good number is to fix this issue ASAP

**Comment by ColonelPhantom** [comment]
I'm hoping to solve this in #2458, but that's getting kind of stale. Will definitely try this specific case!
