### ISSUE TITLE
Organiser name and email broken in email when moving from waiting list

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2623]
### Describe the bug

<img width="573" alt="image" src="https://user-images.githubusercontent.com/7915741/198902437-269d6ca3-6c99-43bc-9e7d-458b3e56b329.png">

`If this date has already passed you can contact the  via .` should contain the organizer details

### How to reproduce
Send an email for moving away from the waiting list

### Expected behaviour
Contain the organizer details

**Comment by DeD1rk** [comment]
Actually has been solved in #2808.
