### ISSUE TITLE
Summary download not working

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2625]
### Describe the bug
Some summaries (for example Data Mining 2019-2020 Practice Exam Midterms) are not downloaded when clicked. They also do not work when trying to view them through the Site Administration. Pressing these buttons only leads to a new empty tab. 

Some summaries still work however.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'education'
2. Scroll down to 'data mining'
3. Click on 'data mining'
4. Click on '2019-2020'
5. Click on 'Practice Exam Midterm'

### Expected behaviour
Clicking this button should download the associated file.

**Comment by se-bastiaan** [comment]
![Screenshot 2022-11-01 at 13 37 09](https://user-images.githubusercontent.com/1799914/199234014-07844e53-8209-4a3e-ac07-7f469b521315.png)

**Comment by JobDoesburg** [comment]
Currently we get an 403 from Nginx
