### ISSUE TITLE
Add 'what are all those files' section to README

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2631]
### Is your feature request related to a problem? Please describe.
Concrexit is overwhelming to new people, and we have developed a certain concrexit-flavoured Django standard (that the django documentation does not cover)

### Describe the solution you'd like
Add a section to the readme that explains for most files and directories what's in there, and what should be in there, and some best-practices

### Motivation
Helping people get started

**Comment by se-bastiaan** [comment]
Based on this issue I have no idea what is concrexit-flavoured or what should be added to the readme exactly 😅

**Comment by DeD1rk** [comment]
Closed in #3090
