### ISSUE TITLE
Look at KiOui/TOSTI filters for adding info banners to pages

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2635]
### Describe the change
Right now, the base template contains some hardcoded banners, like "you're not a member anymore". That logic shouldn't be in the `thaliawebsite` app but in the members app.

TOSTI solves this in a nice way with `Filters` (stolen from, yes, Wordpress): See https://github.com/KiOui/TOSTI/blob/master/website/tosti/filter.py 
https://github.com/KiOui/TOSTI/blob/7008c332758f6e89716cdf8f9a7220aea36b877a/website/users/views.py#L37-L44 and https://github.com/KiOui/TOSTI/blob/7008c332758f6e89716cdf8f9a7220aea36b877a/website/thaliedje/apps.py#L14-L25

### Motivation
Separation of concerns

**Comment by se-bastiaan** [comment]
Wouldn't it be better to just use django context processors to add this information to te request? https://docs.djangoproject.com/en/4.1/ref/templates/api/#using-requestcontext
That way the values are properly set per request and you can do that in any app without misusing the app ready function for something that it is not intended to (which is really only to register signals).

Do note that the django docs [warn you to not do any db queries in app.ready](https://docs.djangoproject.com/en/4.1/ref/applications/#django.apps.AppConfig.ready)
