### ISSUE TITLE
Prefetch photo likes for album view

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2641]
### Describe the change
For some reason, despite the fact that we use queryable properties, the album view triggers a lot of duplicated db requests querying all likes for a photo. This should be optimized

### Motivation
Save our DB

### Suggested implementation
prefetch related? Or really changing the code more fundamental

### Additional context
Use the debug toolbar

**Comment by JobDoesburg** [comment]
Dont forget the 'liked photos' page as well!

**Comment by DeD1rk** [comment]
Properties are only done during queryset evaluation if they are selected with `select_properties`. I think thats not used anywhere in our codebase so might be a good idea to find other places where that helps as well
