### ISSUE TITLE
Find a faster way to request signatures from S3 storage objects

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2659]
### Is your feature request related to a problem? Please describe.
Staging is very slow. It takes seconds to get signatures for S3 objects. And our SSD's are getting too expensive

### Describe the solution you'd like
This should be faster, so we can move to S3.

### Motivation
Money and server load

**Comment by wdoeland** [comment]
Job and I discussed this issue and we came to the following solution:
- process thumbnails at upload-time
- execute this as a batch when uploading an album and only show the album once the pictures have been uploaded and thumbnails have been generated
- use django-thumbnails
