### ISSUE TITLE
Site gives 400 error

### ISSUE THREAD

**Issue by movieminer** [svthalia/concrexit#2673]
### Describe the bug
When I try to access www.thalia.nu, the site returns a 400: Bad request error

### How to reproduce
Steps to reproduce the behaviour:
1. Go to www.thalia.nu

### Expected behaviour
See the site

### Screenshots
![image](https://user-images.githubusercontent.com/12615607/202426492-f1abb634-017d-4718-a31e-bc1487034091.png)

**Comment by movieminer** [comment]
The issue seems to be resolved.

**Comment by Gulianrdgd** [comment]
I can reproduce
