### ISSUE TITLE
External events admin does not show TinyMCE editor

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2675]
### Describe the bug
External events admin does not show TinyMCE editor for the event description

### How to reproduce
1. Go to the external events admin

### Expected behaviour
Do show the TinyMCE editor

**Comment by se-bastiaan** [comment]
Is this really useful? External events will never show rich text anywhere, the tags will be stripped

**Comment by JobDoesburg** [comment]
Oh for real, I thought they also just had event pages. Nvm then
