### ISSUE TITLE
Tests fail on Python 3.11

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#2689]
### Describe the change
Currently, when running `make test` with Python 3.11 we get failures in two tests. Both errors are

```
AttributeError: <module 'payments.payables' from 'concrexit/website/payments/payables.py'> does not have the attribute 'get_payable'
```

which seem to originate from 
```py
    @mock.patch("payments.payables.get_payable")
```

I haven't tested if any payable-related code also breaks when running the website normally.
### Motivation
Even if we stick to Python 3.9 for the time being, it is always good to be compatible with the latest version so that we can easily upgrade in the future if desired. Supporting the current version of Python is also convenient for users of operating systems with newer Python versions.

### Current implementation
It is possible to work around this issue by installing Python 3.10 (or 3.9) and then instructing Poetry to use it with e.g.
```sh
$ poetry env use python3.10
```

### Suggested implementation
I believe the error originates from how imports are performed? It looks like there is a change in how imports are handled in Python 3.11, as `get_payable` belongs to a class, but we seem to use it as part of a module.

### Additional context
Full backtrace for one of the failing tests:
```
======================================================================
ERROR: test_creates_payment (payments.tests.api.v1.test_viewsets_payments.PaymentProcessViewTest.test_creates_payment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.11/unittest/mock.py", line 1356, in patched
    with self.decoration_helper(patched,
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/unittest/mock.py", line 1338, in decoration_helper
    arg = exit_stack.enter_context(patching)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/contextlib.py", line 502, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/usr/lib64/python3.11/unittest/mock.py", line 1427, in __enter__
    original, local = self.get_original()
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/unittest/mock.py", line 1400, in get_original
    raise AttributeError(
AttributeError: <module 'payments.payables' from '/home/quinten/code/thalia/concrexit/website/payments/payables.py'> does not have the attribute 'get_payable'
```

**Comment by DeD1rk** [comment]
Is this still the case? and if so, how feasible is it to just drop support for 3.9 (i.e. how much trouble would it cause for people? what's installed on ubuntu these days?)
Dropping 3.9 would be nice so we can use 3.11 language features

**Comment by ColonelPhantom** [comment]
The tests currently pass on my laptop with Python 3.11. It seems they're also passing with 3.10. I guess ruff fixed this!
