### ISSUE TITLE
V2 events API reports wrong participants number

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2703]
### Describe the bug
On some event the amount of participants is not reported correctly on V2 version of the API.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to https://thalia.nu/api/v2/events/1005/
2. Go to https://thalia.nu/events/1005/
3. Observe a small difference.

The difference is not present in V1
Counting the pictures of the participants matches up with V1 and not V2

### Expected behaviour
The V2 API should properly report the number of registered members

**Comment by se-bastiaan** [comment]
Did you remove the registration? With my register and cancel action I have brought the number in API v2 to 13 now :p

**Comment by se-bastiaan** [comment]
I think this can be a bit flaky based on the python process that is running the request. Let's review this piece of code:

```
participant_count = AggregateProperty(
        Count(
            "eventregistration",
            filter=~Q(eventregistration__date_cancelled__lt=timezone.now()),
        )
    )
```

This is a property in the model file so everything here is executed at the time the server is started and the file is loaded. This means that `timezone.now()` is executed and the value will always be _that_ value after init.
