### ISSUE TITLE
Remove test dependencies from push notifications on events

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2755]
### Describe the change
Remove test dependencies from push notifications on events

### Motivation
Better modularity of apps

### Current implementation
The tests of the app depend on events

**Comment by DeD1rk** [comment]
I'm confused about this, it makes sense for `pushnotifications.tests` to depend on `events` and I don't recall seeing an opposite dependency from `events.tests` on `pushnotifications`

**Comment by JobDoesburg** [comment]
I think the refactor might have already solved this
