### ISSUE TITLE
Make member groups extend auth.groups

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2760]
### Describe the change
Make member groups extend auth.groups

### Motivation
Better modularity, as some apps then can depend on auth.groups instead of activemembergroups (like event, sales).
This also makes it possible to introduce ad-hoc groups for certain occasion that are not necessarily a committee or society

### Suggested implementation
Just extending the auth group model

**Comment by mark-boute** [comment]
@Pokemaster69 what is the progress on this?
If you are not working on this I'd like to take over this issue :)

**Comment by mark-boute** [comment]
Taking over this issue after discussing with Niels

**Comment by mark-boute** [comment]
Will not be implemented, too much effort in re-keying for such a little refactor.

**Comment by mark-boute** [comment]
Will not be implemented, too much effort in re-keying for such a little refactor.
