### ISSUE TITLE
Future partner events return past events in edge case

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2821]
### Describe the bug
In some cases the partner events returns bad results

### How to reproduce
https://staging.thalia.nu/api/v2/partners/events/?ordering=start&start=2023-02-01T00%3A00%3A00.000
This shows events from 2021, even though the filter is set to future events only

### Expected behaviour
Only return events past 2023-2-1

### Screenshots
![screenshot-2023-02-15-202804](https://user-images.githubusercontent.com/19241481/219132630-71d6dc57-4f9f-47c4-8730-ffe2402ba869.png)

### Additional context
This should just work smh

**Comment by DeD1rk** [comment]
Looks to me like the APi works fine, but the URL you entered is wrong. the correct endpoint is now `events/external`, but when `partners/events` is redirected, the query params are dropped

**Comment by JAicewizard** [comment]
well, that still means the API doesnt return the things correctly. But I guess the app should move to this new endpoint? I dont have time to fix it now but can look at it tomorrow so at least the app shows things correctly

**Comment by DeD1rk** [comment]
Superseded by #2843.
