### ISSUE TITLE
Switch student well-being page contents

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2823]
### Is your feature request related to a problem? Please describe.
We want to have the services from university and the trust contact persons switched on the Student well-being page.

### Describe the solution you'd like
Switch the the two page-sections in the HTML for the different services around, making it so the university services are shown first.

### Motivation
We want to show the university-provided services more clearly and explicitly as suggested by the GM earlier.

### Describe alternatives you've considered
Show both side-by-side, but an earlier issue has shown that in current circumstances this is probably not possible.

**Comment by ColonelPhantom** [comment]
I'm currently looking at this, but have some questions:

- We probably need to adjust the text a bit. For example "University also offers some services to help students. Below are the most important points of contact." seems out of place, considering the use of "also". Should I try to update this, or will the board/someone else provide updated text?
- What should the layout look like exactly? Should the TCPs be below the 'general' link, or in-between (like Nienke's attempt in #2258 when on mobile)?

**Comment by timkersten655** [comment]
- Adjusting the text can be done by removing the word "also". "The University offers some services to help students. Below are the most important points of contact." would be a good replacement I think.
- Preferably have the TCP's be below the 'general link'.
