### ISSUE TITLE
Partner events are not filtered by `search`  parameter

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2828]
### Describe the bug
When using the search parameter in the partner events API the filter does not work
https://thalia.nu/api/v2/partners/events/?search=beest&ordering=start&start=2023-02-01T00%3A00%3A00.000  should have results filtered by "beest" but clearly also returns results not fitting this search

### How to reproduce
Steps to reproduce the behaviour:
1. Go to https://thalia.nu/api/v2/partners/events/?search=beest&ordering=start&start=2023-02-01T00%3A00%3A00.000 
2. See to many results

### Expected behaviour
There should be (approximately) no results as I suspect no partner event used "beest". I don't think partners have hosted a beestfeest

### Additional context
Needed for the search function in the app

**Comment by DeD1rk** [comment]
@JAicewizard did you read https://github.com/svthalia/concrexit/issues/2821#issuecomment-1432867562 yet?

**Comment by DeD1rk** [comment]
Superseded by #2843.
