### ISSUE TITLE
Model Relation Diagram generation with GraphViz

### ISSUE THREAD

**Issue by mark-boute** [svthalia/concrexit#2840]
### Is your feature request related to a problem? Please describe.
Generate a diagram from the model layer in the pipeline

### Motivation
Automatic Documentation is good

### Describe alternatives you've considered
Manual labor

### Additional context
I will implement this feature

`python manage.py graph_models -a -g -o models.png` requires: https://graphviz.org/download/
https://django-extensions.readthedocs.io/en/latest/graph_models.html

**Comment by JobDoesburg** [comment]
Nice, curious to see the result
