### ISSUE TITLE
Respect rotation of photos in fancybox

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#2852]
### Describe the bug
Photos in an album can have a rotation. That is not being used by fancybox (the fullscreen gallery) right now.

### How to reproduce
Look at e.g. photo 37 in the 'thalia on ice' album (https://thalia.nu/members/photos/thalia-on-ice/).

### Expected behaviour
All photos are upright.

### Additional context
I'm not sure why the website passes a rotation, instead of just serving pictures that are upright.

Perhaps it's a better idea to ensure that we store the files upright, rather than rotating then when rendering. That would also make https://github.com/svthalia/Reaxit/issues/366 unnecessary.

**Comment by JobDoesburg** [comment]
I think just passing the rotation info to fancybox is easiest

**Comment by LisanneWeidmann** [comment]
Does not look like fancybox has an easy fix for this issue, one would have to edit the css file manually. The thumbnail shows the image correctly, but inside the fancybox the rotation is not applied. The relevent files are: 

- /website/photos/static/js/main.js
- /website/photos/static/css/style.scss
- /website/photos/models.py

Possibly relevant StackOverflow page: https://stackoverflow.com/questions/24747957/image-rotation-with-fancybox

**Comment by DeD1rk** [comment]
As this seems hard, and having to do stuff like this is very ugly anyway, let's do #3133 instead.
