### ISSUE TITLE
Edit information field in admin gives error page

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2861]
### Describe the bug
The site gives the 500 error page when you try to edit information fields of registered users

### How to reproduce
Go to an event on the admin and press change on a user's registration. At "Fields:" press the "Edit Information Fields" button and the bug happens (found at parents day, Tim Kersten)

### Expected behaviour
I'd expect the appropriate page for editing a user's information fields.

**Comment by DeD1rk** [comment]
Confirmed, corresponding sentry log: https://thalia.sentry.io/issues/3905837977/?project=1463433&query=is%3Aunresolved&referrer=issue-stream

**Comment by DeD1rk** [comment]
Thats a very simple issue, probably solved by removing a sinlge `s` 😆 
But kinda surprising to see it's been there for 2+ years without anyone noticing.
