### ISSUE TITLE
[THALIA] Notification about your registration for Template Broken

### ISSUE THREAD

**Issue by tintin10q** [svthalia/concrexit#2870]
### Describe the bug
The email notification template about that you left the queue and are now registerted for the event is broken. The email is missing at the end.

### How to reproduce
Steps to reproduce the behaviour:
1. Sign up for event get in to the queue 
2. Wait until you leave the queue 
3. Get email notification 

### Expected behaviour

I expect the email to have the email of who I should contact in there.

### Screenshots
![IMG-20230314-WA0022.jpg](https://user-images.githubusercontent.com/24190849/225121805-75efc57b-9b23-4fa4-9ef9-9261c67f3d53.jpg)

**Comment by DeD1rk** [comment]
Hey there, we were aware of this issue, see #2808 and #2623. It's been fixed but not yet released. I'm hoping we can do that soon.
Thanks for notifying us anyway!
