### ISSUE TITLE
Add http endpoint for the next event 

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2871]
### Is your feature request related to a problem? Please describe.
We want to use a dns redirect to redirect to the first upcoming Thalia event. 

### Describe the solution you'd like
An endpoint (like /events/next) that redicects to the next Thalia event 
### Motivation
We want to setup a domain (sog.je) that redirects to this 

### Describe alternatives you've considered
Static html host that uses javascriot, but this would require using additional resources

**Comment by DeD1rk** [comment]
We can add this but you can also just get a few current/future events by time, and then loop through that response to get what you want. That's not very clean of course, but there's no guarantee that there aren't multiple events starting at the same time. So having an endpoint that returns only a single event (first one starting in the future, with lowest PK if multiple?) would be misleading.

**Comment by DeD1rk** [comment]
Okay I was confused thinking you meant an API endpoint. For a redirect view I see the appeal. But some things to consider: what if there are multiple events starting at the same time?

**Comment by JobDoesburg** [comment]
Also note that you won't be able to accomplish your goal with a DNS redirect. You need a HTTP 301/302 redirect

**Comment by DeD1rk** [comment]
e.g. google domains will do that for you for free and with nearly no setup though
