### ISSUE TITLE
Liked photos API returns duplicate photos on different api requests

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2878]
### Describe the bug
Different pages of the liked photos API return the same photo

### How to reproduce
Difficult, this is using @JeeVee11's account as I could not reproduce it. 

https://staging.thalia.nu/api/v2/photos/photos/liked/?limit=10&offset=0
https://staging.thalia.nu/api/v2/photos/photos/liked/?limit=30&offset=10

Both have pk=70
### Expected behaviour
this should kinda not happen

### Additional context
This is likely related to photos not following order and https://github.com/svthalia/Reaxit/issues/359

**Comment by JeeVee11** [comment]
> As we've solved the order of photos, I imagine this is probably also solved? Seemed like the like count annotation messes with the db-default ordering (no ordering != pk ordering if some join is done). @JAicewizard could you verify, as I already couldn't reproduce?

Still does not work :)
