### ISSUE TITLE
Directly import Registration field definitions from profile

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2879]
### Describe the change
Make registration.Registrations contain fields directly from members.Profile, instead of copying them

### Motivation
Better code quality

### Current implementation
Copied fields

### Suggested implementation

```python
class Registration(Entry):
    ...
    phone_number = Profile.phone_number

```

**Comment by JobDoesburg** [comment]
maybe it can be done even nicer

**Comment by DeD1rk** [comment]
I have a feeling this is not really how fields are intended to be used. Doesn't Django set e.g. `model` on the field instance? Whether this is safe to do depends very much on Django implementation details.

**Comment by DeD1rk** [comment]
Yes this is not quite safe. It's hard to predict whether this will straight up crash, work fine, or _seem to_ work fine and cause hell later.
