### ISSUE TITLE
Career Central Page on site.

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2921]
### Describe the solution you'd like
Have a career central link (https://ru.nxus.nl/student/group/0b242b79-01a4-4502-a582-8a0327676a2b) next to the other social media's in the bottom of the site.

### Motivation
It's one of Thalia's social media's so should be there with the rest.

**Comment by DeD1rk** [comment]
@WidadMajdoubi24 @Sophie2104 do you guys still want this? It was postponed due to XSS vulnerabilities that supposedly have been fixed (I couldn't reproduce as easily any more, although I still don't think it's nice/secure software).
