### ISSUE TITLE
Push notification registered from queue

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2922]
### Is your feature request related to a problem? Please describe.
Currently if you get into an event from the queue you get an email, which isn't seen on time by everyone. A push notification might help with this.

### Describe the solution you'd like
A push notification on a members app when they get into an event from the queue.

### Motivation
More people able to join events of prompted lastminute.

**Comment by DeD1rk** [comment]
Sounds like a good idea!
