### ISSUE TITLE
Some large commitee photos are a 404

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2926]
### Describe the bug
Some URLs to (large) committee photos return a 404 instead of the photo

### How to reproduce
Steps to reproduce the behaviour:
1. Go to https://thalia.nu/api/v2/activemembers/groups/?limit=1000&type=committee
2. Open large photo of the adviesco

### Expected behaviour
These images should just work

**Comment by DeD1rk** [comment]
This has been resolved by @ColonelPhantom (deleting the thumbnail tables with a management command IIRC)
