### ISSUE TITLE
Partner logos not displaying correctly

### ISSUE THREAD

**Issue by movieminer** [svthalia/concrexit#2942]
### Describe the bug
Partner logos on the [general page](https://thalia.nu/career/) are not displaying, while the partners do have a logo.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to https://thalia.nu/career/
2. See the logos not showing of Working Talent and Prodrive Technologies
3. Go to the pages of these companies
4. See that they do have logos

### Expected behaviour
Logos showing properly on the general page

### Screenshots
![image](https://user-images.githubusercontent.com/12615607/229471943-c27fbc98-d846-4dd4-811a-d668b88cbda2.png)
![image](https://user-images.githubusercontent.com/12615607/229472014-47ac81c5-d27b-4f8e-ac2d-ff7d6b2cee6d.png)

**Comment by DeD1rk** [comment]
See #2959
