### ISSUE TITLE
Upgrade to Django 4.2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#2960]
### Describe the change
Django 4.2 exists. We should use it.

### Motivation
4.2 is LTS, and the changes in it are pretty nice.

**Comment by DeD1rk** [comment]
renovate already automerged 4.2, which seems to be working okay. However, we're not yet using the new STORAGES settings (some dependencies don't work with it nicely yet). And it would be good to upgrade to psycopg3 too.

**Comment by JobDoesburg** [comment]
Also see #2984
