### ISSUE TITLE
500 when giving staff status

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#2966]
### Describe the bug
When giving scarletto staff status on the staging website, saving gives a 500

### How to reproduce
Steps to reproduce the behaviour:
1. Go to site admin
2. Click on users -> scarletto
3. Add staff permissions
4. Click save
5. see error

### Expected behaviour
it should just work

**Comment by ColonelPhantom** [comment]
I think this works now; staging was running on an old commit because the deploy workflow failed. I just tried to add scarletto to staff after manually re-running the deploy and now it works.
