### ISSUE TITLE
Fix Django color scheme toggle

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2984]
### Describe the bug
Since v4.2, Django Admin now has a toggle for switching between light and dark mode (and high contrast?). We don't properly support that, though.

### How to reproduce
1. Use the toggle

### Expected behaviour
Proper color schemes. Maybe even applied in the frontend too (not only admin)

**Comment by DeD1rk** [comment]
High contrast? Just dark, light, auto right? With our custom styling applying properly only with auto
