### ISSUE TITLE
Promo requests: status information for organisers

### ISSUE THREAD

**Issue by W-M-T** [svthalia/concrexit#3005]
### Is your feature request related to a problem? Please describe.
The way promo requests work currently is that there is no communication to the organisers of an event when e.g. the status of the promo request changes or the request has been delivered. This means that the organisers need to remember to check it manually every once in a while. I don't think this is a very good solution, especially if there's time constraints.

### Describe the solution you'd like
One possible solution could be to email organisers on status changes of promo requests for their events.
However, I think it would be better to first discuss whether this needs to be implemented in the website or not: it may be sufficient for the promocie to actively communicate themselves when they deliver something.

### Motivation
It's not that great to have to check over and over to see if promo is done.

### Describe alternatives you've considered
- Have the promocie send emails to organisers when things are done.

**Comment by DeD1rk** [comment]
Sending an email whenever `status` changes would be quite easy and sounds logical. But of course that would be a very limited message, so if there's any communication needed going further than "we're on it" and "we're done", that would need to be manual. 

@CatoOri what do you think? Is just a notification of status changes nearly always enough? Or is there typically more detailed information that should be communicated (e.g. should promocie send deliverables to the requestors?)

**Comment by DeD1rk** [comment]
We can CC the status change email to promocie?

**Comment by DeD1rk** [comment]
Actually with #3340 this is probably not necessary any more?
