### ISSUE TITLE
Change SECRETS_FILE to proper individual GitHub environment secrets and env variables

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#3017]
Right now we use one SECRETS_FILE that contains all secrets. It's better to make it individual secrets that we can set for the environment through GitHub

**Comment by LisanneWeidmann** [comment]
You mean by adding environment secrets?
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by JobDoesburg** [comment]
Yes! Though @DeD1rk should set them, but the CI should be changed so that instead of only passing on the SECRETS_FILE env variable, a number of files should be sent
