### ISSUE TITLE
Use alpine base image

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3026]
### Describe the change
Right now the concrexit docker image is based on the standard python base image. It would be nice to use the alpine base image (`python:3.11-alpine`) instead. See https://medium.com/swlh/alpine-slim-stretch-buster-jessie-bullseye-bookworm-what-are-the-differences-in-docker-62171ed4531d.

### Motivation
Size, speed, stability.

### Current implementation
Bullseye.

### Suggested implementation
Alpine.

### Additional context
See `infra/concrexit/Dockerfile`, and perhaps the entrypoint.

**Comment by DeD1rk** [comment]
Seems infeasible due to libsass not building properly :(

**Comment by T8902** [comment]
Maybe possible due to changed dependencies in the site, will look into it again.
