### ISSUE TITLE
Responsible disclosure update

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#3048]
### Describe the change
Update the responsible disclosure page to state we prefer reports to happen via our GitHub (as security vulnerability). Also add we don't pay out money

### Motivation
More structured

### Current implementation
There is an email

**Comment by LisanneWeidmann** [comment]
I made changes on branch 3048-responsible-disclosure
1.  I updated the single page to redirect reporters to the Github security issues page.
2. I updated the security.txt inside the infra folder to include a link to the Github security issues page.

For the second bullet-point @DeD1rk needs to update the signature.

**Comment by DeD1rk** [comment]
@LisanneWeidmann we/I decided maintaining GPG keys properly is not worth the effort, especialy considering that it's never been used. So the signature as well as the pgp key file and link can be removed. I can help with the server changes for that if needed
