### ISSUE TITLE
The same names with different capitalisation are seen as different

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/concrexit#3085]
### Describe the bug
When claiming promo requests in the admin site, if the claimant name is entered twice, first without capital and then with one. It is counted as two different persons.

### Expected behaviour
The same name with different capitalisation should still count as the same name.

**Comment by DeD1rk** [comment]
https://docs.djangoproject.com/en/4.2/ref/contrib/admin/filters/#using-a-field-name-and-an-explicit-fieldlistfilter

We could add a case-insensitive filter subclass
