### ISSUE TITLE
Use `many` flag instead of separate serializers for selectively including fields in detail views

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#3112]
### Describe the change
Currently, when we need/want a different set of fields in a ListSerializer compared to a regular Serializer we redefine the serializer with a new subclass which sets `fields` to a different value (see for example `OrderListSerializer`). The suggestion is to change this to one class that either includes or does not include some fields based on the value of `many`.

### Motivation
Reduces duplication and simplifies our class hierarchy.

### Suggested implementation
I discussed with @DeD1rk and we're not sure DRF provides a nice way to do this, but worst-case we can override `__init__` for serializers and make it read some new `exclude_many` meta field or similar.

**Comment by DeD1rk** [comment]
Actually because api views often expect a `serializer_class` attrbute, rather than an instance, I think it may not be practical to not have separate serializer classes as we can't always conveniently specify `many=True`
