### ISSUE TITLE
Fix OfflineGenerationError that seems to randomly occur sometimes

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3121]
### Describe the bug
https://thalia.sentry.io/issues/4196385962/?project=1463433&query=is%3Aunresolved+issue.category%3Aerror&referrer=issue-stream&statsPeriod=14d&stream_index=0

It seems to happen pretty much at random, I have no idea why. So far it's been fixed by just restarting the concrexit container (likely because of it triggering collectstatic and compress again).

### How to reproduce
Happens randomly for a few files sometimes, and persists until the next container restart.

### Expected behaviour
Static files work consistently.

### Additional context
It would be nice to also get static files working on S3/cloudfront

**Comment by DeD1rk** [comment]
It looks like it's something to do with concurrent parsing here: 
<img width="837" alt="afbeelding" src="https://github.com/svthalia/concrexit/assets/41264528/fe40fbbd-926f-4ac3-939f-d9600649e731">. 

The final offline_manifest differs between each run (not just in order but also in some additional entries) when running with multiple workers. But when using only 1 worker, the manifest always contains the same items.

With 1 worker it always contains these entries (in random order):
```
7f2bad1b1dac3510200c30078c035fec3cdc969159d805d14b01df86dd9cc2f0 <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.a7d5a5f285e1.css" type="text/css">
b966fe3fa8329870c9a0bb352cecc874eb840854c4802dd7d958f43e13346c23 <script src="/__compressor_url_placeholder__/CACHE/js/output.cc192b688da0.js"></script>
14b372831de65175469a34648b841abcf8fe691db534484ee9880fd158ed3f1a <script src="/__compressor_url_placeholder__/CACHE/js/output.71e843fbae21.js"></script>
5ef675f00762fa03769c9484058eb9e67cc2e3f56d6110a7e21d995013e3e55c <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.a97b4b22fee8.css" type="text/css">
edeacfc131a75c0e0a44756ebbbc024905f6e4b63b5e3dc43ff51511dfd486e4 <script src="/__compressor_url_placeholder__/CACHE/js/output.175e0d378dcb.js"></script>
528f759362e394fd0641ec85d87d81fc13b2d58cdd6cd41181670ca8d5d7de4b <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.66bc1ada0f6d.css" type="text/css">
82d5beed541ff13cf4ad72d427f8b4e409d44b839cb51e277b19b692e5df3e02 <script src="/__compressor_url_placeholder__/CACHE/js/output.dbecd026b0a8.js"></script>
281b947be98d3d0d6901ec767bfe949214071a463cbe5e214f14a0078a5285de <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.17c599832b3f.css" type="text/css">
c2af7f062b9646b012942dbc49395f77f31afb67c0202f8b5c320aae4a25c1fc <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.ccbf1377afb5.css" type="text/css">
735947b143189d3cad6e63cac8d28eaefde41b7fc65bb0cbe085ec9e012f8595 <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.e185ff0331b9.css" type="text/css">
756b5a25914f0fbba3d6e3ed647a1652858b6bf78c5fe934ebaffd4372a9b269 <script src="/__compressor_url_placeholder__/CACHE/js/output.a0c504ab8b2e.js"></script>
b895c9e3f6989968f18aec585f0f16e819f7db2feea64e029e283338e65a49bc <script src="/__compressor_url_placeholder__/CACHE/js/output.56a4df267755.js"></script>
b62de2ee950096458b03d4e65ff53ac729d804e6795eb18a856965a4d598ca58 <script src="/__compressor_url_placeholder__/CACHE/js/output.5a09c0b9dd52.js"></script>
90f92065c33d5a50726bcd40facfbf0479f4e10272fb719c52bcef1aef1f7c01 <script src="/__compressor_url_placeholder__/CACHE/js/output.85d9c7181607.js"></script>
14492bf6720b33358e4e80b791d79d500bbc3c31149a5c7b3fc3ca02fe2e4edd <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.607c19b7479d.css" type="text/css">
08b9e70456cd239c8d7fa358b45edd0225f3cbc0e0a9083b34ddf724fa868719 <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.90176e1fe7f0.css" type="text/css">
b1abb8fd95011f12875aa11eb98c77cbda5a9ab4eb0bf696429424907d23b44a <script src="/__compressor_url_placeholder__/CACHE/js/output.12159315e949.js"></script>
7f9b59a1a238f2308db09e47f7dbe83452b92e667c6f5735da6aca33289491b1 <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.f385f6c5ea4a.css" type="text/css">
cca2f28a1d3b9dea3a0a976483b4ecd1f1138055643de936d83d5d8acdc2c69f <link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.77fd0cb9e4e8.css" type="text/css">
015f6a77baa9431ddf9a47e89a7fd404e6fe0d55b04ff54f0d9f33a861ff36e6 <script src="/__compressor_url_placeholder__/CACHE/js/output.27384ba60bac.js"></script>
```

When using multiple workers, some additional keys appear, and some keys don't appear at random. For example, I've seen `{'0e1808372e0fe8c73618107bf96dcfc7e793aa8536fab499ca44df429cb55999', 'ef67be6405576a0da435c3911b9fdb4325bd50d6e1a13a742cbd6af3acb949dc', 'd161af3a1ebb49242d5144425fcadda6558208531d1dde8982a397bef502b42f'}` be in the manifest additionally, but `{'b62de2ee950096458b03d4e65ff53ac729d804e6795eb18a856965a4d598ca58', '14492bf6720b33358e4e80b791d79d500bbc3c31149a5c7b3fc3ca02fe2e4edd'}` missing.

I'm guessing something related to the django parser (`nodes`?) is not thread-safe.

It's a pain to debug, and quite certainly a bug in compressor (there have been similar reports for > 10 years). 
One option may be to disable offline compression. That may solve the issue (it's currently that way on staging, needs some more testing), but that would not work with S3. 
So for a long term solution I think it's probably best to drop compressor altogether, and replace it by checking in compiled scss files. Then we don't have the advantage of combining and minifying a few files, but with hosting on S3 I think that doesn't matter to much anyway (note that S3/cloudfront can even handle gzip/brotli compression for us).

**Comment by ColonelPhantom** [comment]
Would it be possible to somehow make this run single-threaded? That'd work around any race conditions.
