### ISSUE TITLE
Upload separate slide for the app

### ISSUE THREAD

**Issue by JasmijnB** [svthalia/concrexit#3128]
### Is your feature request related to a problem? Please describe.
It is very hard to design a slider which looks both good on the website and in the app. Which is why it would be great if you could upload separate files for both. 

### Describe the solution you'd like
The ability to upload a separate file for the app and for the website. 
If the app file not uploaded, then the site file will be used for the app (just like current behavior)

### Motivation
Better slider designs as you don't have the restrictions of needing to fit two separate formats.

### Describe alternatives you've considered
Change the format shown in the app. Which would add the advantage of not needing to design two separate sliders.
However the app might not look as good.

**Comment by JobDoesburg** [comment]
Note that slides on the regular website also already need to fit two formats: the mobile website is shown the same way as in the app

**Comment by DeD1rk** [comment]
Indeed slides should already be made (and always had to be made) such that they good look with only the middle 1075x430 px visible. This is documented in the [styleguide](https://thalia.nu/members/styleguide/) and promocie has this template:
![Website - Dark(1)](https://github.com/svthalia/concrexit/assets/41264528/099ad256-eaf3-4c18-837e-7a71bd5af2d4)

Of course allowing two different versions might make it _easier_, but I think it likely that people will then make slides that actually _look_ different. There shouldn't be a visual difference when switching between the partial/full view e.g. when changing the size of your browser. So allowing (although we really should mandate it then) two separate images will probably only lead to a worse experience for the viewer.
