### ISSUE TITLE
Actually rotate photos

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3133]
Currently we store in the db how photos should be rotated (it's part of exif metadata on jpegs or something, and gets lost when e.g. thumbnailing). It would be so much nicer to just have all photos be upright (rotating them) as soon as we save them. 
Then other places where we use photos don't have to consider rotation any more.

**Comment by JAicewizard** [comment]
not fixed everywhere, see https://thalia.nu/members/photos/2022-09-15-beach-party/#gallery-49. The thumbnail is correctly rotated, but the actual photo is not

**Comment by DeD1rk** [comment]
I mean I guess we can export all old rotations from a db backup and apply them

**Comment by JAicewizard** [comment]
Ah yeah that really sucks, I guess using an old DB backup is good tho as most rotated photos are old anyways

**Comment by DeD1rk** [comment]
Yes I've got a list from the backup the day before the release, so they're all in there, and it's just 772 reuploads

**Comment by DeD1rk** [comment]
Even better, the rotations were still saved in the prod database, as reuploading now no longer overrides the rotation to 0 either. 2 mistakes cancelling each other out 😆

**Comment by DeD1rk** [comment]
Should be fixed now
