### ISSUE TITLE
Serve static files from S3

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3210]
It would be great for performance if we can serve staticfiles from S3, like we do for media already.

With #3209, it should now be pretty easy, without any compressor problems.

It's important that we enable long-term caching (IIRC there's a 1-day default with cloudfront, but we should be able to cache indefinitely with staticfiles since there in manifest storage). Some compression would also be nice.

**Comment by DeD1rk** [comment]
This is pretty much done with 1447b8ec. There's one more thing to look at: collectstatic is very slow like this, even when there's nothing to do. I think collectstatic downloads all files to determine their hashes, but need to investigate a bit further.

**Comment by JobDoesburg** [comment]
My preference would be to run collectstatic during the build of the docker I think

**Comment by DeD1rk** [comment]
That's not really possible, as collectstatic is what pushes the files to S3 (that shouldn't happen at build-time)...
Of course it would kind of be possible to give django a kond of fake S3 staticfilesstorage that doesn't really store files, and push the filesystem staticfiles to S3 with the S3 cli/api directly but that's very messy

**Comment by JobDoesburg** [comment]
Yeah I realized that, which is why I deleted that comment haha
