### ISSUE TITLE
[Proposal] remove API v1

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#3227]
### Describe the change
We still have API v1 in the codebase. As far as I know there are no remaining consumers for this API, and as such maintaining it bloats up the codebase with a lot of unnecessary code. Additionally, a lot of tests currently work against API v1, and it would be good to comb through those to move them to v2 if there is no equivalent API v2 test.

### Motivation
Reduce maintenance burden.

### Current implementation
Both API v1 and v2

### Suggested implementation
Only API v2

**Comment by DeD1rk** [comment]
Great idea!
