### ISSUE TITLE
Use easy-thumbnails

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3242]
### Describe the change
I think it would be nice to switch to https://easy-thumbnails.readthedocs.io/en/latest/usage/#.  

### Motivation
It's a lot more popular than django-thumbnails, and I have a feeling it's probably much more mature. It also supports everything we need and more: thumbnail pregeneration can be set up and customized through a signal, and there are loads of customization options to e.g. fallback to an existing size while others are still being generated. 

I think this may help solve https://thalia.sentry.io/issues/4305077187/?project=1463433&query=is%3Aunresolved+issue.category%3Aerror&referrer=issue-stream&statsPeriod=14d&stream_index=2, #3108, #2936 and perhaps even #998.

### Current implementation
We have django-thumbnails, with some hacks to fix it being very slow. It's pretty sad as it's poorly  (not) maintained, throws if thumnbails are requested while they are already being generated, etc.

**Comment by JobDoesburg** [comment]
Now I've seen more about lambdas, I think we should maybe consider thumbnailing with S3 lambdas

**Comment by DeD1rk** [comment]
Yes I would like that a lot, the tricky thing is keeping track of which ones exist (and what to do if a thumbnail doesn't exist yet when trying to serve it), and having a fallback for development.

Considering also themoneybird sync stuff that would be nice to be able to do asynchronously, I think taking another look at celery might also be a good alternative. That's supported reasonably well for thumbnailing and we do have multiple use cases for it.

**Comment by DeD1rk** [comment]
I just tried easy-thumbnails. Like django-thumbnails it suffers from N+1 db access and is not really being maintained. While it's mostly more elegant than django-thumbnails, it doesn't support a cache so performance sucks.

**Comment by JobDoesburg** [comment]
Let's not do this then
