### ISSUE TITLE
Rewrite face detection lambda to invoke_with_response_stream instead of API

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#3287]
### Describe the change
Currently, we expose an API for the AWS lambda callback with face detection results.
This should be removed, and we should simply use the lambda's response_stream to get back the results

### Motivation
Less code, easier infrastructure

### Current implementation
There is an API endpoint and we use some secret values for authentication

### Suggested implementation
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda/client/invoke_with_response_stream.html

**Comment by DeD1rk** [comment]
Doing it like that would require awaiting the results. That's not practical in a request-response cycle (in normal with single pictures) and doesn't make use of lambda's scaling when applied to batch jobs with a cronjob. 
Am I missing some elegant way to await this outside of a request cycle in django?

**Comment by JobDoesburg** [comment]
Hmmm didn't think about it that much... wouldn't multithreaded batch jobs fix the problem?

**Comment by DeD1rk** [comment]
This could be nice if we had celery set up, but otherwise it's not practical having to await.
