### ISSUE TITLE
Collectstatic to S3 is slow

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3290]
### Describe the bug
On every boot, we run collectstatic, which uploads static files to S3. This is very slow as it appears that all/most files are uploaded every time. It would be nice if we can check whether a file has already been uploaded before doing that, to speed up our deployments/reboots.

### How to reproduce
Reboot stating, and observe that booting takes quite a long time.

### Expected behaviour
If few/no static files have changes, collectstatic is quick.

**Comment by DeD1rk** [comment]
While it's definitely not easy to make collectstatic become efficient, we can probably do something simple like setting a flag file in a docker container after running collectstatic once, so that we don't rerun collectstatic on rebooting, but only whenever a new container is created (i.e. after a release or if for some reason a container has to be recreated).

**Comment by DeD1rk** [comment]
We need something like that in order to make #3477 practical.

**Comment by JobDoesburg** [comment]
Wouldn't it be better to just run collect static upon building a container?

**Comment by DeD1rk** [comment]
Can't do that when collecting to S3...
