### ISSUE TITLE
Require data-minimized users to fill in address info again when they re-register.

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3292]
### Describe the bug
There are a number of users whose address info has been minimized, but who do have an active membership. I think that shouldn't be allowed. For these users, an old membership has existed, and a new membership was created some time later.

For example, see https://thalia.nu/admin/auth/user/1668/change/, whose membership had been expired for +- 2 months before creating a new one. 

In these cases, I think somehow we need to make people fill in their info again. 

### How to reproduce
Steps to reproduce the behaviour:
1. Have your membership expire.
2. Wait long enough for data minimization to delete your address info.
3. Create a new membership.

### Expected behaviour
When creating the new membership, you're asked to fill in the minimized fields again.

**Comment by DeD1rk** [comment]
#3478 solves this for the most common cases. I think there should currently be some text telling users this applies to that they need to contact the secretary. But we need to check that that is indeed the case (and maybe unittest it).

**Comment by DeD1rk** [comment]
We should at least just raise in `registrations.services.accept/complete_renewal` if the member.profile is minimized. Optionally we can also check that in the frontend before allowing people to create a renewal.

**Comment by DeD1rk** [comment]
TODO:
- [ ] Profile dataminimization should not minimize profiles of users who have a renewal open (not rejected and not completed).
- [ ] If you're minimized, when trying to make a renewal, you need to enter both the normal stuff, as well as all the profile fields that we really need. When saving (i.e. creating the renewal), the profile information is directly saved to the minimized profile.
This way, we don't add db fields to renewals, and don't have the problem where if someone fills in data again, it's wiped quickly by dataminimization that same night.

**Comment by T8902** [comment]
Instead, change edit profile page and don't let the renewal page show when someone's data is minimized so they can edit their profile and redirect them back to renew once they fixed their profile
