### ISSUE TITLE
Moneybird synchronization error: InvalidData("API error 422: {'sepa_mandate_date': ['cannot be today or in the future']}")

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3295]
https://thalia.sentry.io/issues/4111947935/events/ce4b0f82c04244b58c9864ce6bceb729/?project=1463433

**Comment by DeD1rk** [comment]
I'm not sure why moneybird doesn't accept today/future mandates. But I guess the best solution would be to postpone synchronizing the mandates for these users to be done at night after the mandate date. 

I'm not sure what that means for e.g. the pushing of their tpay payment for their registrations. I think there wouldn't be any problem doing that _on the mandate date_ despite moneybird not knowing about their mandate yet?

@JobDoesburg do you know more about this?

**Comment by JobDoesburg** [comment]
I'm not surprised about not accepting the future, but today should be acceptable I think. But apparently not...

I would indeed just wait a day, we need to rewrite everything to cronjobs anyhow
