### ISSUE TITLE
Canceled event registrations are marked as queued

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#3315]
### Describe the bug
After canceling a registration, 

### How to reproduce
Steps to reproduce the behaviour:
1. Go to https://staging.thalia.nu/api/v2/admin/events/183/registrations/?limit=999999999&ordering=-date_cancelled&cancelled=true&queued=true
2. Go to https://staging.thalia.nu/api/v2/admin/events/183/registrations/?limit=999999999&ordering=-date_cancelled&cancelled=true&queued=false
3. Notice that the canceled registrations are only listed under `queued=true`, and that the queue position is 3
4. Go to https://staging.thalia.nu/api/v2/admin/events/183/registrations/?limit=999999999&ordering=-date_cancelled&cancelled=false&queued=true
5. Notice that the queued position 3 already exists.

### Expected behaviour
Canceled registrations should show up as canceled and not in queue, as they are not in the queue

### Additional context
I think the reason they are listed as queued is because the queue position is set. Ideally this field would be nulled or set to a special value like -1.

**Comment by JAicewizard** [comment]
(It is possible I used the wrong method to cancel a registration, but there is no proper way to do so)

**Comment by DeD1rk** [comment]
A fix for the app is to just ignore (not filter on) queued.
I agree the queue_position should be nulled for cancelled registrations.

Some condition will need to be added to https://github.com/svthalia/concrexit/blob/fff987458865d636f023877fe43c2624435f1bf2/website/events/models/event_registration.py#L117
