### ISSUE TITLE
Automatically add events that open to newsletter

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/concrexit#3317]
### Is your feature request related to a problem? Please describe.
In the newsletter below the introduction, there is usually a list of events which registrations open that week. This has to be done manually, which is quite a lot of work.

### Describe the solution you'd like
Ideally the website would generate the list on its own and add it too the newsletter.

### Motivation
I'm lazy :)

**Comment by DeD1rk** [comment]
> I'm lazy :)

Go build it then ;p
