### ISSUE TITLE
Payments race condition

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3367]
### Describe the bug
In some cases it's possible to create a payment multiple times for one payable. This is mainly a problem for Thalia Pay payments, as there it might cause people to actually be charged incorrectly, instead of only being a pain for the treasurer.

### How to reproduce
Steps to reproduce the behaviour:
1. Send multiple API calls to create payments.
2. One will be accepted.
3. Most others are rejected.
4. But sometimes, multiple are accepted, and later ones get the payable.payment ForeignKey, unlinking the previously accepted payment.

### Expected behaviour
Only 1 payment is created.

A first mitigation would be to put `create_payment` in a transaction, and roll back if, between saving a payment and saving the payment FK to the payable, the payable got a new payment linked.

A more complete solution would be to use #2126. That could allow setting a database constraint that disallows multiple payments linked to a single payable. Then it's really impossible for a race condition to occur. Without it, I think there will always be some delay between checking that no payment exists, and committing the transaction that creates one.

**Comment by JobDoesburg** [comment]
I'm in favor of the first mitigation!

But maybe if that doesn't work, we could set a cache value that payment is already happening and check that.

**Comment by DeD1rk** [comment]
@JobDoesburg Actually I see now that there's also `select_for_update`, which we can use to lock the payable.model while creating payments. That should be perfect, although it is ignored on sqlite3
