### ISSUE TITLE
Opt-out from alumni newsletter not possible without filling in many account details

### ISSUE THREAD

**Issue by ricotewechel** [svthalia/concrexit#3378]
### Describe the bug
To opt-out from alumni emails, you need to deselect a checkbox on your profile settings. In order to do this, you need to save all forms as a whole, which requires you to not leave certain fields empty. This causes unwanted behaviour for alumni, whose data has been minimalized: They only have a mail address and a name.

### How to reproduce
Steps to reproduce the behaviour:
- Start from 'empty account' 
- Add mail address and Name
- Forgot password button
- Reset password
- Login
- Try to opt-out from alumni mails. 

### Expected behaviour
We want alumni to easily deregister from the alumni newsletter. Currently, they cannot do that without filling in all sorts of irrelevant details.

### Additional context
This issue might be related to deeper concerns and also be relevant for other use cases, such as the regular newsletter and the Thabloid, but I'm not sure of that.

**Comment by DeD1rk** [comment]
A simple option would be to just add a seperate form for email (and maybe some other) preferences, that validates independently of the rest of the profile fields. 
It would have to be easy to find with:
- Showing up in the user menu dropdown if(f) your data has been minimized.
- Perhaps a redirect from the normal edit profile view to the new one for dataminimized users.

This is somewhat related to #3292.
