### ISSUE TITLE
Incorrect rotation on profile photos

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/concrexit#3408]
### Describe the bug
In our board page Widad's photo is rotated 90 degrees, while on their profile it is correct.

**Comment by DeD1rk** [comment]
Sounds like EXIF rotation (EXIF data being stripped by thumbnailing, this is handled explicitly for albums but not other kinds of photos). This will be resolved by #3324 which will hopefully be released in 4/5-ish weeks.

If you'd like a temporary workaround, you can download it, remove the EXIF rotation manually somehow, and upload it again.
