### ISSUE TITLE
View group memberships in user admin

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3436]
### What?
Show a (initially collapsed) inline of (current or all?) group memberships in the user admin.

### Why?
It's currently quite not really streamlined to find someone's group memberships. For example, you can't search by username or pk in the groupmemberships admin list. 

### How?
Add an inline (readonly). And maybe tweak the search fields in the groupmemberships admin as well.

**Comment by ColonelPhantom** [comment]
A bug in Django makes this impossible; I reported the bug and it has been fixed since. But we'll need to wait for a release that includes it.

**Comment by DeD1rk** [comment]
@ColonelPhantom that fix has finally at least ended up in a tag 2 weeks ago: https://github.com/django/django/releases/tag/5.1a1

So hopefully maybe finally in 5.1?
