### ISSUE TITLE
Private events

### ISSUE THREAD

**Issue by mark-boute** [svthalia/concrexit#3447]
### What?
For some use cases, i.e. using Thalia Pay for intro mentors their intro-fee, it could be very useful to be able to have private events, to which administrators can add members. Once these members are added they should see the event and be able to forinstance use Thalia Pay.

### Why?
As a private Event organizer I want my participants to be able to pay using Thalia Pay
As a private Event participant I want to be able to use Thalia Pay to pay instead of having to pay an invoice

The Introduction fee for mentors was paid for using invoices, some mentors forget to pay this, and it is extra work for the treasurer.
This method could also be used for the Study Trip, or any private event organized through Thalia's finance.

### How?
Add a field, `private` to the event model.
The object manager should change to not show private events to members that are not registered for that event.

**Comment by DeD1rk** [comment]
It feels to me like this would only be a shortcut for making invoices? Then what is the purpose of still naming an event? I expect that would likely be abused...

For the listed usecases, I think there are probably more elegant solutions we can think of, that don't further complicate the events/registrations logic.

**Comment by JobDoesburg** [comment]
The use case you describe doesn't need private events. Thalia Pay works without an event as well, admins with the correct permissions can create a Thalia Pay payment manually without a payable linked.

**Comment by mark-boute** [comment]
Will take a different approach

**Comment by mark-boute** [comment]
Will take a different approach
