### ISSUE TITLE
`make fixtures` can generate duplicate photos in an album

### ISSUE THREAD

**Issue by movieminer** [svthalia/concrexit#3463]
### Describe the bug
When running `make fixtures`, there is a possibility that duplicate photos get generated in one photo album.

### How to reproduce
1. run `make fixtures`
2. Get lucky that it tries to generate a duplicate photo

### Expected behaviour
`make fixtures` does not return an error sometimes

### Additional context
```
django.core.exceptions.ValidationError: {'file': ['This photo already exists in this album.']}
make: *** [Makefile:196: fixtures] Error 1
```

**Comment by DeD1rk** [comment]
Closed by 96428b13
