### ISSUE TITLE
Add email to groups API

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#3487]
### What?
The app would like the API response for groups to return their email

### Why?
this was requested by jord, and makes sense. You could directly mail a committee by clicking on the link in the app

### How?
Not a clue

**Comment by DeD1rk** [comment]
@JAicewizard  
<img width="495" alt="afbeelding" src="https://github.com/svthalia/concrexit/assets/41264528/21ece32e-4269-439a-8e93-06859c9039e5">

**Comment by JAicewizard** [comment]
Ah I scanned swagger for email, thanks for highlighting this
