### ISSUE TITLE
Separate organizers from participants

### ISSUE THREAD

**Issue by Sophie2104** [svthalia/concrexit#3491]
### What?
I would like to be able to easily put the organisers of an event at the top (maybe even a different section), even though there are already registrations.  

### Why?
Because it should be more clear who the organisers of an event are.

### How?
Maybe a seperate section at the top with organisers.

**Comment by DeD1rk** [comment]
I personally think this is probably an unnecessary complication of the registrations. There isn't always a clear distinction between people participating in an event and people organising it. And we do already indicate which committee is organising. 
So I don't really see much added value in this, and fear it could end up making both the UX and our code worse. But I'd love to hear what others think about this?

**Comment by JobDoesburg** [comment]
> I personally think this is probably an unnecessary complication of the registrations

I agree. At least, there should **not** be a second EventRegistration model. 

### Assuming we would want to do this:
You could argue you might want to have some additional text field on the EventRegistration indicating some sort of _"role"_ in the event (which you could use for 'organization' or 'bhv' or 'team name'). That would be a reasonably generalized solution. 

(Then, what to do with double functions, if someone is both organizing and in a team...?)


The challenge would then be to create a UI that works.
My personal approach would be to give events yet another boolean field `use_event_registration_roles`, which enables this UI.
In the participant list, this would then group the event registrations based on their role.


### But might be feature creep still...
The real question is:

> Because it should be more clear who the organisers of an event are

Why?
