### ISSUE TITLE
Displayed registration message in backend incorrect

### ISSUE THREAD

**Issue by W-M-T** [svthalia/concrexit#3514]
### Describe the bug
When you have an event for which you fill in the field "registration message" (i.e. "Message when there is no registration:"), the backend doesn't show the non-default value that you enter on page https://thalia.nu/admin/events/event/[id]/details/, but shows the default value instead ("No registration required").
Viewing it on the site does correctly show the non-default value (i.e. https://thalia.nu/events/[event-slug])

### How to reproduce
1. Go to https://thalia.nu/admin/events/event/[id]/change/
2. Under "Registrations", fill in anything under "Message when there is no registration:"
3. Go to https://thalia.nu/admin/events/event/[id]/details/

### Expected behaviour
"Registration message" would show the non-default value

**Comment by DeD1rk** [comment]
I found #3515 while working on this. That's a little bit more work though.
