### ISSUE TITLE
Make sure to put Quinten in queue position 3

### ISSUE THREAD

**Issue by NotAtec** [svthalia/concrexit#3521]
### What?

Quinten Cabo shall be placed at queue position three whenever he signs up for an event. Even if the event has optional registration.

### Why?

Just because. Please refer to the talk given at Thalia Talks 2023.

### How?

Honestly just figure it out based on user id or smth

**Comment by Scarletto** [comment]
Vo

**Comment by JAicewizard** [comment]
> Vo

Rt

**Comment by tintin10q** [comment]
[human_rights_UN.pdf](https://github.com/svthalia/concrexit/files/13661632/human_rights_UN.pdf)
