### ISSUE TITLE
Enable registration button when it opens using a timer

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#3522]
### What?
Currently, the registration button only appears on a page refresh. When registrations open this causes a big storm of users who all refresh this page to get the button.

Using client side scripting to make the button appear we prevent these refreshes.

### Why?
Reduces server loads and prevents API-based gaming of registrations 

### How?
We would need some conditional javascript that can make the button appear on a timer. We should also add the required information for this to the API so that the app can do the same live view update.

**Comment by DeD1rk** [comment]
We should embed either a 'can-register-at' time or 'can-register-when-open' bool on the page that's used by JS, and do the same in the API. 
The template should still give a good default (initially show and hide the button correctly) such that it's possible to register normally with JS disabled
