### ISSUE TITLE
empty cancelations table looks bad

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#3523]
### Describe the bug
![screenshot-2023-12-13-102149](https://github.com/svthalia/concrexit/assets/19241481/052c15b4-e549-4579-922a-a4c581a79c48)

### How to reproduce
go to the admin of an event without cancelations

### Expected behaviour
it should look like the empty table of registrations

**Comment by DeD1rk** [comment]
I can't reproduce on prod and staging. Do you have a specific event and browser?

**Comment by JAicewizard** [comment]
Hmm, I can also no longer reproduce it, screenshot is proof it did happen but I cannot find any event that has this anymore. (shouldve linked the page...)

**Comment by DeD1rk** [comment]
Yeah I recall it from long ago too, but probably it's just been solved by a dependency update or the browser cache expiring

**Comment by JAicewizard** [comment]
I have it again locally, on a basically empty event

**Comment by DeD1rk** [comment]
On origin/master? Can you maybe dumpdb so we can exactly reproduce?

**Comment by JAicewizard** [comment]
[db.sqlite3.gz](https://github.com/svthalia/concrexit/files/13760391/db.sqlite3.gz)

**Comment by JAicewizard** [comment]
nice round of fixes!
