### ISSUE TITLE
On the OAUTH page (https://thalia.nu/user/oauth/authorised-apps/) add when access was granted

### ISSUE THREAD

**Issue by tintin10q** [svthalia/concrexit#3527]
### What?

On the [Oauth authorized applications page](https://thalia.nu/user/oauth/authorised-apps/) add when the access was granted. 

### Why?

I had apparently granted access to the thalia app like 6 times but I did not know which one to remove because I did not know what the newest one was.  

### How?

In the [authorized_tokens.html](https://github.com/svthalia/concrexit/blob/master/website/templates/oauth2_provider/authorized-tokens.html) add when the token is granted? Hopefully this is already part of the `token` objects in `applications`. However, there is a comment in this file that this is an automatically generated file so maybe you don't actually want to edit this file.

**Comment by DeD1rk** [comment]
Duplicate of #3100.
