### ISSUE TITLE
Changing ASML logos

### ISSUE THREAD

**Issue by FemkeMarijnissen** [svthalia/concrexit#3581]
### What?
ASML requested we temporarily change their logos on the site and the app. Their message: Vanwege het 40 jarige bestaan van ASML heeft ASML dit jaar een (tijdelijk) nieuw logo. Mijn vraag aan jullie is om vanaf nu dit logo te gebruiken waar een ASML logo wordt geplaatst, en op huidige promo en banners het logo te updaten.

### Why?
ASML has a sponsorship contract

[asml_logo_2024.zip](https://github.com/svthalia/concrexit/files/14127729/asml_logo_2024.zip)

**Comment by DeD1rk** [comment]
Dit kan je (of soppie) gelukkig makkelijk aanpassen vanaf de admin :) 

https://thalia.nu/admin/partners/partner/11/change/

Ik zie dat ASML nu trouwens niet actief is als partner, klopt dat? Dan heeft het weinig zin om ze te veranderen als ze toch nooit getoond worden

**Comment by DeD1rk** [comment]
Ofja ik zie het, dat klopt niet. Is het een nieuw contract of gaat er iets mis?
