### ISSUE TITLE
Moneybird invoice with no-longer-existing payable

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3587]
### Describe the bug
There are some invoices whose payable object no longer exists, but do `need_synchronization`.  We need to figure out what to do with that. It shouldn't normally happen (and doesn't happen frequently) but it would be nice if we can either handle it somehow or make it impossible.

### How to reproduce

1. ???

### Expected behaviour
???

### Additional context
This caused https://thalia.sentry.io/issues/4937025315/.
There is currently one case: invoice 3719, which was for a minimized renewal.

**Comment by T8902** [comment]
> So I guess this can be reproduced by minimizing an outstanding renewal, or something like that?

If that is the case, it should be fixed with this pull request #3571 since minimizing outstanding renewals becomes impossible
