### ISSUE TITLE
Change bookstore links

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3599]
### What?

From the 4th quarter on we will switch to another bookstore, intertaal (https://intertaal.nl/). Can you change this on the site? I am probably missing some information, but that is a work in progress. Once I have more information for on the website, I will let you know. 

~ soppie

**Comment by NotAtec** [comment]
So, looking at that link it seems to be a language books store?
Is there a different link we'll need for studybooks?

**Comment by Sophie2104** [comment]
I asked again for a link and maybe more info for our site. Will let you know asap.
