### ISSUE TITLE
Not possible to deregister if registered by someone else

### ISSUE THREAD

**Issue by W-M-T** [svthalia/concrexit#3602]
### Describe the bug
When you've been registered for an event by somebody else through the backend, trying to deregister yourself gives an error.

### How to reproduce
1. User with rights goes to https://thalia.nu/admin/events/eventregistration/add/ and adds a user registration to an event
2. Other user that was registered goes to https://thalia.nu/events/event-url, presses "cancel registration"
3. 500 internal server error

(Similar behaviour in the app)

### Expected behaviour
Should either allow the deregistration to happen, or fail gracefully, depending on intended behaviour.

### Additional context
Registering someone else via the backend is pretty common as a way to guarantee the people involved in organising an event a spot without them all having to individually register themselves. Them not being able to deregister doesn't seem intended though.

**Comment by DeD1rk** [comment]
I tried to reproduce it on staging but that didn't work: when making a registration from the admin for an event with mandatory registrations I could successfully cancel both before and after the deadline.

I did spot the case from yesterday in the nginx container logs, but only as a few single lines with the url and 500 status code; strangely there's no other information like a stacktrace from the django container.


There would have to be a bug somewhere in this (maybe from #3500 ?): https://github.com/svthalia/concrexit/blob/7de651481a4ed39d0cab1d2181ffaff85acdd659/website/events/services.py#L339-L353

But that doesn't explain it not showing up on sentry and the logs.

**Comment by W-M-T** [comment]
There were people in the waiting list during these deregistration attempts, though I would expect that people would've run into this bug before already if the only conditions were "registered by someone else through the backend, try to deregister while there's someone in the waiting list".

**Comment by DeD1rk** [comment]
That's indeed from #3500. I'm guessing sentry doesn't always catch exceptions raised within signal handlers, despite the exceptions bubbling up as you would expect.

**Comment by DeD1rk** [comment]
Indeed solved by https://github.com/svthalia/concrexit/commit/e84bb99fee23bbbdf436f6ed1c2037e5f53ff2e2
