### ISSUE TITLE
Add checkbox for receiving thabloid on the RegistrationForm

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3613]
### What?
We should make a checkbox where people can decide whether they want to receive the Thabloid physically, when registering. The checkbox should be checked by default, and have some text (that Thabloidcie can provide) describing what the Thabloid is.

### Why?

This may help reduce the number of wasted Thabloid prints, for sustainability and to save some money.

### How?
Add a checkbox to the form and make it be saved somehow.

**Comment by nadiand** [comment]
Hi, this is Nadia! We'd like the text to be as follows:

The Thabloid is a small quarterly booklet containing fun, interesting and captivating articles, as well as puzzles and interviews of our lovely Thalia board. Each time a new Thabloid is produced, you will receive a booklet for free, unless you decide to opt-out. Every final version of the Thabloid will also appear on the website, so you can read it at your convenience at any time.

I hope this is not too long? Let me know if it should be changed :) And thanks for doing this!!
