### ISSUE TITLE
Reschedule information check email

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3614]
### What?
Let's send the information check email sometime in februari, instead of august.

### Why?
In the holiday, people will often not read it. @WidadMajdoubi24 and I expect it to be more effective throughout the lecture year.

### How?
Just change a date in settings.py, and check if some of the contents of the email should change.
Also, maybe add a note that people may also like to review their settings (such as receiving thabloid on paper).

**Comment by Luukosaurus** [comment]
It might be a problem that it won't sent one for over 1,5 years because it skips this years.
