### ISSUE TITLE
Rate limit queue emails

### ISSUE THREAD

**Issue by T8902** [svthalia/concrexit#3621]
### What?

When organizers are messing with the sign in order to give certain people prioritised access to an event, the number 1 in queue can get unlimited amounts of emails. Maybe have a rate limit or a timer of how many emails and maybe have a heads-up that you are not in the event anymore or something not sure how this would look.
### Why?

Because getting 30 emails about being in an event and then not being in there is really annoying.
### How?

Possibly timer or rate limit on amount of these emails send to one person or something I'm not sure how this could look.

**Comment by DeD1rk** [comment]
Solved by https://github.com/svthalia/concrexit/commit/e84bb99fee23bbbdf436f6ed1c2037e5f53ff2e2, this happens when the cancellation crashes inbetween sending email and trying to send the pushnotification, before saving the cancellation.
