### ISSUE TITLE
"Live" Registration doesn't work

### ISSUE THREAD

**Issue by NotAtec** [svthalia/concrexit#3628]
### Describe the bug

The timer countdown from #3522 / #3565 before the registration button becomes available on the website doesn't enable the registration button when the timer hits zero, but the counter goes into the negative.
### How to reproduce

1. Go to any event with a countdown timer before registration opens
2. Wait for timer to hit zero, and continue counting down

### Expected behaviour 

Timer should dissapear and the registration button shouldn't be greyed out anymore so it can be used.
### Screenshots

Example from the thalia weekend sign-ups:
![Screenshot_of_website](https://github.com/svthalia/concrexit/assets/28996638/2fe72904-af0c-496a-bd1d-91b44bf99120)

**Comment by ColonelPhantom** [comment]
@DeD1rk why is this labeled optimization? 

Anyway, I tried this on Chrome Android but couldn't reproduce. @NotAtec, if you have any idea what circumstances cause this issue, that would be great.

**Comment by DeD1rk** [comment]
@ColonelPhantom by oopsie I guess. I did see this happen for multiple people. I'll try if I can reproduce myself once I have a bit of time. I've seen it on a desktop browser as well, so it wasn't just android chrome

**Comment by DeD1rk** [comment]
I just tried and also couldn't reproduce on macos+firefox with a 2 minute wait. Maybe the timeout gets cancelled somehow
