### ISSUE TITLE
2FA numeric and autocomplete

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#3633]
### What?
Make the 2FA TOTP field a

```html
<input
  type="text"
  name="token"
  id="token"
  inputmode="numeric"
  pattern="[0-9]*"
  autocomplete="one-time-code"
/>
```

### Why?
Hint browsers to display numeric 0-9 input mode, and autocomplete TOTPs (e.g. when using bitwarden)

### How?
HTML ✨

**Comment by DeD1rk** [comment]
Actually only the inputmode is not already set, but e.g. ios+webkit picks the numpad just fine based on the pattern

**Comment by DeD1rk** [comment]
Any example of browsers/password managers that don't correctly discover the field?

**Comment by JobDoesburg** [comment]
> Any example of browsers/password managers that don't correctly discover the field?

Bitwarden on iOS 17.4 safari
