### ISSUE TITLE
"You are rate limited"

### ISSUE THREAD

**Issue by W-M-T** [svthalia/concrexit#3640]
### Describe the bug
Not sure if this issue is unique to me, but after logging in, I get a singular message of "You are rate limited" instead of any page.

### How to reproduce
1. Go to https://thalia.nu/user/account/login/
2. Enter credentials, log in
3. Get shown "You are rate limited"

### Expected behaviour
See the website after logging in

**Comment by W-M-T** [comment]
Not sure what the cause of this was, but it seems to be over now.

**Comment by DeD1rk** [comment]
Someone probably failed to log in many times (30/hour I'm guessing without consulting the source code) either from your IP or using your username. It's an intentional rate limit to prevent online brute force attempts against your password.

**Comment by DeD1rk** [comment]
Or you made a really large number of requests yourself if it wasn't at login and persisted on other pages

**Comment by W-M-T** [comment]
This happened on my first interaction with the thalia website of the day, me navigating to the login as a redirect from the edit-profile link in today's email about thabloid preferences, and I'm the only user on my network, so I'd be suprised if it was because of a large amount of requests on my side.
I'd be interested to know what the cause of it was since the other explanation also sounds kind of odd to me (I don't see why someone else would try to log in as me?), but I also understand if it's not a priority.

**Comment by DeD1rk** [comment]
Hmmm yeah I would love to know precisely what the reason was, but I'm afraid the ratelimit cache that determines expires an hour after each request so we can't look it up
