### ISSUE TITLE
Display queue length when not in queue.

### ISSUE THREAD

**Issue by Maikel-J** [svthalia/concrexit#3644]
### What?
I would like to be able to see the length of the queue of an event, without having to be in the queue myself.

### Why?
I want to be able to see how long the queue for an event is when I am already registered (but not in the queue).

### How?
Display it next to the number of registrations

**Comment by DeD1rk** [comment]
This is definitely possible, but I wonder, why? Organisers can already view the queue...

**Comment by DeD1rk** [comment]
Ties says: Implementing this on the website is fine, however also including this in the app is not worth the effort. If this is enough then we will implement is otherwise we will just close the issue.

**Comment by T8902** [comment]
@Maikel-J Bump for reaction otherwise I will close this issue
