### ISSUE TITLE
Add specifications for promo requests

### ISSUE THREAD

**Issue by lisaaalbrecht** [svthalia/concrexit#3672]
### What?

The promocie wants to add small explanations to the channels that can be requested and a line of text at the top that says: 
"Only request promo if you want the Promocie to make it"

### Why?

Because the promotion requests list sometimes gets filled with promo that we don't have to make or with requests that costs us a lot of time but are not really needed. Also because we want to only use Instagram post for mostly company ads so they are clearly visible on the page and don't get lost between events post.

### How?

![image](https://github.com/svthalia/concrexit/assets/157694842/e24cb295-3292-45a2-8a22-f278c12dd5c9)
The small explanations should state which ones are mostly used for events and which ones are only for company advertisement or really big events. This prevents people from requesting a lot of big promo for a relatively small event and keeps the Thalia Instagram clean.
So I would say maybe add something like 'used for most events' right next to the whatsapp and Instagram story channel. And then something like 'used for big events or company ads' next to poster/instagram post/mercator screen. 
I don't exactly know how so design is up to you, but if you want my input you can text me(Lisa).

**Comment by T8902** [comment]
For the problem of promo requests being cluttered with non-promocie requests we could maybe make a boolean field "for promocie" which seems kind of unnecessary since the promo requests are meant for promocie promo requests, and for the explanation per type of promo request I don't see an elegant solution personally do you have ideas @DeD1rk

**Comment by T8902** [comment]
> I think getting unnecesary requests is a policy problem, not something to solve in code. IMHO it should be up to promocie to discuss with the requester if they think it shouldn't be a request. Adding a 'rejected' status seems more useful to me.
> 
> Regarding the channel descriptions, I have a very elegant solution. Since you want descriptions that show up in the dropdown, just change the channel names to include the description ;)

The channel descriptions in the name as in WhatsApp (company events) or something?
Does rejecting requests really solve the problem though? I agree that it should just be a policy thing, not a website thing and board/promocie should just get angry at people for misusing the promo requests. The only thing we could do is put a warning above "promo request 1" that it should only be used if you want people of promocie to make the promo but again not sure if that will work and it will look more cluttered.

**Comment by DeD1rk** [comment]
> The channel descriptions in the name as in WhatsApp (company events) or something?

Exactly, that requires no code changes and I think achieves exactly what Lisa asked.

I think being able to reject requests solves the thing where promocie simply does not fulfill a request, without communicating this to the requester, or internally removing it from the list.
Through a rejected status, it becomes possible to clean up stuff promocie does not intend to work on, while also communicating this to the requester.

I think that would really help a lot with managing the clutter. It's very similar to closing or labelling issues on github.

**Comment by DeD1rk** [comment]
If you'd like a rejected status or something like it, please let us know, we can do it in a new issue
