### ISSUE TITLE
Warning about costs in newsletter not accurate

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/concrexit#3681]
When adding an event to the newsletter and checking the "Show warnings about costs", it will say "registration deadline = unregistration deadline". This does not have to be true as the cancellation deadline can be set to something different than when the registrations close, and it often does. 

So, it should be changed to something like "Attention: when deregistering after the cancellation deadline Thalia will recover the costs on you. These costs are: €X.XX."

**Comment by DeD1rk** [comment]
While this is not unintended behaviour (it shows up based on the button, not based on incorrect criteria) I agree it makes sense to make the message more generic so it can be used correctly for events with all deadlines. It can easily be updated here: https://github.com/svthalia/concrexit/blob/6c7b1b3b11ddc4f99375e1d1d20087f5e7043044/website/newsletters/templates/newsletters/email.html#L100
