### ISSUE TITLE
Boolean flag as attachment filename

### ISSUE THREAD

**Issue by marcopus** [svthalia/concrexit#3699]
In the content disposition header, the attachment should probably be outside curly braces, or the variable between curly braces should be the name of the file:

https://github.com/svthalia/concrexit/blob/a69196bdbfdd7dda68500628ef8ed258f8d20262/website/thaliawebsite/storage/backend.py#L63-L65

@DeD1rk

**Comment by DeD1rk** [comment]
@marcopus that's right, we should probably have typehinted it as `False | str` or smth
