### ISSUE TITLE
Add a total money sum for Food Events revenue

### ISSUE THREAD

**Issue by BigRoelof** [svthalia/concrexit#3724]
### What?
I want to have a quick and easy way to see the total amount of revenue that has been generated through food orders that are made during an event.

### Why?
This makes it easier for the treasurer to check whether the costs of the Professor invoices somewhat coincide with the revenue that was made. Most ideally I would like to see this total amount split up in an amount that was paid for by card, and an amount that was paid for through TPay. This is already implemented for sales that are made during borrel shifts.

### How?
All the amounts are already there. Now when I need to check these costs I just dump them into an excel sheet and calculate in manually, but I hope Technicie can do some coding hocus pocus to make the treasurer life a bit easier <3

### Bonus quest
I think this is a quick and easy one: Could the VAT for every food order made be put to 0% (no VAT)? Currently it's on 21% and this is also something I have to change manually every time the orders are made, since we cannot declare VAT on this kind of product. I already changed for the past food orders so no need to delete and push those again (for now), but if this can be implemented for orders in the future that would be great.

**Comment by DeD1rk** [comment]
@BigRoelof <img width="685" alt="afbeelding" src="https://github.com/svthalia/concrexit/assets/41264528/64089e78-1c9c-464d-a291-f79e496a8041">

<img width="455" alt="afbeelding" src="https://github.com/svthalia/concrexit/assets/41264528/174e0828-1c36-400d-982f-abca04dd38ab">

Isn't this exactly what you mean? A bit hidden but this has been there for a long time

**Comment by DeD1rk** [comment]
I moved your bonus request to #3750 to keep the issue tracker clean. That's indeed a very simple one. If the total money count is not actually implemented already, feel free to reopen
