### ISSUE TITLE
Where is the chair banner ????

### ISSUE THREAD

**Issue by Baublesaurus** [svthalia/concrexit#3727]
### Describe the bug
When looking at the committees, I can see no chair banner. 

### How to reproduce
Ask Ties, or Cato, but she might have forgotten

### Expected behaviour
I want to see a chair banner 

### Screenshots
![image](https://github.com/svthalia/concrexit/assets/82397984/158452af-0537-458a-aed6-5945a8156946)

### Additional context
A chair banner is really central for the functioning of the website, so please give it high priority

**Comment by Baublesaurus** [comment]
This should receive higher priority!!

**Comment by Jorritboer** [comment]
I agree with @Baublesaurus , this frankly makes the site unusable for me and I think this should be hotfixed asap.

**Comment by ColonelPhantom** [comment]
The chair banner seems to work for me on localhost, as well for e.g. the board, as well as the Technicie and the Educacie.

As such I am inclined to believe this is an error in the provided data, and the affected committees do not have a chair indicated in the database.

This is the problem of those responsible for entering this (maybe intern? not sure tbh), and not us. This is something that should be fixed via /admin/.

Feel free to reopen if you believe this is an issue on our side after all!

Additionally, maybe the presence of a chair is something we could potentially validate, but I'm not sure that's ideal either.

**Comment by ColonelPhantom** [comment]
I have been informed that it can disappear in some edge cases, e.g. zooming in really far.
