### ISSUE TITLE
https://staging.thalia.nu/api/docs is broken

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#3745]
### Describe the bug
Parser error on line 5088
unknown tag !<tag:yaml.org,2002:python/object/apply:decimal.Decimal>

### How to reproduce

1. Go to https://staging.thalia.nu/api/docs

### Expected behaviour
It should show the V2 API, it does not

**Comment by DeD1rk** [comment]
This comes from 17ebc7b78ee6e26b2f07c938c2ffc11521463de4, which solved a warning. But apparently is itself unsupported. So I'm not sure what the correct thing to do is. We'll need to look into the DRF docs and check.
