### ISSUE TITLE
board slug API returns 500

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#3755]
### Describe the bug
it returns a 500

### How to reproduce
1. Go to https://thalia.nu/api/v2/activemembers/boards/2023-2024/
2. See error

### Expected behaviour
It should return a board

**Comment by JAicewizard** [comment]
This actually seems to work on staging, was this a known bug? if so ill close it

**Comment by DeD1rk** [comment]
This is #3756
