### ISSUE TITLE
"Renew membership" notification even after renewing/extending membership and still being member

### ISSUE THREAD

**Issue by baszn** [svthalia/concrexit#3776]
### Describe the bug
After renewal from normal membership (which is until 1 september 2024) to benefactor (from 1 sept. 2024 until 1 sept. 2025) successfully I know get the banner that I'm not a member anymore and need to renew.

Almost all (member specific) parts of the website seem to work, except viewing other peoples profiles which result in a '403: Premission denied' error.

### How to reproduce
1. Renew your Thalia membership while still Thalia member for the next year from member to benefactor
2.  Go through the registration process just fine and get a 'Renewal successful" mail
3. See the banner "You're currently not a member of Thalia. [Renew your membership](https://thalia.nu/user/membership/) to get access to all parts of the website." appear on top of the website
4. Get 403 errors when clicking on a members profile

### Expected behaviour
To be seen as a member of Thalia until 1 sept. 2024 and as benefactor the year after.

### Screenshots

![image](https://github.com/user-attachments/assets/cc75769d-624b-4775-9011-eb83d99640dd)

![image](https://github.com/user-attachments/assets/d96f5cda-4c42-418b-bfe1-ded7a273dc2e)

**Comment by DeD1rk** [comment]
I see the issue, will fix it asap. Thanks for finding it just in time for intro 😅
