### ISSUE TITLE
Prices of 'Order Food' not visible when the name of the food is to long.

### ISSUE THREAD

**Issue by BPC2004** [svthalia/concrexit#3788]
### Describe the bug
In the Thalia App when ordering food if the name of the food is to long the price is not visible. To be able to see the food you first have to order the food.

### How to reproduce

1. Go to 'Borrel'
3. Click on 'Order Food'
4. Scroll down food that has a long name
5. See the name of the food and then ... and the price will not be visible.

### Expected behaviour
There should be a way to see the price of the food no matter how long the name of the food is.

### Screenshots
![Screenshot_20240904_131512_ThaliApp](https://github.com/user-attachments/assets/c90b3968-2f65-4e64-abd2-bbd6407720bb)

**Comment by ColonelPhantom** [comment]
This is a Reaxit issue, not Concrexit. Additionally, I believe the latest update fixed this? @JAicewizard

**Comment by JAicewizard** [comment]
This should be partially fixed in the latest release, some very long names are still hidden. This can be fixed but it will take a bit longer as it needs a redesign. Feel free to open an issue at https://github.com/svthalia/reaxit/issues
