### ISSUE TITLE
Old benefactors not able to renew or register as members

### ISSUE THREAD

**Issue by RickJoosten26** [svthalia/concrexit#3789]
### Describe the bug
There was a person that used to be a benefactor and then did not renew but now started studying and was eligible to become a Thalia member could not register to be a member. Neither could she renew her benefactorship. Therefore we had to manually put in her membership in the users page.

### How to reproduce

Basically find a user that used to be a benefactor, does not have this benefactorship anymore and then try to register as a member or renew the benefactorship. I think that will be sufficient to reproduce this.

### Expected behaviour
Nothing should happen. It should not be possible to either register or renew. I don't know for sure whether this gives an error because I can not reproduce this myself.

**Comment by RickJoosten26** [comment]
Pretty niche issue but Ties wanted me to report :)

**Comment by T8902** [comment]
Should be fixed if the profile is completed I think since there is missing mandatory pieces of the profile
