### ISSUE TITLE
Societies permission to use Thadmin shifts

### ISSUE THREAD

**Issue by WrvanOuwerkerk** [svthalia/concrexit#3797]
### What?
Give societies (or if possible only the chair of the society) the permission to make and manage shifts

### Why?
If societies have an open event and they decide to sell products from Tartarus they do not have permission to make a shift or access Thadmin at all. Even when the society gets added as a manager of the shift, they do not have permission.

I say chairs specifically because the average member of a society has less of an idea about how it works than the average committee member.

### How?
Change permission of (the chair of) societies to access Thadmin if there is a shift that they are a manager of.

**Comment by DeD1rk** [comment]
Ask board for that ;) They can set the permissions from the society admin (should use the 'chair permissions' field)


But also, don't just give societies this. Societies don't normally have a borrelbrevet and aren't tied to board so closely. So I'm not sure of a scenario where a society would have to do a borrel if they don't have CAD  (or members of CAD) there
