### ISSUE TITLE
Website Calendar List; that it displays 1 event at a time.

### ISSUE THREAD

**Issue by ArlindeDaanen** [svthalia/concrexit#3800]
### What?

Instead of this, that you can click on all the events and that they are all open:
<img width="1327" alt="Screenshot 2024-09-25 at 18 24 09" src="https://github.com/user-attachments/assets/871ca8ca-ba8f-490c-9031-ade8c7bf8a66">
That when you click on the next event you want to open, that the one that was already open; closes.
So that it is only this:
<img width="1325" alt="Screenshot 2024-09-25 at 18 25 23" src="https://github.com/user-attachments/assets/1c25fb37-fb12-4b90-9eea-8e6fc50a16b5">

### Why?

Because then it could give a better overview.

### How?

Probably Javascript

**Comment by ColonelPhantom** [comment]
We discussed this a bit in today's meeting and are not sure it's a good idea. I'll leave this open with a request-for-comments label for now.
