### ISSUE TITLE
People that do not extend their membership at the start of the year are not kicked from committees/guilds

### ISSUE THREAD

**Issue by vincevd1** [svthalia/concrexit#3801]
### Describe the bug
When a person does not extend their membership by paying their contribution at the start of the year they are put as an old member, however they can still be in committees/guilds even though they are not part of the association anymore

### Example
1. Go to the following user https://thalia.nu/members/profile/2877
2. They are a former member
3. They are still part of the soccer guild

### Expected behaviour
They should have been put out of the soccer guild on the 31st of August. However this might prove detrimental if we do this right away on the 1st of September because some members might not have had time to extend their membership. That's why they should be kicked after some fixed time if their membership isn't extended (2 months for example or when their data is minimized)

**Comment by DeD1rk** [comment]
See https://github.com/svthalia/concrexit/issues/3437. Back then, while there hasn't been much discussion, I think our conclusion was that keeping memberships up to date (including kicking people out of committees if they leave thalia) is and should remain the responsibility of the board (specifically internal affairs) as well as the chair of each committee/society.
For the sake of security, I made people with no membership unable to use any permissions granted on the basis of being a committee member. 

We could periodically send an email to the board listing non-members in a committee/society. I'd personally prefer that over actually changing memberships.

**Comment by vincevd1** [comment]
Yeah, maybe changing people's enlistment in committees automatically could possibly cause problems but sending an email around 1 or 2 months after the start of the year with all people without an active membership who are in a committee is a good idea.

**Comment by T8902** [comment]
I mean if they can't execute their committee rights when they don't have a membership then I don't really see the point. Committees and board should keep this up to date together. 


> Yeah, maybe changing people's enlistment in committees automatically could possibly cause problems but sending an email around 1 or 2 months after the start of the year with all people without an active membership who are in a committee is a good idea.
