### ISSUE TITLE
Switch to ruff for formatting

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3817]
### What?
[ruff](https://docs.astral.sh/ruff/) has a formatter and import sorter that is much faster than black and isort. I think it would be nice to switch to that.

### Why?
Nicer dev experience.

### How?
- Change the depenencies.
- Update configurations in pyproject.toml and .pre-commit-config.yaml.
- Update the Makefile
- Update the README
- Update vscode settings to enable formatting with ruff onsave, and disable isort and black.

**Comment by ColonelPhantom** [comment]
Sounds good, will there be any differences between the style black uses and what ruff will do?

**Comment by DeD1rk** [comment]
Here's an overview of the differences from black: https://docs.astral.sh/ruff/formatter/black/. 
I get 7-9 lines in total.

**Comment by ColonelPhantom** [comment]
Differences seem pretty small, nice! That said I do get 142 files changed (+200, -68) when I run `ruff format`, mostly because of an extra newline before imports. When I ignore the files with only 1 line changed I get 12 files.
