### ISSUE TITLE
Add announcements to API

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#3830]
### What?
Add an announcements endpoint to the API.

### Why?
We would like to be able to show announcements in the app.

### How?
The website currently collects and displays announcements. We should collect these with plain-text as well as rich-text, and add an endpoint to fetch the plain-text version (for example).

**Comment by rodepanda7** [comment]
I really like the announcements API. However, I have a little issue when using it for the app. Usually, APIs have a count with the number of items in the list. An example is the frontpage-articles API where the results look like this
```
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "pk": 3,
      "title": "Staging server",
      "content": "<p>This is a staging environment, used for testing purposes only.</p>"
    }
  ]
}
```
However, in the current API the result looks like this:
```
[
  {
    "content": "<p>THIS IS A STAGING ENVIRONMENT</p>",
    "closeable": false,
    "icon": "bullhorn",
    "id": 3
  },
  {
    "content": "<p>\n    You don't have a profile picture yet! Upload one on your\n    <a href=\"/user/edit-profile/\">profile page</a> so that the other members know who you are.\n</p>\n",
    "closeable": false,
    "icon": "address-card",
    "id": null
  }
]
```

**Comment by ColonelPhantom** [comment]
We have decided to work around the issue Floris mentions here in the app.
