### ISSUE TITLE
Not allowed to lower the price after registration has started

### ISSUE THREAD

**Issue by annalorenz123** [svthalia/concrexit#3856]
### Describe the bug

After the registration has started (but thalia pay is still disabled) you are not allowed to adjust the entrance fee. I get that you are not allowed to up the price, but I think it's nice to be able to lower it.
### How to reproduce

1. Organize Legoland
2. Rent the lego
3. Get a very nice discount from the lego guy
4. Have less expenses
5. Want to lower the price, but this is not possible :(

**Comment by T8902** [comment]
I don't really like this idea

**Comment by Noah-marc** [comment]
@T8902 what do you not like about it ? 

Like I agree with Anna that it should not be possible to up the price. 

The only reason against it that I can think of is that some people might not register for the event if the initial price was too high for them, but would register for the updated lower price.

Nevertheless, not being able to update it when the opportunity arises also sucks.

**Comment by ColonelPhantom** [comment]
Yeah, if someone already paid, then we would need to adjust their payment that has already been done, which is really ugly IMO.

**Comment by annalorenz123** [comment]
Yeah this sounds pretty tricky indeed. I will close this issue for now.
