### ISSUE TITLE
Event page map not working

### ISSUE THREAD

**Issue by rkoelewijn** [svthalia/concrexit#3870]
### Describe the bug
When you go to the page of an event, the map showing the location of the event is not working/loading. 

### How to reproduce
1. Go to an event (e.g. https://thalia.nu/events/christmas-dinner-2024/)

### Expected behaviour
It is supposed to show a map of the location. 

### Screenshots
![image](https://github.com/user-attachments/assets/8e7a0649-3016-4fad-8294-390d2d0f23bc)

**Comment by DeD1rk** [comment]
That's a google cloud billing issue for which we'll bother rick
