### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#570]
In GitLab by @se-bastiaan on Feb 9, 2018, 23:43

### One-sentence description

Improve test coverage

### Why?

It will make our lives easier.

### Current implementation

There are a couple of tests.

### Desired implementation

100% coverage.

### Tasks

- [ ] events
- [x] registrations
- [ ] photos
- [ ] members
- [ ] activemembers
- [ ] pizzas
- [ ] documents

etc.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Feb 13, 2018, 10:05

Shall we set this up as a milestone?

**Comment by pingiun** [comment]
We'll close this in favour of more concrete ways to improve code quality
