### ISSUE TITLE
Improve statistics

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#61]
In GitLab by @thomwiggers on Aug 14, 2016, 22:18

### One-sentence description
Improve statistics

### Changed behaviour

After merging !46 (ref #9), we could improve the statistics page.

Suggestions:
- Add statistics about event attendance sorted by event type (from #389)
- Pizza chart. Showing percentages of everything > 5% with a max of 10 and everything else is 'other'
- Top 10 memberships of committees
- Percentage of active members compared to non-active members
- Bar chart with number of members per committees.
- Events heatmap with number of events per week

Also, some header on the page are unclear. As mentioned in #366.

**Comment by thaliawww-service** [comment]
In GitLab by mstiphout on Sep 28, 2016, 19:02

Aucke and I will be working on this, starting with the pizzas. This is because the data is saved to the old database, contrary to beerdata which is owned by the (other) borrelcie. We will have a look at event data after this.

**Comment by thaliawww-service** [comment]
In GitLab by mstiphout on Nov 9, 2016, 21:30

We spent today working on our setup and have come to the point where we only need to write the query that calculates the pizza. We might need some graphics for 'badges' to show certain levels of achievement (i.e. a bronze medal for eating 10 pizzas). We have to look at translation as well.

**Comment by thaliawww-service** [comment]
In GitLab by mstiphout on Nov 30, 2016, 20:18

(at)all 

Hallo, wij zijn momenteel redelijk ver met de personal statistics. Graag zouden we van jullie horen wat voor statistieken jullie leuk vinden om te zien. We hebben zelf natuurlijk al een hoop ideeën, maar schiet los.

Het draait hier om persoonsgebonden statistieken zoals bijvoorbeeld het totaal aantal bestelde pizza's/bezochte evenementen, niet om verenigingsstatistieken zoals aantal leden.  We zullen niet overal de stats voor hebben, maar brand vooral los; mogelijk kunnen we alsnog de benodigde statistieken gaan verzamelen.

**Comment by thaliawww-service** [comment]
In GitLab by gmulder on Nov 30, 2016, 20:28

Hoeveel gratis zonnebrillen iemand heeft...

**Comment by thaliawww-service** [comment]
In GitLab by mstiphout on Nov 30, 2016, 21:02

Van Luuk: aantal afmeldingen. Degene met de meeste afmeldingen wordt geshamet.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 6, 2016, 16:35

Zoengraaf

**Comment by thaliawww-service** [comment]
In GitLab by mstiphout on Apr 28, 2017, 17:39

removed assignee

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on May 3, 2017, 21:07

Ik heb nieuwe statistieken issues hierin gemerged.

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Apr 10, 2018, 14:14

created branch [`58-improve-statistics-pizza`](https://gitlab.science.ru.nl/thalia/concrexit/compare/master...58-improve-statistics-pizza)

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Feb 20, 2019, 20:11

https://github.com/qlik-oss/picasso.js Look like a good library

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 27, 2019, 20:06

assigned to (at)jhorst

**Comment by thaliawww-service** [comment]
In GitLab by @mtsatsev on Feb 19, 2020, 21:11

unassigned (at)jhorst

**Comment by se-bastiaan** [comment]
Maybe we could add statistics about our photo albums and the number of photos.

**Comment by mtsatsev** [comment]
What exactly do you mean by that /

**Comment by se-bastiaan** [comment]
So we have albums and photos. We could add graphs that show the number of photos per album, the number of photos per year or something like it. Just some idea.

**Comment by pingiun** [comment]
Closed by #1899
