### ISSUE TITLE
Handle re-registrations after data minimisation

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#706]
In GitLab by @se-bastiaan on Sep 19, 2018, 16:21

### One-sentence description

Handle re-registrations after data minimisation

### Why?

Because we need to minimise data and this might cause issues with renewals in ~registrations 

### Current implementation

None

### Desired implementation

Handle renewals of members of whom data was minimised by allowing them to re-enter the data.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Sep 19, 2018, 20:36

We should probably also add some 'are you trying to register while you already exist'-detection based on email addresses.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Sep 19, 2018, 21:14

You mean like this? https://gitlab.science.ru.nl/thalia/concrexit/blob/master/website/registrations/models.py#L248

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Sep 20, 2018, 10:45

Exactly, great that we already have that. Maybe we can extend it...

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 26, 2019, 22:34

Since renewal is already possible for existing user accounts we could just add the user's information to the renewal in the admin. The responsibility of checking if the information is available is then with the board. This way we prevent over engineering this, since I do not think this will happen that often.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Sep 17, 2019, 09:58

We have our first case here. User id 1073.

**Comment by thaliawww-service** [comment]
In GitLab by @pingiun on Dec 19, 2019, 15:03

There have been 7 cases since

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 16:15

Another 2 today. We  need to either block these renewals  or  allow them to re-enter their information

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 16:22

assigned to @se-bastiaan

**Comment by PeaceDucko** [comment]
@se-bastiaan is this issue still relevant? And if so is there any way to replicate it in a way to try and solve it?

**Comment by pingiun** [comment]
This doesn't happen very often so I moved this to medium priority
