### ISSUE TITLE
Multiple organisers per event

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#786]
In GitLab by @se-bastiaan on Nov 29, 2018, 18:19

### One-sentence description

Multiple organisers per event

### Motivation

I noticed that since the introduction of the Partnercie (once again) multiple committees (and the board) involved in events increased (Lunches are board + partnercie, laser tag was evc + partnercie). It would be quite useful if an event can have multiple organisers. With the new societies this might happen even more often, think 'EVC + board game society'.

### Desired functionality

Select more than one organiser per event.

### Food for thought

- Currently you can only select the groups you belong to as organiser unless you're a board member. That's not useful if you want to add a group as organiser that you're not in
- The organiser determines the mailing list that is used for the unregister notifications. Should all organisers have a mailing list to enable that option? Do we send all organisers that email?

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 12, 2018, 21:25

We think that this may be useful but it doesn't have priority.

**Comment by thaliawww-service** [comment]
In GitLab by lschernthaner on Nov 27, 2019, 16:59

assigned to (at)lschernthaner

**Comment by thaliawww-service** [comment]
In GitLab by lschernthaner on Nov 27, 2019, 18:58

unassigned (at)lschernthaner

**Comment by JobDoesburg** [comment]
More food for thought: we could decide to use Django guardian to manage per-object permissions (though that might be too much overkill for this simple feature)

**Comment by se-bastiaan** [comment]
I think that is a bit overkill for something that is now a ForeignKey and would become a ManyToMany field.

**Comment by JobDoesburg** [comment]
Right now exactly this is implemented in the `sales` app and it really is easy and fun to change
