### ISSUE TITLE
Data minimization on payments and event registrations after 7 years.

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#880]
In GitLab by @JobDoesburg on Jun 2, 2019, 15:35

### One-sentence description

Data minimization on payments and event registrations after 7 years.

### Motivation

The privacy office of the RU has indicated that there are no grounds for Thalia to keep data of payments or event participation after 7 years (the legal obligatory time to keep this information). So in order to be fully compliant to the AVG/GDPR we should maybe delete this information after 7 years.

### Desired functionality

7 years after an event, information of who attended what activity should be removed and whether they paid, and how. 
It would be nice if we can keep track of the amount of participants at that activity.

### Suggested implementation

Apart from that I can imagine this is not quite easy, I have no idea.

Note that this request is only based on information provided by the Radboud University privacy office. But the Technicie I'm sure also have an grounded opinion about this. So if you guys think it is unnecessary to remove this data because of reasons, and you think it is compliant to the AVG/GDPR that is fine as well! This is just passing on information actually.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jun 3, 2019, 17:20

> It would be nice if we can keep track of the amount of participants at that activity.

If we replace the member in the registration with a value in the name field we essentially removed the information and kept the amount of registrations. You know how many registrations and whether they were present (a value we could set to `False`) is all that would be left. Especially since we can easily remove payments older than 7 years, which would set the payment status to 'No payment'.

Don't really think it is that hard actually. Just needs careful execution and tests.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jun 3, 2019, 17:20

changed due date to June 01, 2019

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jun 3, 2019, 17:20

changed due date to June 01, 2022

**Comment by pingiun** [comment]
As we will be using payments more and more, this is becoming a high priority
