### ISSUE TITLE
Guest registration for events

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#920]
In GitLab by tkleinbreteler on Sep 10, 2019, 11:35

### One-sentence description

Guest registration for events

### Motivation

Workshops have bad visitor numbers. So as solution we have asked the R&VO (R&BO) coordinator to invite non-Thalia members. There is however no easy way for them to register.

### Desired functionality

Add an option to make non-member registration possible.

### Suggested implementation

Create a form that creates a non-member registration for someone with an email confirmation.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Sep 12, 2019, 07:52

This will need some special consideration with regards to them agreeing to Thalia's privacy policy for processing this information, and the terms of Thalia events.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Sep 16, 2019, 22:36

You could have an email address available for them to register and add them manually to the registration list.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Oct 30, 2019, 22:15

I think there are more use cases for such a feature: think of alumni borrels, the symposium or other educatie-events, some EVC events maybe.

And although there are solutions to do this easily not via the Thalia website, it shouldn't be too hard to implement either.

**Comment by pingiun** [comment]
As we don't want increased problems with having an open field that bots might click on, or have to deal with the privacy processing, we will be closing this. The solution for committees is to manually add people to the registration list, and they could have people send an email to the committee for that.
