### ISSUE TITLE
Thalia Pay: Add an option to membership registrations to pay with Thalia Pay

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#935]
In GitLab by @JobDoesburg on Oct 16, 2019, 20:24

### One-sentence description

Add an option to membership renewals and registrations to pay with Thalia Pay 

### Motivation

Everyone wants to do this via Thalia Pay remotely!

### Desired functionality

During registration (or after registration is approved, which is easier to build but less user friendly) people should have the possibility to immediately add a bank account and select payment via Thalia Pay.

### Suggested implementation

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Oct 23, 2019, 18:55

assigned to @JobDoesburg

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Oct 23, 2019, 18:55

unassigned @JobDoesburg

**Comment by Jorritboer** [comment]
What is the progress on this? Seeing as we are unsure if the board room can be open in the beginning of the year, having this feature would be great so people can pay for their membership regardless.
