### ISSUE TITLE
Thalia Pay: Add an option to membership renewals to pay with Thalia Pay

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#936]
In GitLab by @JobDoesburg on Oct 16, 2019, 20:26

### One-sentence description

Add an option to membership renewals to pay with Thalia Pay 

### Motivation

Because everyone wants to pay their contribution remotely via Thalia Pay and not come to a bbq

### Desired functionality

Just a 'Pay with Thalia Pay' button while requesting membership renewal (if a bank account is added, otherwise show a message that if they do add a bank account they can pay with Thalia Pay).

### Suggested implementation

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Oct 23, 2019, 18:55

assigned to @JobDoesburg

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Oct 23, 2019, 18:55

unassigned @JobDoesburg

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Oct 30, 2019, 22:43

assigned to @JobDoesburg

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Nov 13, 2019, 20:14

Will be implemented this way: 

In the email stating that the renewal has been accepted, people will find a URL 'pay with Thalia Pay'

**Comment by JobDoesburg** [comment]
Closed by #1048
