### ISSUE TITLE
Thalia Pay: Add user-instructions for activating in bankaccounts

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#947]
In GitLab by @JobDoesburg on Oct 30, 2019, 21:09

### One-sentence description

Add information about Thalia Pay to bankaccounts

### Motivation

People should know what Thalia Pay is and how to activate it.

### Desired functionality

Something about that if you sign a direct debit, it will be used for Thalia Pay etc.

### Suggested implementation

Maybe ask the board? Or just come up with something ourselves. It should not be too extensive in my opinion, just something short.

**Comment by JobDoesburg** [comment]
- Make the "Pay with Thalia Pay" appear as disabled button for people that do not have Thalia Pay enabled yet, with redirect to BankAccountCreateView.
- Write some extra explanation on the BankAccountListView and BankAccountCreateView
- Maybe clarify the PaymentProcessView?

And on release we can send an email and add a banner to the site.
