### ISSUE TITLE
Remove Payment type None

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#957]
In GitLab by @JobDoesburg on Nov 13, 2019, 20:54

### One-sentence description

Remove Payment type None

### Why?

It is weird to have payment objects for payments that not yet have taken place. It makes much more sense to just have no payment then.

### Current implementation

For registrations, we now make payments for every accepted registration, and change the type when it really is paid.

### Suggested implementation

Make a payment object upon payment.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Nov 17, 2019, 00:15

mentioned in commit 8e44cbd94ba2b6ce4708a91ca4621d2fbb75814b

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Nov 17, 2019, 13:27

mentioned in commit f3c83f9c771533da3ee35a94892fe45d2df34226

**Comment by thaliawww-service** [comment]
In GitLab by @mtsatsev on Nov 20, 2019, 20:10

assigned to @mtsatsev

**Comment by thaliawww-service** [comment]
In GitLab by @mtsatsev on Dec 4, 2019, 19:08

unassigned @mtsatsev

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 8, 2020, 20:31

mentioned in commit f2f7de77cad420fc9922d8665a8664a4fdc17323

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 8, 2020, 20:39

mentioned in commit 0735192decbed1255a5cf4dd45b668881275c7f1

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 8, 2020, 20:56

mentioned in commit 60b433c4215b4fdacdaf6c52c348a6ea9f88f46c

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 8, 2020, 21:09

mentioned in commit 720a246640fad09bb46537644c0f3c2a05255a68

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 8, 2020, 21:10

mentioned in commit c08cb449df4b7a3dfee7de242eb86b2dc926806d

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 22, 2020, 16:28

mentioned in commit b3b0c03f7b7ed6b63f03b12a29de54e47e4f92af

**Comment by se-bastiaan** [comment]
#1054 closes this issue
