### ISSUE TITLE
Support GIFs as profile pictures

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#960]
In GitLab by jguijt on Nov 19, 2019, 13:07

Is it pronounced gif or jif?

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Nov 27, 2019, 19:51

closed

**Comment by thaliawww-service** [comment]
In GitLab by jguijt on Nov 28, 2019, 10:31

reopened

**Comment by thaliawww-service** [comment]
In GitLab by jguijt on Nov 28, 2019, 10:31

Not fixed yet

**Comment by thaliawww-service** [comment]
In GitLab by jguijt on Nov 28, 2019, 10:32

Seksgod Sebbie zei dat het nodig is om dan 1MB plaatjes te supporten, maar:
* Je kan ook GIFs alleen als avatar gebruiken, naast een standaard profielfoto. Zo hoeft een GIF niet 1000x1000 te zijn.
* Je kan ook een geheugenlimiet stellen op de grootte van GIFs, zodat jullie je geen zorgen hoeven te maken over compression etc.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Nov 28, 2019, 10:39

https://stackoverflow.com/questions/41718892/pillow-resizing-a-gif

**Comment by pingiun** [comment]
Having some pictures that are constantly moving is annoying for users
