### ISSUE TITLE
Renewals not processed correctly on uniqueness constraint for membership id

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#962]
In GitLab by @JobDoesburg on Nov 20, 2019, 20:08

### One-sentence description

Renewals not processed correctly on uniqueness constraint for membership id

### Current behaviour / Reproducing the bug

1. Do a renewal for 1 year
2. Approve it, add a payment, finish it fully etc
3. Do a renewal for the rest of your study
4. Approve it
5. Process a payment
6. Breakage

(the payment gets processed, the membership is correctly added to the user, but the renewal does stick at 'approved' (with a processed payment attached))

### Expected behaviour

Do not crash

**Comment by JobDoesburg** [comment]
Could very well be that after the rewrite with `create_payment` this is not a problem anymore
