### ISSUE TITLE
sync_mailinglists errors

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#963]
In GitLab by @joren485 on Nov 26, 2019, 11:36

### One-sentence description
The `sync_mailinglists` generates many errors.

### Description

Currently, the `sync_mailinglists` generates many errors (see the [server sentry issues](https://sentry.io/organizations/thalia/issues/?project=1470866)).
These should either be caught or the underlying bug should be fixed.

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Dec 5, 2019, 15:14

Because we released v29.1 today (which includes the G Suite user sync), we resolved all issues. We will have to see which issues are still present in the current version.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 18, 2019, 19:40

Most issues we currently only have left are 503 errors from the API and ConnectionResetErrors so we should just ignore those because it retries later.

**Comment by pingiun** [comment]
No idea what this is about anymore
