### ISSUE TITLE
Make Thabloid .pdf only available for authenticated users

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#965]
In GitLab by @JobDoesburg on Dec 3, 2019, 16:44

### One-sentence description

Thabloids are crawable by Google, and we discussed that we rather not have that.

### Current behaviour / Reproducing the bug

Google crawls our Thabloids. You can search for text fragments

### Expected behaviour

Not have them appear in Google. 
We do not necessarily have them only available on login, but add them to robots.txt to disallow search machines to display them would be nice

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Dec 3, 2019, 17:12

Small note: we currently do not have a `robots.txt` file.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 3, 2019, 17:39

Who is 'we'? Thabloidcie?

Maybe we should just put the Thabloids behind the authentication completely? I'm guessing that Google is indexing the PDF files.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Dec 4, 2019, 12:02

We = thabloidcie yeah. 

Authentication is also fine to me I guess. Also curious on (at)jdusseljee's opinion on this. Do partners check the thabloid on the website? (Probably not)

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Dec 4, 2019, 12:05

In my year as commissioner of external affairs recruiters did check the Thabloid on the website.

**Comment by thaliawww-service** [comment]
In GitLab by wtheunisse on Dec 5, 2019, 11:42

Don't really have an opinion on this, but would like to add that I've heard about first years students who read the Thabloid (not having an account) before deciding they wanted to study here.

**Comment by thaliawww-service** [comment]
In GitLab by jdusseljee on Dec 5, 2019, 12:02

I also know that some recruiters check the Thabloid on the website.
Especially Recruiters who are interested in placing promotions in the
Thabloid like to see it in advance.

**Comment by se-bastiaan** [comment]
@joren485 can this be solved by using a robots.txt?

**Comment by joren485** [comment]
Apparently not ([source](https://support.google.com/webmasters/answer/6062608)). It might be possible by sending the `X-Robots-Tag: noindex` header.

However, I don't think blocking these PDFs, but keeping them publicly accessible, is a good idea. There will always be sites scraping sites for PDFs even with a draconic `robots.txt` (or something similar).
If you do not want a webpage/PDF to be scraped, put authentication on it. Otherwise, you will be scraped by some shady website that is indexed by Google. In short, I am not sure that asking bots to not scrape the Thabloids solves the problem.

Maybe @JobDoesburg could explain a bit more what the Thabloidcie wants to accomplish.

**Comment by JobDoesburg** [comment]
The point most people had was that we didn't really like the fact that you can easily search for a name of a person on google and directly find a thabloid in which he/she is mentioned. We didn't think it was a true problem that the thabloids are publicly available, but we thought it would nice if they were a bit harder to find than on the first hit on Google. I think most obvious search-engines respect so than a `X-Robots-Tag: noindex` header would do the job.

Another idea might be to put authentication on the pdf version, and keep the image preview publicly available. What do you think about that?

**Comment by se-bastiaan** [comment]
Only having the directly viewable version available does make sense to me, but doesn't google crawl texts in images as well?

**Comment by JobDoesburg** [comment]
> Only having the directly viewable version available does make sense to me, but doesn't google crawl texts in images as well?

I think they do secretly, but I don't think they publish it as search results

**Comment by se-bastiaan** [comment]
I think that may be the best solution then. Also given that people are then allowed to view the thabloid but not completely download it unless you are a member. That makes sense to me.

**Comment by JobDoesburg** [comment]
I got a message from @mariesophiesimon about this and that motivated me to start working on this. But the way it is written makes it pretty hard to realize this.

**Comment by se-bastiaan** [comment]
Depends on what the exact message was, I think that we may be missing some context?

If it is easy to make them completely private then we could do that and leave the issue open to make the images available later? I'm not sure what the exact problem is that you are running into. Imo it could just all be private.

In any case, the files need to be moved on the server to be able to do this. That is possible by using a migration and running python code or asking @svthalia/server to do it.

**Comment by mariesophiesimon** [comment]
Hey, so the board decided that it would be nice to have the Thabloid completely private, so like the photos you should only be able to see them once you are logged in as a Thalia member. If recruiters want to see Thabloids we will handle that differently, but this seemed like the best option to us to really avoid all issues with people just randomly finding the Thabloid.
