### ISSUE TITLE
Bug: 'view site' from event detail admin forwards to wrong url

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#969]
In GitLab by @JobDoesburg on Dec 4, 2019, 19:43

### One-sentence description

Improve navigation between admin views for event admin

### Motivation

Currently it works terrible. 

### Desired functionality

On save, go to the view that makes sense instead of very often go back to the event overview. 

Also maybe provide buttons that take you to the event detail overview page, or to the frontend view, etc etc

I don't yet have clear suggestions but I think everyone can think of their own what makes sense.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 18, 2019, 19:14

This should be specified better. The edit view currently goes back to the previous page where you clicked on 'edit'. And there is a 'view on site' option in the edit view already?

**Comment by JobDoesburg** [comment]
I have just found the exact bug again:

When I hit this 'view site' button from the event detail admin:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/7915741/117675005-79bf3f00-b1ac-11eb-9011-27ba5d4c92b5.png">

I get this error:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/7915741/117674876-58f6e980-b1ac-11eb-93bc-4a3e896e5513.png">
