### ISSUE TITLE
Use html email template for all emails we send

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#971]
In GitLab by @JobDoesburg on Dec 4, 2019, 20:04

### One-sentence description

Use html email template for all emails we send

### Why?

It looks nice

### Current implementation

We only send plaintext mails, except for the information check emails

### Suggested implementation

Use the information check email template

**Comment by thaliawww-service** [comment]
In GitLab by @mtsatsev on Feb 19, 2020, 20:02

assigned to @mtsatsev

**Comment by thaliawww-service** [comment]
In GitLab by @mtsatsev on Feb 19, 2020, 21:13

unassigned @mtsatsev

**Comment by se-bastiaan** [comment]
I believe sending plain text emails is perfectly fine for what we do. Only for the information check this made sense since we have that table in there. But only adding this because it looks nice is not a good reason imo since it adds a lot of overhead and decreases maintainability of the emails.

**Comment by JobDoesburg** [comment]
I think if we implement #1305 the maintainability should not be too much of a problem. And it looks really nice. I mean, look at this beauty:
![Uploading Schermafbeelding 2020-10-15 om 11.19.48.png…]()

**Comment by se-bastiaan** [comment]
Screenshotting an automatically dark mode changed email does not count :p
