### ISSUE TITLE
Guest registrations can not be marked paid

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#978]
In GitLab by @lukovdm on Dec 5, 2019, 15:28

### One-sentence description

When there is a guest registration for an event that has a price. If this person is marked as paid, an error occurs.

Associated sentry error: [https://sentry.io/organizations/thalia/issues/1372921592/?project=1463433&referrer=slack](https://sentry.io/organizations/thalia/issues/1372921592/?project=1463433)

### Current behaviour / Reproducing the bug

1. Create an event with registrations and a price
2. Register a guest user for this event
3. Try to mark this guest user as paid
4. Breakage

### Expected behaviour

1. Create an event with registrations and a price
2. Register a guest user for this event
3. Try to mark this guest user as paid
4. either you can't mark their payment status at all or you can. However marking a guest user as paid creates a lot more complication in the payments module.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 6, 2019, 14:47

Different issue

**Comment by thaliawww-service** [comment]
In GitLab by @LCKnol on Feb 12, 2020, 19:39

assigned to @LCKnol

**Comment by thaliawww-service** [comment]
In GitLab by @LCKnol on Feb 12, 2020, 19:53

I can't reproduce this. I've created an event with registrations and a price, when I register a guest at Home>events>event-name>add I can enter a name, save and mark this guest as paid. The page then reloads fine, and the payment is still there after closing and reopening the page.

**Comment by se-bastiaan** [comment]
I am also unable to reproduce this.
