### ISSUE TITLE
Automatically send email with G Suite calendar id invite to member on joining committee

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#980]
In GitLab by @JobDoesburg on Dec 6, 2019, 14:23

### One-sentence description

To prevent ourselves from explaining this over and over

### Desired functionality

If a members joins a committee they will receive an email from Thalia stating 'hey you have joined committee x, fun times, here you also have the calendar stream for this committee'

### Suggested implementation

Probably we will need to introduce a field in the active member group model that contains the id for their calendar. And then we can use that one to send an email to the new members

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 6, 2019, 14:32

This increases the required maintenance and introduces more tasks for us. The whole idea of G Suite is that we decrease our workload. With documentation the committees should be able to organise this themselves. And if they do not want to use the Google Calendar we created then that is fine. They can add individual addresses to the calendar or create a subscribe link. Whatever they want. After the first introduction committees will be the ones responsible for their calendars just like they were before Nextcloud.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Dec 6, 2019, 14:53

I really really think that people will keep sending www(at)thalia.nu emails requesting access to their calendar because they forgot the ID (this is what I also always said in case of problems I couldn't solve in 1 minute: just send an email). By including it in concrexit, we only need to store it once when we create it (we need to create the calendar anyhow, but would be nice if there were an API for that) and then never think about it anymore.

**Comment by thaliawww-service** [comment]
In GitLab by @JobDoesburg on Dec 6, 2019, 16:22

So required maintance: yeah maybe, like every feature.

More tasks for us: no, less tasks. It only is work for us when we create the stream (which is exactly once, and that is already done manually). And throughout the year it is less tasks

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Dec 6, 2019, 16:30

There are too many edge cases for this to work properly. A lot of committees/societies might not want a calendar. Some committees/societies might want many calendars (e.g. every separate D&D group).

I completely agree with @se-bastiaan that committees should be able to handle this themselves.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 18, 2019, 19:11

I think the way you created calendar for the almanac committee shows that we're unable to control who has which calendar.

**Comment by thaliawww-service** [comment]
In GitLab by @Legosteen11 on Feb 19, 2020, 20:27

I think this would be way too complicated. The best solution I came up with was adding an "Administration" part to the committee pages where these calendar invites could be shared or something. This would still be a bad solution because then the commissioner of internal affairs has to update this, or we have to add a feature to let the committee chair edit this.

What would be a much easier fix: every commission has access to G Suite Drive where you could easily add a document with all administration and links required!

**Comment by se-bastiaan** [comment]
I am closing this issue as a bit of cleanup, I don't think we will ever be able to do this since committees control themselves if they use and share the calendar we made at the beginning.
