### ISSUE TITLE
Deliver sliders or other large images as webp

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#988]
In GitLab by @pingiun on Jan 15, 2020, 20:56

### Why?
According to [Google PageSpeed](https://developers.google.com/speed/pagespeed/insights/?hl=nl&url=thalia.nu&tab=mobile), we can speed up our site by a lot by converting slider images to webp.

### Current implementation
Large pictures are all served as png, this is a good image format for things that need to be compressed lossless.

### Suggested implementation
Supply images as `<picture>` [with multiple sources](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Use_modern_image_formats_boldly)

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 15, 2020, 22:35

So what do you want to do exactly? Do you want to convert them on the fly on create new images for every single slide on disk? If you want to save the files to disk that could take some space if you want to serve both. And I don't think this makes the image loading stuff ~"easy and fun" with it being quite difficult already. At least, the drawback of complexity vs (supposed) loading time

I do think that increasing the JPG image quality that we save may help, because that's mostly the reason that these images are PNG: the JPEGs are horrible quality. I have changed the images to JPEG now and the warning in PageSpeed is goner. The one for image caching though? Maybe we should add that to the nginx config.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 15, 2020, 22:38

If Safari would support webp I would be in favour of converting every single image to webp, but unfortunately that is not the case: https://caniuse.com/#feat=webp. Even the last non-Chromium version of Edge has support.

2016 -> https://www.cnet.com/news/apple-ios-macos-tests-googles-webp-graphics-to-speed-up-web/

**Comment by se-bastiaan** [comment]
Safari 14 adds webp support, but only on macOS Big Sur and later :|

**Comment by se-bastiaan** [comment]
Note that React Native also has no WebP support without extra deps: https://reactnative.dev/docs/image#gif-and-webp-support-on-android

**Comment by pingiun** [comment]
This is now feasible: https://caniuse.com/?search=webp
