### ISSUE TITLE
Internet required to run tests

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#992]
In GitLab by @joren485 on Jan 26, 2020, 20:07

### Description
Internet required to run tests, because [`activemembers/signals.py` always initializes the G Suite API](https://gitlab.science.ru.nl/thalia/concrexit/blob/master/website/activemembers/signals.py#L15). This is not (and should not be) always necessary (e.g. when running tests).

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jan 26, 2020, 21:31

mmm it's better to initialise it globally because of the caching, but we should be able to disable it in test environments

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Jan 26, 2020, 22:07

This problem does not only occur with the tests, but also when running a development environment (i.e. `python website/manage.py runserver` does not work without internet).

**Comment by se-bastiaan** [comment]
We can borrow code to do this from https://github.com/GipHouse/website as soon as @lukovdm is done there :p
