### ISSUE TITLE
Miscellaneous annual files on document page

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#998]
In GitLab by nvoers on Feb 3, 2020, 14:50

### One-sentence description
The ability to add more yearly files on the document page. 

### Motivation
Normally things like the half year report are added as GM documents, but now we want to add yearly documents that are not necessarily discussed at a GM. We want to add a report from the societies on how well everything worked that year, as the society rules state that they should publish this.

### Desired functionality
A new section underneath the GMs, where miscellaneous or other documents can be added.

### Suggested implementation
See picture in the comments.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 3, 2020, 16:24

I don't get it? Do you want files on society pages? Or on documents pages?

**Comment by thaliawww-service** [comment]
In GitLab by nvoers on Feb 4, 2020, 11:05

woops, wrong title.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 11:06

Isn't this exactly what the `Association Documents` are for? What kind of documents are we thinking of? Could you adjust the description to use the 'Feature Request' template instead of 'Technical Change' and add a motivation?

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 14:43

So these are basically annual documents like the policy and report but in the category 'miscellaneous'.

Are there a lot of these kind of documents that are not part of a GM?

**Comment by pingiun** [comment]
This could be a good feature to have all kinds of annual documents, instead of the hardcoded 3 we have now

**Comment by pingiun** [comment]
We do not plan to work on this feature anymore so it will be closed to remove clutter
