### ISSUE TITLE
Expiration date on partner pages

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#999]
In GitLab by jdusseljee on Feb 4, 2020, 11:04

### One-sentence description

Can you add a functionality to set an expiration date on profile pages of partners.

### Motivation

Because it is pretty annoying to have to memorise the duration of all contracts. It would be way easier to just be able to set an expiration date when the contract enters.

### Desired functionality

An extra date field in the admin page when editing/creating a partner page. When this date has passed, the profile page should automatically be set to inactive (maybe send a mail to extern@ to let the extern know when this happens).

### Suggested implementation

-

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 11:30

Could you please use the feature request template?

**Comment by thaliawww-service** [comment]
In GitLab by jdusseljee on Feb 4, 2020, 14:34

I thought I already did that.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 14:37

Ah wait you removed the titles.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 4, 2020, 14:40

> to have to memorise

Don't you have a document for this? You don't have to memorise this. And are there that many contracts that are not 1 sept - 31 august?

We have removed this exact feature for vacancies because it was either not used or was already replaced by a simple sheet -> #877

**Comment by jendusseljee** [comment]
Sorry for the late response. 
If it is not too much effort to implement it would be nice if the website could just send an email to the partnercie for expiring profile pages. Most contracts indeed run from 1 sept - 31 august, but there are quite some companies that join us somewhere in the middle of the year.

It is not necessary but, in my opinion, it would be nice to have this automated as it would just be one less thing for the commissioner of external affairs to keep track of, reducing the overhead just a little bit.

**Comment by se-bastiaan** [comment]
The point is not that it is too much effort to implement. 

Fact is that we have implemented something like this before and it was _not used_. How will we know what we build is going to be used or is something that we can remove again after two years?

This may not be a piece of overhead anymore for the external affairs, but it will become a piece of overhead for us. Even though I believe you could have some administration of some kind to stay in contact with the partners right? It sounds like what you basically need is some kind of CRM.

**Comment by DeD1rk** [comment]
Not planned as there's plenty of reason not to do this, and there have been no requests for this recently. We can reopen if partnercie people really want it.
